'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/rpg/constants'),M=require('../src/rpg/model'),B=require('../src/rpg/combat'),F=require('../src/rpg/forms'),H=require('../src/rpg/health');
const V=require('../src/rpg/coupons'),Boss=require('../src/rpg/boss'),R=require('../src/rpg/rescue'),DT=require('../src/rpg/mortality'),X=require('../src/rpg/exploration'),G=require('../src/rpg/glossary'),S=require('../src/rpg/showcase');
const Draft=require('../src/rpg/action-drafts'),{createStore}=require('../src/rpg/store'),{createRpg}=require('../src/rpg'),{harness,state,fight,weapon,minRng}=require('./helpers/rpg-harness');
let ties=0;const varied=(lo,hi)=>lo+(ties++%(hi-lo));
const controls=v=>v.components.flatMap(r=>r.toJSON().components),button=(v,label)=>{const c=controls(v).find(c=>c.label===label);assert.ok(c,label);return c.custom_id;};
function runtime(seed=state()){const h=harness();require('../src/rpg/activities').migrate(seed);require('../src/rpg/skills').migrate(seed);seed.config.gmRoleIds=['gm'];seed.config.playerRoleIds=['player'];let saved=C.clone(seed);h.deps.database={assertLease(){},load:async()=>C.clone(saved),save:async(_,before,next)=>{assert.equal(saved.revision,before.revision);saved=C.clone(next);}};return h;}
function npc(s,extra={}){const t=B.validateNPC(s,{...F.defaults('npc'),name:'守卫',hpMax:100,...extra});t.id=C.id('t');t.version=1;t.published=true;s.npcTemplates[t.id]=t;return t;}
function pool(s,mode='bundle',entries){const t=weapon(s,{weightKg:0});return V.publish(s,{name:'补给券',description:'私密补给',mode,entries:entries||[{ref:t.id,quantity:2}]});}
function grant(s,v,uid='1',quantity=1){V.grant(s,v.id,[{uid,characterId:s.players[uid].id,quantity}]);}
function map(s=state()){const f=F.create(s,'GM','mapcategory');f.data.name='基地';const cat=F.publish(s,f),n=npc(s,{randomStrength:true,levelMin:91,levelMax:91,anomalyRank:'X'}),rf=F.create(s,'GM','room');Object.assign(rf.data,{name:'机房',categoryIds:[cat.id]});F.publish(s,rf);s.config.rpChannelId='hidden';const m=X.create(s,'GM','map-channel','基地',1,5,'random',cat.id);X.generate(s,m,minRng);return{s,m,n};}
function arrived(s,m,ref='2,0'){X.publish(s,m);X.join(s,m,'1');X.join(s,m,'2');for(const p of Object.values(m.participants))p.cell=ref;m.revealed[ref]=true;m.cells[ref].touched=true;Boss.reconcile(s);return m.cells[ref].room.bossRequest;}

test('one bundle voucher creates all quantities once and remains redeemable when issuance stops',()=>{const s=state(),v=pool(s);grant(s,v,'1',2);v.enabled=false;assert.throws(()=>grant(s,v),/停止/);const f=V.preview(s,'1',v.id),r=V.redeem(s,'1',f.id);assert.equal(r.items.reduce((n,i)=>n+i.quantity,0),2);assert.equal(r.remaining,1);assert.deepEqual(V.redeem(s,'1',f.id),r);assert.equal(Object.keys(s.players['1'].inventory).length,2);assert.throws(()=>V.remove(s,v.id),/余额/);});
test('single choice only issues the selected physical template; limits reject invalid whole bundles',()=>{const s=state(),a=weapon(s,{name:'A',weightKg:0}),b=weapon(s,{name:'B',weightKg:0}),v=pool(s,'choice',[{ref:a.id,quantity:7},{ref:b.id,quantity:100}]);grant(s,v);const r=V.redeem(s,'1',V.preview(s,'1',v.id,a.id).id);assert.equal(r.items.reduce((n,i)=>n+i.quantity,0),7);assert.ok(r.items.every(i=>i.templateId===a.id));assert.throws(()=>pool(s,'bundle',v.entries),/最多100/);assert.throws(()=>pool(s,'choice',[{ref:a.id,quantity:101}]),/数量/);});
test('old coupons preview latest pool and bind pool/template versions and five minute deadline',()=>{for(const change of ['pool','template','expired','character']){const s=state(),v=pool(s);grant(s,v);const f=V.preview(s,'1',v.id);if(change==='pool')v.version++;if(change==='template')s.catalog[v.entries[0].ref].version++;if(change==='expired')f.expiresAt=0;if(change==='character')s.players['1'].id='replacement';assert.throws(()=>V.redeem(s,'1',f.id),/变化|更新|过期/);assert.equal(s.players['1'].couponBalances[v.id],1);assert.equal(Object.keys(s.players['1'].inventory).length,0);}});
test('overweight final bundle entry leaves no earlier item or voucher debit',()=>{const s=state(),a=weapon(s,{weightKg:0}),b=weapon(s,{weightKg:9999}),v=pool(s,'bundle',[{ref:a.id,quantity:1},{ref:b.id,quantity:1}]);grant(s,v);const f=V.preview(s,'1',v.id),p=C.clone(s.players['1']);assert.throws(()=>V.redeem(s,'1',f.id),/超重/);assert.deepEqual(s.players['1'],p);assert.equal(f.status,'ready');assert.equal(Object.keys(s.couponRedemptions).length,0);});
test('recruiting, paused or active battle and downed life prohibit redemption',()=>{for(const status of ['recruiting','paused','active','downed']){const s=state(),v=pool(s);grant(s,v);if(status==='downed')H.damage(s.players['1'],999);else{const b=B.createBattle(s,'battle','GM','战斗');B.join(s,b,'1');b.status=status;}assert.throws(()=>V.preview(s,'1',v.id),/战斗|倒地/);assert.equal(s.players['1'].couponBalances[v.id],1);}});
test('batch issuance validates all character bindings before changing any balance',()=>{const s=state(),v=pool(s);assert.throws(()=>V.grant(s,v.id,[{uid:'1',characterId:s.players['1'].id,quantity:3},{uid:'2',characterId:'wrong',quantity:4}]),/变化/);assert.equal(s.players['1'].couponBalances?.[v.id],undefined);assert.throws(()=>V.grant(s,v.id,Array(26).fill({uid:'1'})),/25/);});
test('showcase publishes only chosen owned gold/red instances and immediately omits transferred items',()=>{const s=state(),gold=M.issue(s,'1','seed_0_gold')[0],red=M.issue(s,'1','seed_0_red')[0],white=M.issue(s,'1','seed_0_white')[0];assert.throws(()=>S.select(s,'1',s.players['1'].id,0,[white.id]),/变化/);S.select(s,'1',s.players['1'].id,0,[gold.id]);assert.deepEqual(S.entries(s,'1').map(i=>i.id),[gold.id]);assert.ok(!S.entries(s,'1').some(i=>i.id===red.id));delete s.players['1'].inventory[gold.id];assert.deepEqual(S.entries(s,'1'),[]);});
test('glossary drafts and disabled terms never appear in player search, explanation and stable ID survive edits',()=>{const s=state(),t=G.publish(s,{name:'污染',description:'字'.repeat(4000)});assert.equal(G.search(s,'污染')[0].description.length,4000);t.published=false;assert.equal(G.search(s,'污染').length,0);const updated=G.publish(s,{name:'污染度',description:'说明'},t.id,t.version);assert.equal(updated.id,t.id);assert.equal(updated.version,2);assert.throws(()=>G.publish(s,{name:'x'.repeat(81),description:'说明'}),/名词|名称/);});
test('a single mixed strike downs player, ignores excess, retains assets and AP; second bar alone triggers death',()=>{const {s,b}=fight(),p=s.players['1'],a=b.actors[0];p.couponBalances={voucher:8};p.ap=321;const first=H.damage(p,1000,1);assert.equal(first.ignored,1000-first.before.hp);assert.equal(first.after.reserveHP,M.stats(p).maxHP);assert.equal(DT.settle(s,b,a),null);assert.ok(H.downed(p));assert.equal(p.ap,321);assert.equal(p.couponBalances.voucher,8);assert.ok(!a.deathId);H.damage(p,first.after.reserveHP);const d=DT.settle(s,b,a);assert.ok(d.id);assert.equal(s.players['1'],undefined);assert.equal(DT.settle(s,b,a),null);});
test('healing fills downed HP first and only excess revives, repeated downing replenishes second bar',()=>{const p=state().players['1'];H.damage(p,999);H.damage(p,8);const r=H.heal(p,8);assert.equal(r.reserveHealed,8);assert.equal(r.healed,0);assert.ok(H.downed(p));const next=H.heal(p,1);assert.ok(next.revived);assert.equal(p.hp,1);H.damage(p,999);assert.equal(p.life.reserveHP,M.stats(p).maxHP);assert.ok(H.downed(p));});
test('NPC retains single-bar death, standing second bar tracks HP maximum and downed increase does not heal',()=>{const s=state(),b=B.createBattle(s,'c','GM','NPC'),a=B.addNPC(s,b,npc(s).id,'enemy');H.damage(a.character,999);assert.equal(a.character.life,undefined);assert.ok(DT.settle(s,b,a));const p=s.players['1'];H.ensure(p);p.attributes.constitution++;M.syncHP(p);assert.equal(p.life.reserveHP,M.stats(p).maxHP);H.damage(p,999);H.damage(p,4);const old=p.life.reserveHP;p.attributes.constitution+=2;M.syncHP(p);assert.equal(p.life.reserveHP,old);});
test('burst switches from chosen defense to full passive armor after first bullet downs player without extra dice',()=>{const {s,b}=fight(),p=s.players['2'],a=b.actors[1];p.hp=1;const armor=M.publishTemplate(s,{...F.defaults('item','防具'),name:'护甲',defenses:{physical:4,magical:0,mental:0}});B.pause(b);M.equip(s,'2',M.issue(s,'2',armor.id)[0].id);B.pause(b,true);const before=H.snapshot(p);b.pending={id:'burst',targetId:a.id,targetCharacterId:p.id,attackerId:b.actors[0].id,attackName:'连射',hit:10,defenses:M.stats(p).defenses,shots:[{damage:{physical:10,mental:3}},{damage:{physical:10}}],conditions:[],armorWeakening:{type:'physical',amount:0},expiresAt:Date.now()+60000};const hit=b.pending;B.defend(s,b,hit.id,'none',()=>{throw Error('unexpected roll');});assert.ok(H.downed(p));assert.equal(p.life.reserveHP,before.maxHP-6);assert.equal(hit.result.perShot[0].health.ignored,12);assert.equal(hit.result.perShot[1].reduced.physical,4);assert.ok(!hit.result.killed);});
test('downed pending attack auto-defends at transaction boundary without waiting for a player deadline',async()=>{const {s,b}=fight();H.damage(s.players['2'],999);b.pending={id:'hit',targetId:b.actors[1].id,targetCharacterId:s.players['2'].id,attackerId:b.actors[0].id,attackName:'命中',hit:10,defenses:{physical:2},shots:[{damage:{physical:3}}],conditions:[],armorWeakening:{type:'physical',amount:0},expiresAt:Date.now()+60000};const h=runtime(s),st=createStore(h.deps);await st.load(s.guildId);await st.transact(s.guildId,'reconcile','GM',()=>null);const saved=st.snapshot(s.guildId);assert.equal(saved.battles[b.id].pending,null);assert.equal(saved.players['2'].life.reserveHP,14);});
test('downed actor loses drafts and casting but preserves paid counts, AP and eligibility as an attack target',()=>{const {s,b}=fight(),p=s.players['1'],a=b.actors[0],f=Draft.create(s,'1',{battleId:b.id,actorId:a.id,turnId:b.current.id,action:'move',params:{x:26,y:25}}),ap=p.ap,counts=C.clone(b.actionRound.counts);a.casting={count:1};H.damage(p,999,1);DT.interrupt(s,b,a);assert.equal(f.status,'cancelled');assert.equal(a.casting,undefined);assert.equal(p.ap,ap);assert.deepEqual(b.actionRound.counts,counts);assert.ok(B.liveActors(s,b).includes(a));assert.ok(!B.activeActors(s,b).includes(a));assert.throws(()=>M.drop(s,'1',Object.keys(p.inventory)[0]),/倒地/);assert.throws(()=>M.createOffer(s,'1','2'),/倒地/);});
test('downed conditions tick once per new action round and persist ledger on restore',()=>{const {s,b}=fight(),a=b.actors[1],p=s.players['2'],t=B.validateCondition({...F.defaults('condition'),name:'毒',levels:{一般:{difficulty:100,duration:{kind:'actions',count:5},worsenAfter:0,effects:[{target:'hp',amount:'2'}]}}});t.id='poison';t.published=true;s.conditionTemplates[t.id]=t;B.applyCondition(s,p,{id:t.id,severity:'一般'},minRng);H.damage(p,999,1);DT.interrupt(s,b,a);const hp=p.life.reserveHP;b.current=null;b.actionRound.completed=b.actors.map(a=>a.id);assert.ok(B.resetActionRound(s,b,minRng));assert.equal(p.life.reserveHP,hp-2);assert.equal(a.downConditionRound,2);assert.equal(p.conditions[0].remaining,4);const restored=C.clone(s),rb=restored.battles[b.id];assert.equal(B.resetActionRound(restored,rb,minRng),false);assert.equal(restored.players['2'].life.reserveHP,hp-2);});
test('ally treatment consumes healer item and quick action, heals recipient and RP stays on one receipt',()=>{const {s,b}=fight(),target=s.players['2'];H.damage(target,999);H.damage(target,4);DT.interrupt(s,b,b.actors[1]);const t=M.publishTemplate(s,{...F.defaults('item','药品'),name:'急救包',heal:'1d6',weightKg:0}),item=M.issue(s,'1',t.id)[0],ap=s.players['1'].ap,f=Draft.create(s,'1',{battleId:b.id,actorId:b.actors[0].id,turnId:b.current.id,action:'item',params:{itemId:item.id,recipientId:b.actors[1].id,recipientCharacterId:target.id}});let rolls=0;const r=Draft.execute(s,f.id,'1','我包扎伤口。',(min,max)=>{rolls++;return max-1;});assert.equal(rolls,1);assert.equal(target.hp,2);assert.equal(target.life.reserveHP,15);assert.equal(b.current.quick,0);assert.equal(s.players['1'].ap,ap);assert.equal(s.players['1'].inventory[item.id],undefined);assert.deepEqual(Draft.execute(s,f.id,'1','',()=>{throw Error('reroll');}),r);});
test('rescue validates same grid cell and no cross-battle or cross-map healing',()=>{const {s,b}=fight(),T=require('../src/rpg/treatment');b.actors[1].x=75;assert.throws(()=>T.battle(s,b,b.actors[0],b.actors[1].id),/同格/);assert.throws(()=>T.outside(s,'1','3'),/跨战斗/);B.endBattle(s,b);s.explorations.map={id:'map',status:'active',participants:{'1':{cell:'0,0',characterId:s.players['1'].id}}};assert.throws(()=>T.outside(s,'1','3'),/同地图/);delete s.explorations.map;assert.equal(T.outside(s,'1','3').id,s.players['3'].id);});
test('all downed party waits for saved hits, then persists hidden GM judgment without clearing AP or assets',()=>{const {s,b}=fight(),ap=s.players['1'].ap;for(const a of b.actors)H.damage(s.players[a.userId],999);b.pending={id:'saved'};assert.ok(R.check(s,b));assert.equal(b.status,'active');assert.equal(b.stopForRescue,true);b.pending=null;assert.ok(R.check(s,b));assert.equal(b.status,'paused');assert.equal(b.judgment.notification.status,'pending');assert.equal(s.players['1'].ap,ap);assert.equal(Object.keys(s.deaths).length,0);const saved=JSON.stringify(b.judgment);assert.equal(R.check(s,b),false);assert.equal(JSON.stringify(b.judgment),saved);});
test('GM rescue event restores selected players but remains paused until explicit resume',()=>{const {s,b}=fight();for(const a of b.actors)H.damage(s.players[a.userId],999);R.check(s,b);const j=b.judgment,result=R.event(s,b,j.id,j.version,[b.actors[0].id],1,'援军赶到。');assert.equal(result[0].after.hp,1);assert.ok(H.downed(s.players['2']));assert.equal(b.status,'paused');B.pause(b,true);assert.equal(b.status,'active');assert.throws(()=>R.event(s,b,j.id,1,[b.actors[0].id],1,'旧消息'),/变化/);});
test('reinforcements only receive new positions and zero AP and stale death preview cannot kill healed party',()=>{const {s,b}=fight();for(const a of b.actors)H.damage(s.players[a.userId],999);R.check(s,b);const j=b.judgment,f=R.deathPreview(s,b,'GM',j.id,j.version,'无法救援'),positions=b.actors.map(a=>[a.x,a.y]);const a=R.addPlayer(s,b,'3');assert.deepEqual(b.actors.slice(0,2).map(a=>[a.x,a.y]),positions);assert.equal(s.players['3'].ap,0);assert.ok(!positions.some(([x,y])=>x===a.x&&y===a.y));assert.throws(()=>R.kill(s,'GM',f.id),/变化/);assert.equal(Object.keys(s.players).length,3);});
test('party death confirmation clears each character and voucher once and marks defeat',()=>{const {s,b}=fight();for(const a of b.actors){s.players[a.userId].couponBalances={v:5};H.damage(s.players[a.userId],999);}R.check(s,b);const j=b.judgment,f=R.deathPreview(s,b,'GM',j.id,j.version,'救援失败'),r=R.kill(s,'GM',f.id);assert.equal(r.names.length,2);assert.equal(Object.keys(s.deaths).length,2);assert.equal(s.players['1'],undefined);assert.equal(b.status,'ended');assert.equal(b.outcome,'defeat');assert.deepEqual(R.kill(s,'GM',f.id),r);assert.equal(Object.keys(s.deaths).length,2);});
test('BOSS assignment is unique, manual, frozen across pool edits and map generation, including high-rank templates',()=>{const {s,m,n}=map(),v=Boss.publish(s,{name:'BOSS',entries:[{ref:n.id,quantity:19}]});m.maxRank=1;const r=Boss.assign(s,m,'2,0',v.id,minRng),frozen=JSON.stringify(r.remainingNpcs);assert.equal(r.remainingNpcs.length,19);assert.equal(r.remainingNpcs[0].template.spawnStrength.level,91);assert.throws(()=>Boss.assign(s,m,'4,0',v.id,minRng),/最多一间/);v.entries[0].quantity=1;n.name='更名';X.generate(s,m,minRng);assert.equal(JSON.stringify(m.cells['2,0'].room.remainingNpcs),frozen);assert.throws(()=>X.editCell(s,m,3,1,'corridor'),/BOSS/);});
test('BOSS waits for whole party and RP, forbids direct encounter, hidden confirmation consumes one batch only',()=>{const {s,m,n}=map(),v=Boss.publish(s,{name:'BOSS',entries:[{ref:n.id,quantity:19}]});Boss.assign(s,m,'2,0',v.id,minRng);const q=arrived(s,m),r=m.cells['2,0'].room;assert.ok(q);assert.equal(r.remainingNpcs.length,19);assert.equal(Object.keys(s.battles).length,0);assert.throws(()=>X.encounter(s,m,'2,0',['1','2'],minRng),/隐藏/);const b=Boss.confirm(s,m.id,'2,0',q.id,q.version,varied);assert.equal(b.actors.length,20);assert.equal(r.remainingNpcs.length,1);assert.equal(Boss.confirm(s,m.id,'2,0',q.id,1,()=>{throw Error('reroll');}).id,b.id);assert.equal(r.remainingNpcs.length,1);assert.equal(Object.keys(s.battles).length,1);});
test('BOSS second wave uses saved layout and requires fresh GM confirmation; defeat cannot unlock resources',()=>{const {s,m,n}=map(),v=Boss.publish(s,{name:'BOSS',entries:[{ref:n.id,quantity:19}]});Boss.assign(s,m,'2,0',v.id,minRng);const q=arrived(s,m),b=Boss.confirm(s,m.id,'2,0',q.id,1,varied),r=m.cells['2,0'].room;B.endBattle(s,b);b.outcome='defeat';assert.throws(()=>X.resolve(s,m,'2,0'),/获胜/);b.outcome='victory';X.resolve(s,m,'2,0');Boss.reconcile(s);const next=r.bossRequest;assert.notEqual(next.id,q.id);const layout=JSON.stringify(r.tacticalLayout),last=Boss.confirm(s,m.id,'2,0',next.id,1,varied);assert.equal(last.actors.length,3);assert.equal(JSON.stringify(r.tacticalLayout),layout);assert.equal(r.remainingNpcs.length,0);});
test('BOSS pending request cancels when roster changes and no monster quota is consumed',()=>{const {s,m,n}=map(),v=Boss.publish(s,{name:'BOSS',entries:[{ref:n.id,quantity:2}]});Boss.assign(s,m,'2,0',v.id,minRng);const q=arrived(s,m);m.participants['2'].cell='1,0';Boss.reconcile(s);assert.equal(q.status,'cancelled');assert.throws(()=>Boss.confirm(s,m.id,'2,0',q.id,1,varied),/变化/);assert.equal(m.cells['2,0'].room.remainingNpcs.length,2);});
test('BOSS RP waiting prevents request and generated manual-only templates are excluded',()=>{const {s,m,n}=map(),v=Boss.publish(s,{name:'BOSS',entries:[{ref:n.id,quantity:1}]});Boss.assign(s,m,'2,0',v.id,minRng);X.publish(s,m);X.join(s,m,'1');m.participants['1'].cell='2,0';m.revealed['2,0']=true;m.rps={rp:{status:'pending'}};m.rpPendingId='rp';Boss.reconcile(s);assert.equal(m.cells['2,0'].room.bossRequest,undefined);m.rps.rp.status='released';Boss.reconcile(s);assert.equal(m.cells['2,0'].room.bossRequest.status,'pending');const excluded=Object.values(s.roomTemplates)[0];excluded.manualOnly=true;assert.throws(()=>X.selectRoom(s,m,{categoryId:m.categoryId},minRng),/房间/);});
test('upgrade 7 preserves AP/current opportunity/pending dice and historical deaths while only adding fields once',()=>{const {s,b}=fight();s.upgrade=6;s.players['2'].hp=0;const before=C.clone(b),ap=s.players['1'].ap;const report=require('../src/rpg/features-upgrade').migrate(s);assert.equal(report.features,7);assert.deepEqual(b,before);assert.equal(s.players['1'].ap,ap);assert.ok(H.downed(s.players['2']));assert.equal(Object.keys(s.deaths).length,0);assert.equal(require('../src/rpg/features-upgrade').migrate(s),null);});
test('50 duplicate redemptions and restart return one durable receipt without repeated reward',async()=>{const seed=state(),v=pool(seed);grant(seed,v,'1',3);const h=runtime(seed),st=createStore(h.deps);await st.load(seed.guildId);const f=await st.transact(seed.guildId,'preview','1',s=>V.preview(s,'1',v.id));let executions=0;await Promise.all(Array.from({length:50},()=>st.transact(seed.guildId,'coupon:'+f.id,'1',s=>{executions++;return V.redeem(s,'1',f.id);})));assert.equal(executions,1);const reload=createStore(h.deps);await reload.load(seed.guildId);const saved=reload.snapshot(seed.guildId);assert.equal(saved.players['1'].couponBalances[v.id],2);assert.equal(Object.keys(saved.couponRedemptions).length,1);assert.equal(saved.forms[f.id].status,'done');assert.equal(Object.keys(saved.players['1'].inventory).length,2);});
test('failed save before reward and uncertain save after reward reconcile one voucher operation',async()=>{for(const mode of ['before','after']){const h=harness(),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);const refs=await st.transact(C.DEFAULT_GUILD_ID,'seed','GM',s=>{Object.assign(s.players,state().players);const v=pool(s);grant(s,v);return{pool:v.id,form:V.preview(s,'1',v.id).id};});h.fail(mode);if(mode==='before')await assert.rejects(st.transact(C.DEFAULT_GUILD_ID,'redeem','1',s=>V.redeem(s,'1',refs.form)));else await st.transact(C.DEFAULT_GUILD_ID,'redeem','1',s=>V.redeem(s,'1',refs.form));const restored=createStore(h.deps);await restored.load(C.DEFAULT_GUILD_ID);assert.equal(Object.keys(restored.snapshot(C.DEFAULT_GUILD_ID).couponRedemptions).length,mode==='after'?1:0);assert.equal(restored.snapshot(C.DEFAULT_GUILD_ID).players['1'].couponBalances[refs.pool],mode==='after'?0:1);}});
test('player/GM slash panels, junk category and full glossary obey permissions and Discord component limits',async()=>{const seed=state(),v=pool(seed);grant(seed,v);G.publish(seed,{name:'长名词',description:'词'.repeat(4000)});const h=runtime(seed),rpg=createRpg(h.deps);await rpg.start();try{for(const name of ['兑换券','收藏柜','名词解释']){const i=h.interaction('1',name);await rpg.handle(i);assert.ok(i.result.embeds);assert.equal(i.deferOptions.flags,64);assert.deepEqual(i.result.allowedMentions,{parse:[]});assert.ok(i.result.components.length<=5);}const forbidden=h.interaction('1','gm',{sub:'兑换券'});await rpg.handle(forbidden);assert.match(forbidden.result.content,/GM/);const gm=h.interaction('GM','gm',{sub:'兑换券'});await rpg.handle(gm);assert.ok(controls(gm.result).some(c=>c.label==='批量发券'));const term=h.interaction('1',null,{},'rpg:features:terms:read',Object.keys(seed.glossaryTerms));await rpg.handle(term);assert.equal(term.result.embeds[0].data.description.length,4000);const form={id:'draft',type:'coupon',version:0,data:{name:'池',description:'',mode:'choice',entries:[]}};const recipe=rpg.features.recipe(rpg.store.snapshot(seed.guildId),form);assert.ok(controls(recipe).find(c=>c.placeholder==='按物品分类筛选').options.some(o=>o.value==='junk'));}finally{rpg.stop();await rpg.drain();}});
test('blocked rendering does not block 20 initial acknowledgments and private text replies',async()=>{const seed=state(),v=pool(seed);grant(seed,v);const shown=M.issue(seed,'1','seed_0_gold')[0];S.select(seed,'1',seed.players['1'].id,0,[shown.id]);const h=runtime(seed),samples={};h.deps.metrics={observe:(k,v)=>(samples[k]||=[]).push(v),start:k=>{const at=performance.now();return()=>h.deps.metrics.observe(k,performance.now()-at);},gauge(){},close(){}};let release;const blocked=new Promise(r=>release=r);h.deps.renderer={decorate:async(_,p)=>{if(p.rpgMap||p.rpgPortraits)await blocked;return p;},close(){}};const rpg=createRpg(h.deps);await rpg.start();try{await Promise.all(Array.from({length:20},()=>rpg.handle(h.interaction('1','收藏柜'))));const p95=k=>samples[k].sort((a,b)=>a-b)[Math.floor((samples[k].length-1)*.95)];assert.ok(p95('interaction.ack')<1000);assert.ok(p95('interaction.result')<3000);}finally{release();rpg.stop();await rpg.drain();}});
test('hidden judgment notification saves intent, uncertain send survives restart, and never falls back to public',async()=>{
 const {s,b}=fight(),h=runtime(s),st=createStore(h.deps);s.config.rpChannelId='hidden';await st.load(s.guildId);await st.transact(s.guildId,'down','GM',s=>{s.config.rpChannelId='hidden';for(const uid of ['1','2'])H.damage(s.players[uid],999);});
 const U=require('../src/rpg/ui');h.ch.id='hidden';h.ch.type=U.D.ChannelType.GuildText;h.deps.client.guilds={fetch:async()=>h.guild};for(const id of [s.guildId,'gm','player'])h.guild.roles.cache.set(id,{id,name:id,permissions:new U.D.PermissionsBitField(0n)});h.ch.permissionsFor=who=>new U.D.PermissionsBitField(['BOT','gm'].includes(who?.id)?U.D.PermissionFlagsBits.Administrator:0n);
 const args=store=>({snapshot:store.snapshot,store,tx:(i,fn)=>store.transact(i.guildId,i.id,i.user.id,fn),client:h.deps.client,needGM:(s,m)=>C.requireThat(U.gm(s,m),'需要GM'),textChannel:async()=>h.ch}),story=require('../src/rpg/gm-story').createStory(args(st)),send=h.ch.send;h.ch.send=async options=>{await send(options);throw Error('uncertain send');};
 await assert.rejects(story.notice(s.guildId,'rescue/'+b.id),/uncertain/);const sent=h.sent.length;assert.equal(st.snapshot(s.guildId).battles[b.id].judgment.notification.status,'uncertain');assert.equal(h.sent.at(-1).lastPayload.allowedMentions.roles[0],'gm');
 const reload=createStore(h.deps);await reload.load(s.guildId);await require('../src/rpg/gm-story').createStory(args(reload)).notice(s.guildId,'rescue/'+b.id);assert.equal(h.sent.length,sent);
 const q=reload.snapshot(s.guildId).battles[b.id].judgment;await reload.transact(s.guildId,'reset-notice','GM',s=>{s.battles[b.id].judgment.notification.status='pending';s.battles[b.id].judgment.notification.attempt=1;});h.ch.permissionsFor=()=>new U.D.PermissionsBitField(0n);await assert.rejects(require('../src/rpg/gm-story').createStory(args(reload)).notice(s.guildId,'rescue/'+b.id),/权限/);assert.equal(h.sent.length,sent);assert.equal(q.id,reload.snapshot(s.guildId).battles[b.id].judgment.id);
});
test('slash ally healing in battle opens the same direct/RP draft with exact target and does not consume before confirmation',async()=>{const {s,b}=fight();H.damage(s.players['2'],999);const med=M.publishTemplate(s,{...F.defaults('item','药品'),name:'急救针',heal:'1d6',weightKg:0}),item=M.issue(s,'1',med.id)[0],h=runtime(s),rpg=createRpg(h.deps);await rpg.start();try{const i=h.interaction('1','使用',{物品:item.id,目标:'2'});await rpg.handle(i);assert.ok(controls(i.result).some(c=>c.label==='RP 并行动'));assert.match(i.result.embeds[0].data.description,/急救针 → 角色2/);assert.ok(rpg.store.snapshot(s.guildId).players['1'].inventory[item.id]);assert.equal(rpg.store.snapshot(s.guildId).battles[b.id].current.quick,1);}finally{rpg.stop();await rpg.drain();}});
test('GM native pool modal, junk category, preview and publication feed player redemption without granting junk elsewhere',async()=>{const seed=state(),h=runtime(seed),rpg=createRpg(h.deps);await rpg.start();try{const gm=h.interaction('GM','gm',{sub:'兑换券'});await rpg.handle(gm);const open=h.interaction('GM',null,{},button(gm.result,'新建池'));await rpg.handle(open);assert.ok(open.modal);const i=h.interaction('GM',null,{},open.modal.toJSON().custom_id,[],{name:'古物券',description:'GM定制'});await rpg.handle(i);let v=i.result;const cat=controls(v).find(c=>c.placeholder==='按物品分类筛选');const choose=h.interaction('GM',null,{},cat.custom_id,['junk']);await rpg.handle(choose);v=choose.result;const list=controls(v).find(c=>c.placeholder==='选择模板加入或修改数量');assert.ok(list.options.every(o=>seed.catalog[o.value].kind==='杂物'));const add=h.interaction('GM',null,{},list.custom_id,[list.options[0].value]);await rpg.handle(add);const preview=h.interaction('GM',null,{},button(add.result,'预览发布'));await rpg.handle(preview);const publish=h.interaction('GM',null,{},button(preview.result,'确认发布'));await rpg.handle(publish);assert.equal(Object.values(rpg.store.snapshot(seed.guildId).couponPools)[0].name,'古物券');assert.match(publish.result.embeds[0].data.title,/已发布/);}finally{rpg.stop();await rpg.drain();}});
test('keyword pagination retains query, rescue cards show selected double bars without inventing damage or player RP',async()=>{const seed=state();for(let n=0;n<23;n++)G.publish(seed,{name:'污染'+n,description:'解释'});G.publish(seed,{name:'其他',description:'另一条'});const h=runtime(seed),rpg=createRpg(h.deps);await rpg.start();try{const i=h.interaction('1','名词解释',{关键词:'污染'});await rpg.handle(i);const next=h.interaction('1',null,{},button(i.result,'下一页'));await rpg.handle(next);const list=controls(next.result).find(c=>c.placeholder==='选择名词');assert.equal(list.options.length,3);assert.ok(list.options.every(o=>o.label.startsWith('污染')));}finally{rpg.stop();await rpg.drain();}const {s,b}=fight();for(const uid of ['1','2'])H.damage(s.players[uid],999);R.check(s,b);R.event(s,b,b.judgment.id,1,b.actors.map(a=>a.id),1,'医疗组进行急救。');const e=b.publicEvents.find(e=>e.type==='rescue'),v=require('../src/rpg/battle-events').view(b,e,1);assert.match(v.embeds[0].data.description,/获救角色：角色2/);assert.match(v.embeds[0].data.description,/正常HP 0→1 · 倒地HP 15→15/);assert.doesNotMatch(v.embeds[0].data.description,/undefined|伤害 NaN/);assert.deepEqual(e.rpEntries,[]);});
