'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/rpg/constants'),M=require('../src/rpg/model'),B=require('../src/rpg/combat');
const BE=require('../src/rpg/battle-events'),{createStore}=require('../src/rpg/store'),{createRpg}=require('../src/rpg');
const {createOutbox}=require('../src/rpg/outbox'),{harness,state,fight,weapon,minRng}=require('./helpers/rpg-harness');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){const deadline=Date.now()+5000;while(!fn()){assert.ok(Date.now()<deadline,'timed out');await pause(10);}}
function prepared(){const s=state();require('../src/rpg/content-pack').install(s);require('../src/rpg/ammunition').migrate(s);require('../src/rpg/skills').migrate(s);s.config.gmRoleIds=['gm'];s.config.playerRoleIds=['player'];return s;}
function database(s=prepared(),delay=0){let saved=C.clone(s),fail=null,saves=0;return {
  assertLease(){},load:async()=>C.clone(saved),importState:async(_,next)=>{assert.equal(saved,null);saved=C.clone(next);},
  save:async(_,before,next)=>{await pause(delay);assert.equal(saved.revision,before.revision);saves++;if(fail==='before'){fail=null;throw Error('simulated disconnect');}saved=C.clone(next);if(fail==='after'){fail=null;throw Error('simulated disconnect');}},
  fail:mode=>{fail=mode;},get saves(){return saves;},get state(){return C.clone(saved);}
};}
function runtime(delay=0){const h=harness(),db=database(prepared(),delay);h.deps.database=db;h.deps.backgroundPublications=true;return {...h,db};}

test('RPG construction works before Discord login populates client.user',()=>{const h=runtime();h.deps.client.user=null;const rpg=createRpg(h.deps);assert.equal(rpg.store.clientId,undefined);h.deps.client.user={id:'BOT'};assert.equal(rpg.store.clientId,'BOT');rpg.stop();});

test('database transactions conserve concurrent assets and duplicate interaction receipts',async()=>{const h=runtime(5),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);let calls=0;
 await Promise.all(Array.from({length:20},(_,n)=>st.transact(C.DEFAULT_GUILD_ID,'credit-'+n,'1',s=>{s.players['1'].balance++;return s.players['1'].balance;})));
 await Promise.all(Array.from({length:20},()=>st.transact(C.DEFAULT_GUILD_ID,'one-operation','1',s=>{calls++;s.players['1'].balance++;return {balance:s.players['1'].balance};})));
 assert.equal(st.snapshot(C.DEFAULT_GUILD_ID).players['1'].balance,21);assert.equal(calls,1);assert.equal(h.db.state.players['1'].balance,21);
 const selected=st.select(C.DEFAULT_GUILD_ID,s=>s.players['1']);selected.balance=999;assert.equal(st.select(C.DEFAULT_GUILD_ID,s=>s.players['1'].balance),21);
});
test('database COMMIT ambiguity reconciles a committed receipt and never falls back to Discord',async()=>{const h=runtime(),st=createStore(h.deps);let downloads=0;h.deps.fetcher=async()=>{downloads++;throw Error('must not read old Discord backup');};await st.load(C.DEFAULT_GUILD_ID);
 h.db.fail('after');const value=await st.transact(C.DEFAULT_GUILD_ID,'after','1',s=>{s.players['1'].balance++;return 1;});assert.equal(value,1);assert.equal(st.frozen(C.DEFAULT_GUILD_ID),false);
 h.db.fail('before');await assert.rejects(st.transact(C.DEFAULT_GUILD_ID,'before','1',s=>{s.players['1'].balance++;return 2;}),/暂停/);assert.equal(st.frozen(C.DEFAULT_GUILD_ID),true);assert.equal(st.select(C.DEFAULT_GUILD_ID,s=>s.players['1'].balance),1);
 await st.recover(C.DEFAULT_GUILD_ID);assert.equal(st.frozen(C.DEFAULT_GUILD_ID),false);assert.equal(downloads,0);
});
test('missing database requires an explicit first import instead of silently loading old assets',async()=>{const h=runtime();h.deps.database.load=async()=>null;const st=createStore(h.deps);await assert.rejects(st.load(C.DEFAULT_GUILD_ID),/RPG_IMPORT_DISCORD_ONCE/);});
test('outbox is durable, coalesces in-flight refreshes and does not swallow later changes',async()=>{const h=runtime(),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);const ref=await st.transact(C.DEFAULT_GUILD_ID,'battle','GM',s=>B.createBattle(s,'channel','GM','first').id);
 let release;const gate=new Promise(r=>{release=r;}),seen=[];
 const worker=createOutbox({store:st,client:h.deps.client,logFailure:()=>{},handlers:{battle:async(g,r)=>{seen.push(st.select(g,s=>s.battles[r].name));if(seen.length===1)await gate;}}});worker.start();
 try{await until(()=>seen.length===1);await st.transact(C.DEFAULT_GUILD_ID,'change-a','GM',s=>{s.battles[ref].name='middle';});await st.transact(C.DEFAULT_GUILD_ID,'change-b','GM',s=>{s.battles[ref].name='latest';});release();await until(()=>seen.length===2&&st.select(C.DEFAULT_GUILD_ID,s=>s.deliveryJobs['battle:'+ref].status)==='done');assert.deepEqual(seen,['first','latest']);const restored=createStore(h.deps);await restored.load(C.DEFAULT_GUILD_ID);assert.equal(restored.select(C.DEFAULT_GUILD_ID,s=>s.deliveryJobs['battle:'+ref].status),'done');}finally{worker.stop();release();await worker.drain();}
});
test('each NPC edits one card across turns while player moves keep the original merge rule',async()=>{const h=runtime(),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);
 const ref=await st.transact(C.DEFAULT_GUILD_ID,'npc','GM',s=>{const b=B.createBattle(s,'channel','GM','cards');const p=M.newCharacter('NPC',{strength:3,constitution:3,mind:3,appearance:3,intelligence:3,agility:3,knowledge:3},1);b.actors.push({id:'npc',name:'NPC',team:'enemy',character:p});b.current={id:'turn-1',actorId:'npc',quick:1,formal:1,move:9};B.record(b,'NPC移动至(26,25)。',{actorId:'npc',remaining:8});return b.id;});
 const events=BE.createEvents({snapshot:st.snapshot,store:st,client:h.deps.client,textChannel:async()=>h.ch,render:async(_,v)=>{delete v.rpgMap;return v;},logFailure:()=>{}});
 await events.publish(C.DEFAULT_GUILD_ID,ref);const first=st.select(C.DEFAULT_GUILD_ID,s=>s.battles[ref].npcCards.npc.publication.messageId),sends=h.sent.length;
 await st.transact(C.DEFAULT_GUILD_ID,'next','GM',s=>{const b=s.battles[ref];b.current.id='turn-2';B.record(b,'NPC移动至(27,25)。',{actorId:'npc',remaining:7});});await events.publish(C.DEFAULT_GUILD_ID,ref);
 assert.equal(st.select(C.DEFAULT_GUILD_ID,s=>s.battles[ref].npcCards.npc.publication.messageId),first);assert.equal(h.sent.length,sends);assert.equal(st.select(C.DEFAULT_GUILD_ID,s=>s.battles[ref].publicEvents.length),2);
 const {s,b}=fight();B.move(s,b,b.current.id,26,25);B.move(s,b,b.current.id,27,25);assert.equal(b.publicEvents.filter(e=>e.type==='move').length,1);
});
test('NPC duplicate cleanup deletes only verified active NPC cards and preserves player history',async()=>{const h=runtime(),st=createStore(h.deps);h.ch.id='channel';await st.load(C.DEFAULT_GUILD_ID);const first=await h.ch.send({content:'NPC old'}),last=await h.ch.send({content:'NPC current'}),player=await h.ch.send({content:'player record'});let deleted=[];for(const m of [first,last,player])m.delete=async()=>{deleted.push(m.id);h.messages.delete(m.id);};
 const ref=await st.transact(C.DEFAULT_GUILD_ID,'old-cards','GM',s=>{const b=B.createBattle(s,'channel','GM','old cards');b.actors=[{id:'npc',name:'NPC',team:'enemy',character:M.newCharacter('NPC',{strength:2,constitution:2,mind:2,appearance:2,intelligence:2,agility:2,knowledge:2},1)},{id:'player',userId:'1',name:'Player',team:'ally',characterId:s.players['1'].id}];b.publicEvents=[{id:'old',actorId:'npc',message:'移动',type:'move',details:{},version:1,publication:{status:'sent',messageId:first.id,version:1}},{id:'new',actorId:'npc',actorName:'NPC',message:'移动',type:'move',details:{},version:1,publication:{status:'sent',messageId:last.id,version:1}},{id:'player-event',actorId:'player',type:'move',details:{},version:1,publication:{status:'sent',messageId:player.id,version:1}}];return b.id;});
 const events=BE.createEvents({snapshot:st.snapshot,store:st,client:h.deps.client,textChannel:async()=>h.ch,render:async(_,v)=>{delete v.rpgMap;return v;},logFailure:()=>{}});await events.publish(C.DEFAULT_GUILD_ID,ref);assert.deepEqual(deleted,[first.id]);assert.ok(h.messages.has(last.id)&&h.messages.has(player.id));assert.equal(st.select(C.DEFAULT_GUILD_ID,s=>s.battles[ref].publicEvents.length),3);
});
test('NPC legality checks are read-only and share attack validation with real execution',()=>{const {s,b}=fight(),a=B.actorById(b,b.current.actorId),p=B.actorCharacter(s,a),target=b.actors.find(x=>x.id!==a.id),op={type:'attack',ability:p.equipped.weapon,target:target.id,group:'formal',firing:{mode:'semi'}};a.x=target.x;a.y=target.y;const before=JSON.stringify(s);B.validateOperation(s,b,op);assert.equal(JSON.stringify(s),before);B.attack(s,b,b.current.id,op.ability,op.target,op.group,minRng);assert.equal(b.current.formal,0);});
test('slow rendering cannot delay text controls or replace a newer private panel',async()=>{const h=runtime();let release;const gate=new Promise(r=>{release=r;});h.deps.renderer={decorate:async(_,v)=>{if(v.rpgMap)await gate;return {...v,content:'old-image',rpgMap:undefined};},close:()=>release()};
 const rpg=createRpg(h.deps);await rpg.start();const ref=await rpg.store.transact(C.DEFAULT_GUILD_ID,'fight','GM',s=>{const b=B.createBattle(s,'channel','GM','private');B.join(s,b,'1');B.join(s,b,'2');B.start(s,b,null,minRng);return b.id;});
 try{const opened=h.interaction('1',null,{},'rpg:battle:'+ref);await Promise.race([rpg.handle(opened),pause(1000).then(()=>{throw Error('text reply waited for image');})]);assert.equal(opened.edits.length,1);const rows=opened.result.components.flatMap(r=>r.toJSON().components),id=rows.find(x=>x.label==='开始行动／个人面板').custom_id;const next=h.interaction('1',null,{},id);next.message={flags:{has:()=>true}};await rpg.handle(next);release();await pause(80);assert.equal(opened.edits.length,1,'old image must not overwrite newer navigation');assert.match(next.result.embeds[0].data.title,/个人行动/);}finally{release();rpg.stop();await rpg.drain();}
});
test('20 simultaneous clicks acknowledge promptly and 50 queued writes retain every asset',async()=>{const h=runtime(35),samples={},metrics={observe:(k,v)=>(samples[k]||=[]).push(v),start:k=>{const t=performance.now();return()=>metrics.observe(k,performance.now()-t);},gauge(){},close(){}};h.deps.metrics=metrics;const rpg=createRpg(h.deps);await rpg.start();
 try{await Promise.all(Array.from({length:20},()=>rpg.handle(h.interaction('1','rd',{'骰式':'1d20'}))));const p95=a=>[...a].sort((x,y)=>x-y)[Math.floor((a.length-1)*.95)];assert.ok(p95(samples['interaction.ack'])<1000);assert.ok(p95(samples['interaction.result'])<3000);
 await Promise.all(Array.from({length:50},(_,n)=>rpg.store.transact(C.DEFAULT_GUILD_ID,'burst-'+n,'1',s=>{s.players['1'].balance++;})));assert.equal(rpg.store.select(C.DEFAULT_GUILD_ID,s=>s.players['1'].balance),50);console.log(JSON.stringify({test:'synthetic-concurrency',clicks:20,ackP95Ms:Math.round(p95(samples['interaction.ack'])),resultP95Ms:Math.round(p95(samples['interaction.result'])),burstWrites:50}));}finally{rpg.stop();await rpg.drain();}
});
test('independent latest/daily/weekly backups keep the migration archive and deduplicate overlapping timers',async()=>{const h=runtime(),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);const original=await h.ch.send({content:'discord-api-bot-rpg-v1:'+C.DEFAULT_GUILD_ID,files:[{name:'rpg-'+C.DEFAULT_GUILD_ID+'.json.enc',attachment:st.pack(st.snapshot(C.DEFAULT_GUILD_ID))}]});const originalBody=original.lastPayload.files[0].attachment;
 await Promise.all(Array.from({length:10},()=>st.backup(C.DEFAULT_GUILD_ID)));assert.equal(h.sent.length,4);assert.equal(original.content,'discord-api-bot-rpg-v1:'+C.DEFAULT_GUILD_ID);assert.ok(originalBody.equals(original.lastPayload.files[0].attachment));
 const copies=h.sent.slice(1);assert.ok(copies.some(m=>m.content.includes(':daily:'))&&copies.some(m=>m.content.includes(':weekly:')));await st.backup(C.DEFAULT_GUILD_ID);assert.equal(h.sent.length,4);
 await st.transact(C.DEFAULT_GUILD_ID,'backup-credit','1',s=>{s.players['1'].balance++;});await st.backup(C.DEFAULT_GUILD_ID);assert.equal(h.sent.length,4);const latest=h.messages.get(h.settings[C.DEFAULT_GUILD_ID].rpgDatabaseBackupMessageId),raw=h.decrypt(JSON.parse(latest.lastPayload.files[0].attachment)).value,data=JSON.parse(require('node:zlib').gunzipSync(Buffer.from(raw.body,'base64')));assert.equal(data.players['1'].balance,1);assert.equal(data.receipts['backup-credit'].result,null);
});
test('late single/automatic/AOE settlement cannot replace a newer NPC action slot',()=>{const b={actors:[{id:'npc',name:'NPC'}],status:'active',publicEvents:[{id:'old',type:'attack',actorId:'npc',version:1,details:{groupId:'old-group',children:[{id:'hit'}]},publication:{status:'sent'}},{id:'new',type:'attack',actorId:'npc',version:2,details:{groupId:'new-group'},publication:{status:'sent'}}],npcCards:{npc:{actorId:'npc',eventId:'new',version:9,publication:{status:'sent'}}}};
 BE.settle(b,{id:'hit',groupId:'old-group',targetId:'target',result:{total:7,hp:4}});assert.equal(b.npcCards.npc.version,9);assert.equal(b.publicEvents[0].details.results[0].targetId,'target');assert.equal(b.publicEvents[1].details.results,undefined);
});
test('two persistent render workers deduplicate identical SVGs, bound the queue and recover from rendering failure',async()=>{const renderer=require('../src/rpg/map-image').createRenderer({portraits:{load:async()=>null},logFailure:()=>{}}),svg=n=>'<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120"><rect width="120" height="120" fill="rgb('+n+',0,0)"/></svg>';
 try{const first=renderer.queue(svg(1));assert.equal(renderer.queue(svg(1)),first);await Promise.all([first,renderer.queue(svg(2))]);const workers=renderer.workers.map(s=>s.worker);assert.equal(workers.length,2);assert.ok(workers.every(Boolean));await renderer.queue(svg(3));assert.deepEqual(renderer.workers.map(s=>s.worker),workers);
  const burst=await Promise.allSettled(Array.from({length:22},(_,n)=>renderer.queue(svg(n+10))));assert.ok(burst.some(r=>r.status==='rejected'));await assert.rejects(renderer.queue('<svg broken>'));assert.ok((await renderer.queue(svg(100))).length>0);
 }finally{renderer.close();}await assert.rejects(renderer.queue(svg(101)),/停止/);
});
test('defense notifications use a reserved lane while every ordinary publisher waits on network',async()=>{const h=runtime(),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);await st.transact(C.DEFAULT_GUILD_ID,'ordinary','GM',s=>{for(let n=0;n<3;n++)require('../src/rpg/outbox').put(s,'map',String(n));},'queued',{delivery:false});let release;const gate=new Promise(r=>{release=r;}),started=[],notices=[];const worker=createOutbox({store:st,client:h.deps.client,logFailure:()=>{},handlers:{map:async(_,r)=>{started.push(r);await gate;},defense:async()=>{notices.push('delivered');}}});worker.start();
 try{await until(()=>started.length===3);await st.transact(C.DEFAULT_GUILD_ID,'priority','GM',s=>require('../src/rpg/outbox').put(s,'defense','battle',{priority:0}),'queued',{delivery:false});await until(()=>notices.length===1&&worker.active.size===3);assert.equal(started.length,3);assert.equal(worker.active.size,3);}finally{release();worker.stop();await worker.drain();}
});
test('restart resumes a running task without repeating an uncertain NPC message',async()=>{const h=runtime(),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);const ref=await st.transact(C.DEFAULT_GUILD_ID,'uncertain-npc','GM',s=>{const b=B.createBattle(s,'channel','GM','restart');b.actors=[{id:'npc',name:'NPC',character:M.newCharacter('NPC',{strength:1,constitution:1,mind:1,appearance:1,intelligence:1,agility:1,knowledge:1},1)}];b.publicEvents=[{id:'e',actorId:'npc',actorName:'NPC',type:'move',message:'移动',version:1,details:{},publication:{status:'sending'}}];return b.id;});await st.transact(C.DEFAULT_GUILD_ID,'crashed-task','GM',s=>{s.deliveryJobs['battle:'+ref].status='running';},'crashed',{delivery:false});
 const resumed=createStore(h.deps);await resumed.load(C.DEFAULT_GUILD_ID);const events=BE.createEvents({snapshot:resumed.snapshot,store:resumed,client:h.deps.client,textChannel:async()=>h.ch,render:async(_,v)=>v,logFailure:()=>{}}),worker=createOutbox({store:resumed,client:h.deps.client,logFailure:()=>{},handlers:{battle:(g,r)=>events.publish(g,r)}});worker.start();try{await until(()=>resumed.select(C.DEFAULT_GUILD_ID,s=>s.deliveryJobs['battle:'+ref].status)==='done');assert.equal(h.sent.length,0);assert.equal(resumed.select(C.DEFAULT_GUILD_ID,s=>s.battles[ref].npcCards.npc.publication.status),'uncertain');}finally{worker.stop();await worker.drain();}
});
test('battle recovery binds only a verified Bot card and rejects an outdated resend',async()=>{const h=runtime(),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);const ref=await st.transact(C.DEFAULT_GUILD_ID,'lost-board','GM',s=>{const b=B.createBattle(s,'storage','GM','recover');b.boardPublication={status:'uncertain'};return b.id;});const ctl=require('../src/rpg/board-recovery').createBoardRecovery({snapshot:st.snapshot,store:st,tx:(i,f)=>st.transact(i.guildId,i.id,i.user.id,f),needGM:(s,m)=>assert.ok(require('../src/rpg/ui').gm(s,m)),textChannel:async()=>h.ch,busy:()=>false});
 const message=await h.ch.send({content:'board'});message.id='123456789012345678';h.messages.set(message.id,message);message.channelId='storage';message.embeds=[{footer:{text:'战斗 '+ref+' · 招募中'}}];const bind=h.interaction('GM',null,{},'rpg:boardrepair:'+ref+':bindsubmit');bind.fields={getTextInputValue:()=>message.id};message.author={id:'HUMAN'};await assert.rejects(ctl.component(bind,h.members.GM),/不是/);message.author={id:h.deps.client.user.id};await ctl.component(bind,h.members.GM);assert.equal(st.select(C.DEFAULT_GUILD_ID,s=>s.battles[ref].messageId),message.id);await assert.rejects(ctl.component(h.interaction('GM',null,{},'rpg:boardrepair:'+ref+':retry'),h.members.GM),/恢复|变化/);
});
test('current Discord interaction roles avoid redundant REST lookup and still reject revoked GM roles',async()=>{const h=runtime();let fetched=0;const fetchMember=h.guild.members.fetch;h.guild.members.fetch=async(...a)=>{fetched++;return fetchMember(...a);};for(const m of Object.values(h.members))m.guild=h.guild;const rpg=createRpg(h.deps);await rpg.start();try{await rpg.handle(h.interaction('1','rd',{'骰式':'1d20'}));assert.equal(fetched,0);h.members.GM.roles.cache.clear();const denied=h.interaction('GM','战斗',{sub:'招募',名称:'denied'});await rpg.handle(denied);assert.match(denied.result.content,/GM/);assert.equal(fetched,0);assert.equal(rpg.store.select(C.DEFAULT_GUILD_ID,s=>Object.keys(s.battles).length),0);}finally{rpg.stop();await rpg.drain();}});
test('already ended legacy NPC cards retain their original messages without migration edits or cleanup',async()=>{const h=runtime(),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);const cards=await Promise.all(['history one','history two'].map(content=>h.ch.send({content}))),ref=await st.transact(C.DEFAULT_GUILD_ID,'ended-history','GM',s=>{const b=B.createBattle(s,'storage','GM','ended');b.status='ended';b.actors=[{id:'npc',name:'NPC',character:M.newCharacter('NPC',{strength:1,constitution:1,mind:1,appearance:1,intelligence:1,agility:1,knowledge:1},1)}];b.publicEvents=cards.map((m,n)=>({id:'event-'+n,actorId:'npc',type:'move',message:m.content,version:1,details:{},publication:{status:'sent',version:1,messageId:m.id}}));return b.id;});const events=BE.createEvents({snapshot:st.snapshot,store:st,client:h.deps.client,textChannel:async()=>h.ch,render:async(_,v)=>{throw Error('ended card must not render');},logFailure:()=>{}});await events.publish(C.DEFAULT_GUILD_ID,ref);assert.deepEqual(cards.map(m=>m.content),['history one','history two']);assert.equal(h.sent.length,2);assert.equal(st.select(C.DEFAULT_GUILD_ID,s=>s.battles[ref].npcCardMigrationVersion),undefined);});
