'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),crypto=require('node:crypto');
const C=require('../src/rpg/constants'),M=require('../src/rpg/model'),F=require('../src/rpg/forms'),G=require('../src/rpg/gm-service'),U=require('../src/rpg/ui');
const {createStore}=require('../src/rpg/store'),{createGmWeb}=require('../src/rpg/gm-web');
const gm='123456789012345678';
const {seed,harness}=require('./helpers/gm-web-fixture.cjs');
test('upgrade 9 initializes only web devices and is idempotent, preserving assets and active deadlines',()=>{const s=seed();s.upgrade=8;s.forms.f={expiresAt:Date.now()+1234};const before=C.clone(s);assert.deepEqual(require('../src/rpg/gm-web-upgrade').migrate(s),{gmWeb:9});assert.deepEqual(s.players,before.players);assert.deepEqual(s.forms,before.forms);assert.equal(require('../src/rpg/gm-web-upgrade').migrate(s),null);assert.ok(require('../src/rpg/postgres').COLLECTIONS.has('gmWebDevices'));});
test('template batch validates each row, rejects stale publishing and keeps legacy entered text',()=>{const s=seed(),rows=[{kind:'trait',data:{name:'合法',description:'',effects:[]},baseVersion:0},{kind:'trait',data:{name:'',effects:[]},baseVersion:0}];const check=G.validateBatch(s,rows,gm);assert.equal(check[0].success,true);assert.equal(check[1].success,false);assert.equal(Object.values(s.traits).length,1);const t=G.publishBatch(s,[rows[0]],gm)[0],first=F.create(s,gm,'trait',null,t.id),second=F.create(s,gm,'trait',null,t.id);first.data.name='新名称';F.publish(s,first);second.data.name='保留填写';assert.throws(()=>F.publish(s,second),/修改/);assert.equal(second.data.name,'保留填写');delete second.baseTemplateVersion;assert.throws(()=>F.publish(s,second),/旧修改草稿/);});
test('binding is private, one-use and device-bound; reads and revocation always enforce current GM',async t=>{const h=await harness(t);assert.equal((await h.call('/session')).status,401);const b=await h.bind();assert.equal((await h.call('/session')).data.userId,gm);assert.equal((await h.call('/pair',{...b.p,deviceId:crypto.randomUUID()},false)).status,422);const devices=await h.call('/devices');assert.ok(devices.data.every(d=>!d.credentialHash));h.setRole(false);assert.equal((await h.call('/session')).status,403);h.setRole(true);await h.call('/devices/revoke',{id:b.deviceId});assert.equal((await h.call('/session')).status,401);});
test('batch grants preserve recipient atomicity and exclude junk without cancelling other recipients',()=>{const s=seed(),heavy=M.publishTemplate(s,{...F.defaults('item','药品'),name:'超重药品',weightKg:1000,heal:'1',rarity:'white'}),light=M.publishTemplate(s,{...F.defaults('item','药品'),name:'轻药',weightKg:0,heal:'1',rarity:'white'}),rows=[{uid:'1',characterId:s.players['1'].id,type:'item',ref:light.id,quantity:1},{uid:'1',characterId:s.players['1'].id,type:'item',ref:heavy.id,quantity:1},{uid:'2',characterId:s.players['2'].id,type:'item',ref:light.id,quantity:2}];const result=G.grantBatch(s,rows);assert.equal(result[0].success,false);assert.equal(Object.keys(s.players['1'].inventory).length,0);assert.equal(result[1].success,true);assert.equal(Object.values(s.players['2'].inventory)[0].quantity,2);const junk=Object.values(s.catalog).find(t=>t.kind==='杂物');assert.throws(()=>G.grantOne(s,'1','item',junk.id,1),/杂物/);});
test('HTTP duplicate burst executes once and survives receipt expiry/restart and reply loss',async t=>{const h=await harness(t);await h.bind();const p=h.store.select(C.DEFAULT_GUILD_ID,s=>s.players['1']),f=(await h.call('/previews',{command:'grant',params:{rows:[{uid:'1',characterId:p.id,type:'points',quantity:3}]}})).data;assert.ok(f?.id);h.failAfterCommit();const replies=await Promise.all(Array.from({length:50},()=>h.call('/commands',{draftId:f.id})));assert.ok(replies.every(r=>[200,202].includes(r.status)));assert.equal(h.store.select(C.DEFAULT_GUILD_ID,s=>s.players['1'].points),5);const op=await h.call('/operations/gm-web:'+f.id);assert.equal(op.data.status,'committed');await h.store.transact(C.DEFAULT_GUILD_ID,'expire-receipt',gm,s=>{delete s.receipts['gm-web:'+f.id];});await h.store.recover(C.DEFAULT_GUILD_ID);assert.equal((await h.call('/commands',{draftId:f.id})).data.status,'committed');assert.equal(h.store.select(C.DEFAULT_GUILD_ID,s=>s.players['1'].points),5);});
test('concurrent state or permission change keeps a draft unexecuted and input recoverable',async t=>{const h=await harness(t);await h.bind();const p=h.store.select(C.DEFAULT_GUILD_ID,s=>s.players['1']),draft=(await h.call('/previews',{command:'grant',params:{rows:[{uid:'1',characterId:p.id,type:'points',quantity:3}]}})).data;await h.store.transact(C.DEFAULT_GUILD_ID,'another-gm',gm,s=>{s.players['1'].points++;});assert.equal((await h.call('/commands',{draftId:draft.id})).status,409);assert.equal((await h.call('/operations/gm-web:'+draft.id)).data.status,'uncommitted');h.setConfig(false);assert.equal((await h.call('/previews',{command:'config.save',params:{data:{gmRoleIds:[]}}})).status,403);});
test('frozen store permits safe reads and authority recovery, not a duplicate write',async t=>{const h=await harness(t);await h.bind();h.store.freeze(C.DEFAULT_GUILD_ID);assert.equal((await h.call('/session')).data.frozen,true);assert.equal((await h.call('/collections/players')).status,200);assert.equal((await h.call('/previews',{command:'grant',params:{rows:[]}})).status,503);assert.equal((await h.call('/recover',{})).status,200);assert.equal(h.store.frozen(C.DEFAULT_GUILD_ID),false);});
test('20 HTTP operations finish independently of blocked publications and expose saved metadata only',async t=>{const h=await harness(t);await h.bind();const never=new Promise(()=>{});h.store.onCommit(()=>never);const drafts=[];for(let n=1;n<=20;n++){const uid=String(n),p=h.store.select(C.DEFAULT_GUILD_ID,s=>s.players[uid]);drafts.push((await h.call('/previews',{command:'grant',params:{rows:[{uid,characterId:p.id,type:'points',quantity:1}]}})).data);}const times=[];const results=await Promise.all(drafts.map(async f=>{const start=performance.now(),r=await h.call('/commands',{draftId:f.id});times.push(performance.now()-start);return r;}));assert.ok(results.every(r=>r.status===200));assert.ok(h.store.select(C.DEFAULT_GUILD_ID,s=>Object.values(s.players).every(p=>p.points===3)));times.sort((a,b)=>a-b);console.log(JSON.stringify({test:'gm-web-http-20-mock-discord',resultP95Ms:Math.ceil(times[18])}));assert.ok(times[18]<3000);const schemas=await h.call('/schemas');assert.equal(schemas.status,200);assert.ok(schemas.data.commands.some(c=>c.id==='battle.partyDeath'));assert.ok(!(await h.call('/collections/forms')).data.items.some(f=>f.kind==='gmWebBind'));});


test('web uses zero-based map clicks consistently, pauses skill changes and previews death without altering life',()=>{const s=seed(),X=require('../src/rpg/exploration'),cf=F.create(s,gm,'mapcategory');cf.data.name='隔离类别';const cat=F.publish(s,cf),m=X.create(s,gm,'channel','坐标验收',2,3,'random',cat.id);G.apply(s,gm,'map.cell',{mapId:m.id,x:2,y:1,type:'corridor',passable:true});assert.equal(m.cells['2,1'].type,'corridor');assert.equal(m.width,3);const B=require('../src/rpg/combat'),b=B.createBattle(s,'webbattle',gm,'隔离战斗');B.join(s,b,'1');const f=F.create(s,gm,'skill');f.data.name='隔离技能';const skill=F.publish(s,f);b.status='active';assert.throws(()=>G.grantOne(s,'1','skill',skill.id,1),/暂停/);b.status='paused';const before=C.clone(s.players['1']);const result=require('../src/rpg/gm-web-preview').preview(s,gm,'battle.death',{battleId:b.id,actorId:b.actors[0].id,reason:'隔离验收'});assert.equal(result.affected[0].name,b.actors[0].name);assert.deepEqual(s.players['1'],before);});
test('duplicate import IDs and NPC skills cannot silently overwrite a newer template',()=>{const s=seed(),t=G.publishBatch(s,[{kind:'trait',baseVersion:0,data:{name:'基线',effects:[]}}],gm)[0],row={kind:'trait',id:t.id,baseVersion:t.version,data:{name:'修改',effects:[]}},rows=G.validateBatch(s,[row,row],gm);assert.equal(rows[0].success,true);assert.equal(rows[1].success,false);assert.match(rows[1].reason,/重复/);});
test('GM permission is checked again after a queued preview, not just before joining the queue',async t=>{const h=await harness(t);await h.bind();let release,entered;const ready=new Promise(r=>entered=r),hold=h.store.transact(C.DEFAULT_GUILD_ID,'hold','test',async()=>{entered();await new Promise(r=>release=r);});await ready;const request=h.call('/previews',{command:'grant',params:{rows:[{uid:'1',characterId:h.canonical().players['1'].id,type:'points',quantity:1}]}});await new Promise(r=>setTimeout(r,20));h.setRole(false);release();await hold;assert.equal((await request).status,403);assert.equal(h.store.select(C.DEFAULT_GUILD_ID,s=>s.players['1'].points),2);});
test('publication repair rejects same-title foreign objects and rechecks the saved delivery state',async()=>{const s=seed(),B=require('../src/rpg/combat'),b=B.createBattle(s,'channel',gm,'同名战斗');let message={id:'123456789012345679',channelId:'channel',author:{id:'bot'},embeds:[{title:'同名战斗',footer:{text:'战斗 wrong-id'}}],components:[]};const ctx=require('../src/rpg/gm-web-context').createContext({store:{snapshot:()=>s},client:{user:{id:'bot'}},outbox:{active:new Set()},textChannel:async()=>({id:'channel',messages:{fetch:async()=>message}})}),a={g:s.guildId},p={kind:'battle',ref:b.id,messageId:message.id};await assert.rejects(ctx.checkPublication(a,p),/属于Bot/);message.embeds[0].footer.text='战斗 '+b.id+' · active';await ctx.checkPublication(a,p);b.boardPublication={status:'uncertain'};assert.throws(()=>ctx.repairPublication(s,a,p),/变化/);await ctx.checkPublication(a,p);const r=ctx.repairPublication(s,a,p);assert.equal(r.status,'queued');assert.equal(b.messageId,message.id);});
test('shipped template import examples use valid targets and versions',()=>{const rows=JSON.parse(require('node:fs').readFileSync(require('node:path').join(__dirname,'../gm-web/samples/模板-新建.json'),'utf8')),s=seed();assert.ok(G.validateBatch(s,rows,gm).every(r=>r.success));});

test('duplicate grant rows obey existing per-project caps and Discord ticket result remains compatible',()=>{const s=seed(),p=s.players['1'],before=p.points;const r=G.grantBatch(s,[{uid:'1',characterId:p.id,type:'points',quantity:60000},{uid:'1',characterId:p.id,type:'points',quantity:60000}]);assert.equal(r[0].success,false);assert.equal(p.points,before);const t=G.grantOne(s,'1','tickets','抽卡',3);assert.equal(t.type,'抽卡');assert.equal(t.amount,3);});
test('loot repair binds only the checked multipart message and preserves already delivered parts',async()=>{const s=seed(),id='loot-record',first={id:'part-0',messageId:'111111111111111111',status:'sent'},second={id:'part-1',status:'uncertain'};s.lootPublications[id]={id,channelId:'channel',result:{pending:false,batchId:'batch',items:[M.makeItem(s.catalog.special_heart),M.makeItem(s.catalog.special_tear)]},userId:'1',publicationParts:[first,second]};const msg={id:'222222222222222222',channelId:'channel',author:{id:'bot'},embeds:require('../src/rpg/activities-ui').lootMessages(s.lootPublications[id])[1].embeds.map(e=>e.data),components:[]};const ctx=require('../src/rpg/gm-web-context').createContext({store:{snapshot:()=>s},client:{user:{id:'bot'}},outbox:{active:new Set()},textChannel:async()=>({id:'channel',messages:{fetch:async()=>msg}})}),p={kind:'loot',ref:id,partIndex:1,messageId:msg.id},before=C.clone(first);await ctx.checkPublication({g:s.guildId},p);ctx.repairPublication(s,{g:s.guildId},p);assert.deepEqual(first,before);assert.equal(second.messageId,msg.id);assert.equal(second.status,'sent');});

test('protected media renders actual battle and map PNG using current renderer signature',async t=>{const s=seed(),B=require('../src/rpg/combat'),b=B.createBattle(s,'channel',gm,'图像验收');B.join(s,b,'1');const f=F.create(s,gm,'mapcategory');f.data.name='图像类别';const cat=F.publish(s,f),m=require('../src/rpg/exploration').create(s,gm,'channel','图像地图',2,3,'random',cat.id),renderer=require('../src/rpg/map-image').createRenderer({portraits:{load:async()=>null},logFailure:()=>{}});t.after(()=>renderer.close());const ctx=require('../src/rpg/gm-web-context').createContext({store:{select:(g,fn)=>C.clone(fn(s))},renderer});for(const key of ['battle/'+b.id,'map/'+m.id]){const r=await ctx.media({g:s.guildId},key,new URLSearchParams('wide=1&gm=1'));assert.equal(r.type,'image/png');assert.equal(r.bytes.subarray(1,4).toString(),'PNG');}});
