'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const C=require('../src/rpg/constants'),M=require('../src/rpg/model'),B=require('../src/rpg/combat'),F=require('../src/rpg/forms'),U=require('../src/rpg/ui');
const Draft=require('../src/rpg/action-drafts'),BE=require('../src/rpg/battle-events'),P=require('../src/rpg/combat-presentation'),Icons=require('../src/rpg/loot-icons'),Images=require('../src/rpg/map-image');
const {createStore}=require('../src/rpg/store'),{createRpg}=require('../src/rpg'),{harness,state,fight,weapon,minRng}=require('./helpers/rpg-harness');
const controls=v=>v.components.flatMap(r=>r.toJSON().components),button=(v,label)=>controls(v).find(c=>c.label===label).custom_id;
function runtime(seed=state()) {const h=harness();require('../src/rpg/activities').migrate(seed);require('../src/rpg/skills').migrate(seed);require('../src/rpg/content-pack').install(seed);seed.config.gmRoleIds=['gm'];seed.config.playerRoleIds=['player'];let saved=C.clone(seed);h.deps.database={assertLease(){},load:async()=>C.clone(saved),save:async(_,before,next)=>{assert.equal(saved.revision,before.revision);saved=C.clone(next);}};return h;}
function draft(s,b,action,params={},actor=b.current.actorId,owner='1'){return Draft.create(s,owner,{battleId:b.id,actorId:actor,turnId:b.current?.id,action,params});}
function npc(s,b,{hpMax=100,team='enemy',baseXP=0}={}){const t=B.validateNPC(s,{...F.defaults('npc'),name:'红眼守卫',hpMax,baseXP});t.id=C.id('t');t.version=1;t.published=true;s.npcTemplates[t.id]=t;const paused=b.status==='active';if(paused)B.pause(b);const a=B.addNPC(s,b,t.id,team);B.position(b,a.id,25,25);if(paused)B.pause(b,true);return a;}
test('draft creation, cancellation and expiration leave AP, ammunition, rolls and public events untouched',()=>{
 const {s,b}=fight(),before=JSON.stringify(b),ap=s.players['1'].ap;const f=draft(s,b,'attack',{abilityKey:s.players['1'].equipped.weapon,targetId:b.actors[1].id,action:'formal'});
 assert.equal(JSON.stringify(b),before);f.status='cancelled';assert.throws(()=>Draft.execute(s,f.id,'1','不会出现'),/取消/);f.status='ready';f.expiresAt=Date.now()-1;assert.throws(()=>Draft.execute(s,f.id,'1'),/过期/);assert.equal(s.players['1'].ap,ap);assert.equal(b.publicEvents,undefined);
});
test('RP and direct execution share one stable operation and replay without a second roll',()=>{
 const {s,b}=fight(),f=draft(s,b,'attack',{abilityKey:s.players['1'].equipped.weapon,targetId:b.actors[1].id,action:'formal'});let rolls=0;const rng=(min,max)=>{rolls++;return max-1;};
 const first=Draft.execute(s,f.id,'1','我举剑向前。',rng),saved=JSON.stringify(b),count=rolls;
 assert.deepEqual(Draft.execute(s,f.id,'1','替换文本',rng),first);assert.equal(JSON.stringify(b),saved);assert.equal(rolls,count);assert.equal(b.publicEvents[0].rpEntries[0].text,'我举剑向前。');assert.equal(b.current.formal,0);
});
test('RP binds character, owner and opportunity; stale action cannot publish narration',()=>{
 const {s,b}=fight(),f=draft(s,b,'move',{x:26,y:25});assert.throws(()=>Draft.execute(s,f.id,'2','偷用'),/属于/);B.finish(s,b,b.current.id,minRng);assert.throws(()=>Draft.execute(s,f.id,'1','过期叙述'),/变化/);assert.ok(!b.publicEvents.some(e=>e.rpEntries?.length));
});
test('same opportunity move merging preserves every RP in submission order across restore',()=>{
 const {s,b}=fight();for(const [x,rp]of [[26,'迈出第一步'],[27,'随后转身']]){const f=draft(s,b,'move',{x,y:25});Draft.execute(s,f.id,'1',rp,minRng);}
 const restored=C.clone(s),e=restored.battles[b.id].publicEvents.find(e=>e.type==='move');assert.equal(restored.battles[b.id].publicEvents.filter(e=>e.type==='move').length,1);assert.deepEqual(e.rpEntries.map(r=>r.text),['迈出第一步','随后转身']);assert.equal(e.details.position.x,27);assert.equal(restored.players['1'].ap,s.players['1'].ap);
});
test('defense RP retains original 60 second deadline and cannot settle an expired hit',()=>{
 const {s,b}=fight();B.attack(s,b,b.current.id,s.players['1'].equipped.weapon,b.actors[1].id,'formal',minRng);const hit=b.pending,f=draft(s,b,'defend',{hitId:hit.id,choice:'defend'},hit.targetId,'2');assert.equal(f.expiresAt,hit.expiresAt);f.expiresAt=Date.now()-1;const hp=s.players['2'].hp;assert.throws(()=>Draft.execute(s,f.id,'2','格挡'),/过期/);assert.equal(s.players['2'].hp,hp);assert.ok(!b.publicEvents.some(e=>e.rpEntries?.length));
});
test('failed target/resource validation atomically discards RP and resource mutations',async()=>{
 const {s,b}=fight(),h=runtime(s),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);const f=await st.transact(C.DEFAULT_GUILD_ID,'prepare','1',s=>draft(s,s.battles[b.id],'move',{x:99999,y:25}));const before=st.snapshot(C.DEFAULT_GUILD_ID);await assert.rejects(st.transact(C.DEFAULT_GUILD_ID,'action:'+f.id,'1',s=>Draft.execute(s,f.id,'1','冲过去')),/范围|坐标|战场|米数/);const after=st.snapshot(C.DEFAULT_GUILD_ID);assert.deepEqual(after.battles, before.battles);assert.equal(after.forms[f.id].status,'ready');assert.equal(after.receipts['action:'+f.id],undefined);
});
test('50 duplicate RP submissions and storage restore execute only once',async()=>{
 const {s,b}=fight(),h=runtime(s),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);const f=await st.transact(C.DEFAULT_GUILD_ID,'draft','1',s=>draft(s,s.battles[b.id],'move',{x:26,y:25}));let calls=0;
 await Promise.all(Array.from({length:50},()=>st.transact(C.DEFAULT_GUILD_ID,'action:'+f.id,'1',s=>{calls++;return Draft.execute(s,f.id,'1','只走一步');})));assert.equal(calls,1);const restored=createStore(h.deps);await restored.load(C.DEFAULT_GUILD_ID);const saved=restored.snapshot(C.DEFAULT_GUILD_ID);assert.equal(saved.forms[f.id].status,'done');assert.equal(saved.battles[b.id].publicEvents.filter(e=>e.type==='move').length,1);assert.equal(saved.battles[b.id].publicEvents[0].rpEntries.length,1);
});
test('RP modal is optional, limited to 1000 characters and mentions are disabled in public and full record',async()=>{
 const {s,b}=fight(),h=runtime(s),rpg=createRpg(h.deps);await rpg.start();try{const prefix=[b.id,b.current.actorId,'1',b.current.id].join(':'),i=h.interaction('1',null,{},'rpg:movevalue:'+prefix,[],{x:'26',y:'25'});await rpg.handle(i);const open=h.interaction('1',null,{},button(i.result,'RP 并行动'));await rpg.handle(open);const m=open.modal.toJSON();assert.equal(m.components[0].components[0].max_length,1000);const done=h.interaction('1',null,{},m.custom_id,[],{rp:'@everyone <@123> 我谨慎前进。'});await rpg.handle(done);assert.match(done.result.content,/已保存/);const next=rpg.store.snapshot(C.DEFAULT_GUILD_ID).battles[b.id],e=next.publicEvents.find(e=>e.type==='move');assert.deepEqual(BE.view(next,e).allowedMentions,{parse:[]});assert.equal(e.rpEntries[0].text,'@everyone <@123> 我谨慎前进。');}finally{rpg.stop();}
});
test('fixed damage never triggers MAX; all dice including ammunition must be maximum',()=>{
 const roll=(chosen,faces=6)=>({expression:'1d'+faces,rolls:[{chosen}]});
 assert.equal(P.shotMax({rolls:{physical:{expression:'10',total:10,rolls:[]}}}),false);
 assert.equal(P.shotMax({rolls:{physical:{...roll(6),ammunition:roll(3,4)}}}),false);
 assert.equal(P.shotMax({rolls:{physical:{...roll(6),ammunition:roll(4,4)}}}),true);
 assert.equal(P.shotMax({rolls:{physical:roll(6),magical:roll(5)}}),false);
});
test('real max dice and enemy death retain both banners and confirmed XP, without repeated reward',()=>{
 const {s,b}=fight(),a=npc(s,b,{hpMax:1,baseXP:1000}),w=weapon(s,{weightKg:0,damage:{physical:'2d6'}}),item=M.issue(s,'1',w.id)[0];M.equip(s,'1',item.id);B.attack(s,b,b.current.id,item.id,a.id,'formal',(min,max)=>max-1);const hit=b.pending;B.defend(s,b,hit.id,'none',minRng);const e=b.publicEvents.find(e=>e.type==='attack'),f=P.feedback(e);assert.equal(f.full,true);assert.equal(f.killed,true);assert.equal(f.result.hpBefore,1);assert.equal(f.result.hp,0);assert.equal(f.result.reward.credited,1000);assert.match(BE.view(b,e).embeds[0].data.description,/击杀敌人[\s\S]*满伤害/);const xp=s.players['1'].xp;assert.throws(()=>B.defend(s,b,hit.id,'none'),/结算/);assert.equal(s.players['1'].xp,xp);assert.equal(Object.keys(s.deaths).length,1);
});
test('a successful dodge suppresses max-damage hit, per-shot armor reduction and target pages stay exact',()=>{
 const e={type:'attack',details:{children:[{id:'a',shots:[{}],result:{perShot:[{maxRoll:true,total:0}],dodge:{success:true}}},{id:'b',shots:[{}],result:{perShot:[{maxRoll:true,total:2}],dodge:null,total:2}}]}};
 assert.equal(P.feedback(e,{child:e.details.children[0]}).full,false);assert.equal(P.feedback(e,{child:e.details.children[1]}).full,true);
 const shots=Array.from({length:8},()=>({})),event={type:'result',details:{shots,perShot:shots.map((_,n)=>({maxRoll:n===7}))}};assert.equal(P.feedback(event,{shotPage:0}).full,false);assert.equal(P.feedback(event,{shotPage:1}).full,true);
 assert.equal(P.feedback({type:'attack',details:{shots:[{rolls:{physical:{expression:'1d6',rolls:[{chosen:6}]}}}],results:[{total:6}]}}).full,false,'old records without saved actual flags are not guessed');
});
test('armor mitigation is shown independently from full-damage banners and source dice remain immutable',()=>{
 const {s,b}=fight(),t=weapon(s,{weightKg:0,damage:{physical:'1d6'}}),w=M.issue(s,'1',t.id)[0];M.equip(s,'1',w.id);const armor=M.publishTemplate(s,{...F.defaults('item','防具'),name:'厚胸甲',defenses:{physical:4,magical:0,mental:0}});B.pause(b);M.equip(s,'2',M.issue(s,'2',armor.id)[0].id);B.pause(b,true);B.attack(s,b,b.current.id,w.id,b.actors[1].id,'formal',(min,max)=>max-1);B.defend(s,b,b.pending.id,'defend',minRng);const e=b.publicEvents.find(e=>e.type==='attack'),r=P.feedback(e).result,before=JSON.stringify(e);assert.equal(r.perShot[0].reduced.physical,4);const svg=Images.eventSVG(e,null,{section:{shotPage:0}});assert.match(svg,/满伤害/);assert.match(svg,/护甲减免 4/);assert.equal(JSON.stringify(e),before);
});
test('animation preserves first/last results, has 12 frames, finite loop and is below 2 MiB',async()=>{
 const {s,b}=fight(),f=draft(s,b,'move',{x:26,y:25});Draft.execute(s,f.id,'1','前进');const e=b.publicEvents[0],r=Images.createRenderer({portraits:{load:async()=>null},logFailure:()=>{}});try{const before=JSON.stringify(e),v=await r.decorate('fixture',BE.view(b,e)),buffer=v.files.at(-1).attachment,meta=await require('sharp')(buffer,{animated:true}).metadata();assert.equal(buffer.subarray(0,3).toString(),'GIF');assert.equal(meta.pages,12);assert.equal(meta.width,640);assert.equal(meta.loop,1);assert.ok(buffer.length<2*1024*1024);assert.equal(meta.delay.reduce((n,v)=>n+v,0),1800);assert.match(Images.eventSVG(e,null,{},0),/剩余移动/);assert.match(Images.eventSVG(e,null,{},1),/剩余移动/);assert.equal(JSON.stringify(e),before);}finally{r.close();}
});
test('every supported actual action has a readable dynamic card; skill damage types combine',()=>{
 assert.deepEqual(P.damageTypes({physical:'1d6',magical:'0',mental:''}),['physical']);assert.deepEqual(P.damageTypes({physical:'1d6',magical:'1d4',mental:'2'}),['physical','magical','mental']);
 for(const kind of ['attack','result','move','reload','switch','item','casting','pass','finish','flee','death']){const e={id:'saved',type:kind,actorName:'守卫',message:'操作已保存',details:{presentation:kind==='casting'?{kind:'skill',damageTypes:['physical','magical','mental']}:undefined}};assert.match(Images.eventSVG(e,null,{},0),/操作已保存/);assert.ok(Images.renderSVG(Images.eventSVG(e,null,{},1)).length);}
 const e={id:'saved',type:'attack',message:'技能',details:{presentation:{kind:'skill',damageTypes:['physical','magical','mental']}}};const svg=Images.eventSVG(e,null,{},.5);for(const c of ['#ffd077','#ad95ff','#ef82c9'])assert.ok(svg.includes(c));
});
test('every red builtin, legacy snapshot and GM red fallback resolves to a transparent local asset',async()=>{
 const s=state();require('../src/rpg/content-pack').install(s);const red=Object.values(s.catalog).filter(t=>t.rarity==='red');assert.equal(red.length,24);for(const t of red){assert.ok(Icons.uri({templateId:t.id,snapshot:{...t,id:undefined}}),t.id);const v=Icons.decorate(U.payload('预览',''),t);assert.ok(fs.existsSync(v.files[0].attachment));assert.equal((await require('sharp')(v.files[0].attachment).metadata()).hasAlpha,true);}assert.ok(Icons.uri({id:'custom',rarity:'red',kind:'杂物',name:'GM遗物'}));assert.equal(Icons.manifest.modern_gold_001,undefined,'unstarted gold assets were not added');
});
test('inventory, details, trade, drop and GM form previews retain authorization and actual quantities',()=>{
 const s=state(),t=s.catalog.seed_0_red,item=M.issue(s,'1',t.id)[0];assert.ok(U.itemView(s,'1','1',item.id).files.length);assert.equal(U.inventoryView(s,'1','1').rpgMap.kind,'items');const o=M.createOffer(s,'1','2');M.updateOffer(s,o.id,'1',[{id:item.id,quantity:1}],0);assert.equal(U.offerView(s,o,'1').rpgMap.items[0].quantity,1);const loot=require('../src/rpg/activities-ui').lootView({id:'loot',userId:'1',result:{item,items:[item]}});assert.ok(loot.files.length);assert.deepEqual(loot.allowedMentions,{parse:[]});
});
test('20-person battle list pages and wide view keep numbering readable and public terrain deterministic',()=>{
 const {s,b}=fight();for(let n=0;n<18;n++)npc(s,b);const page=U.battleView(s,b,1,'wide');assert.match(page.embeds[1].data.description,/11\./);assert.doesNotMatch(page.embeds[1].data.description,/\n1\./);assert.equal(page.rpgMap.page,1);const svg=Images.battleSVG(s,b,{},null,false,page.rpgMap);assert.match(svg,/width="960"/);assert.equal(svg,Images.battleSVG(s,b,{},null,false,page.rpgMap));assert.ok(controls(page).some(c=>c.label==='上一页名单'));assert.ok(Images.renderSVG(svg).length);
});
test('bulk issue hides junk, categories preserve other selections and forged junk grants fail atomically',async()=>{
 const s=state(),one=weapon(s),ammo=M.publishTemplate(s,{...F.defaults('item','弹药'),name:'分类子弹',damage:{physical:'0'}}),h=runtime(s),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);const tx=(i,fn)=>st.transact(i.guildId,i.id,i.user.id,fn),bulk=require('../src/rpg/bulk-issue').createBulkIssue({snapshot:st.snapshot,tx,needGM:()=>{}});let i=h.interaction('GM','gm',{sub:'批量发放'}),v=await bulk.start(i,h.members.GM);async function act(label,values){i=h.interaction('GM',null,{},button(v,label),values);v=await bulk.component(i,h.members.GM);}await act('选择多个物品');let cat=controls(v).find(c=>c.placeholder==='按物品分类筛选');assert.ok(!cat.options.some(o=>o.value==='junk'));let menu=controls(v).find(c=>c.placeholder==='下拉多选（最多25项）');assert.ok(menu.options.every(o=>s.catalog[o.value].kind!=='杂物'));i=h.interaction('GM',null,{},cat.custom_id,['weapon']);v=await bulk.component(i,h.members.GM);menu=controls(v).find(c=>c.placeholder==='下拉多选（最多25项）');i=h.interaction('GM',null,{},menu.custom_id,[one.id]);v=await bulk.component(i,h.members.GM);cat=controls(v).find(c=>c.placeholder==='按物品分类筛选');i=h.interaction('GM',null,{},cat.custom_id,['ammo']);v=await bulk.component(i,h.members.GM);menu=controls(v).find(c=>c.placeholder==='下拉多选（最多25项）');i=h.interaction('GM',null,{},menu.custom_id,[ammo.id]);await bulk.component(i,h.members.GM);const f=Object.values(st.snapshot(C.DEFAULT_GUILD_ID).forms).find(f=>f.kind==='bulkissue');assert.deepEqual(new Set(f.items.map(e=>e.ref)),new Set([one.id,ammo.id]));f.targets=[{uid:'1',characterId:s.players['1'].id}];f.items=[{ref:s.catalog.seed_0_white.id,quantity:1,version:1}];assert.throws(()=>require('../src/rpg/bulk-issue').execute(s,f),/杂物/);
});
test('NPC new item choices exclude junk while old references are retained; GM catalog exposes a separate junk category',()=>{
 const s=state(),w=weapon(s),f=F.create(s,'GM','npc');f.data.name='NPC';f.data.itemIds=[s.catalog.seed_0_white.id];f.field=F.fields(f).findIndex(d=>d.key==='itemIds');const v=F.choiceView(s,f),menu=controls(v).find(c=>c.placeholder.includes('随身实物'));assert.ok(menu.options.every(o=>s.catalog[o.value].kind!=='杂物'));F.setChoice(s,f,0,[w.id]);assert.ok(f.data.itemIds.includes(s.catalog.seed_0_white.id));const cat=require('../src/rpg/item-categories');assert.ok(cat.matches(s.catalog.seed_0_white,'junk',true));assert.equal(cat.matches(s.catalog.seed_0_white,'all'),false);
});
test('public text is sent before blocked animation, stale NPC images never replace newer action text',async()=>{
 const {s,b}=fight(),a=npc(s,b),h=runtime(s),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);await st.transact(C.DEFAULT_GUILD_ID,'npc-op','GM',s=>{const b=s.battles[Object.keys(s.battles)[0]];B.record(b,'守卫移动至新位置。',{actorId:a.id,x:26,y:25});});let release,rendered=0;const gate=new Promise(r=>{release=r;}),events=BE.createEvents({snapshot:st.snapshot,store:st,client:h.deps.client,textChannel:async()=>h.ch,render:async(_,v)=>{rendered++;await gate;delete v.rpgMap;v.content='OLD_ANIMATION';return v;},logFailure:()=>{}});await events.publish(C.DEFAULT_GUILD_ID,b.id);assert.equal(rendered,0);const slot=st.snapshot(C.DEFAULT_GUILD_ID).battles[b.id].npcCards[a.id],old=events.publishImage(C.DEFAULT_GUILD_ID,b.id+'/npc/'+a.id);await new Promise(r=>setImmediate(r));await st.transact(C.DEFAULT_GUILD_ID,'npc-new','GM',s=>B.record(s.battles[b.id],'守卫切换武器。',{actorId:a.id}));await events.publish(C.DEFAULT_GUILD_ID,b.id);release();await old;assert.equal(h.messages.get(slot.publication.messageId).lastPayload.content,undefined);assert.match(h.messages.get(slot.publication.messageId).lastPayload.embeds[0].data.description,/切换武器/);assert.equal(st.snapshot(C.DEFAULT_GUILD_ID).battles[b.id].npcCards[a.id].publication.messageId,slot.publication.messageId);
});
test('a delayed Discord animation PATCH cannot finish after newer NPC text and overwrite it',async()=>{
 const {s,b}=fight(),a=npc(s,b),h=runtime(s),st=createStore(h.deps);await st.load(C.DEFAULT_GUILD_ID);await st.transact(C.DEFAULT_GUILD_ID,'first-op','GM',s=>B.record(s.battles[b.id],'守卫移动至新位置。',{actorId:a.id}));
 const events=BE.createEvents({snapshot:st.snapshot,store:st,client:h.deps.client,textChannel:async()=>h.ch,render:async(_,v)=>({...v,content:'OLD_ANIMATION'}),logFailure:()=>{}});await events.publish(C.DEFAULT_GUILD_ID,b.id);const message=h.messages.get(st.snapshot(C.DEFAULT_GUILD_ID).battles[b.id].npcCards[a.id].publication.messageId),edit=message.edit;let release,entered;
 const gate=new Promise(r=>{release=r;}),started=new Promise(r=>{entered=r;});message.edit=async v=>{if(v.content==='OLD_ANIMATION'){entered();await gate;}return edit(v);};const old=events.publishImage(C.DEFAULT_GUILD_ID,b.id+'/npc/'+a.id);await started;
 await st.transact(C.DEFAULT_GUILD_ID,'new-op','GM',s=>B.record(s.battles[b.id],'守卫切换武器。',{actorId:a.id}));let textDone=false;const newest=events.publish(C.DEFAULT_GUILD_ID,b.id).then(()=>{textDone=true;});await new Promise(r=>setImmediate(r));assert.equal(textDone,false);release();await Promise.all([old,newest]);assert.equal(message.lastPayload.content,undefined);assert.match(message.lastPayload.embeds[0].data.description,/切换武器/);
});
test('an invalid later GIF frame falls back to the independently readable first PNG',async()=>{
 const r=Images.createRenderer({portraits:{load:async()=>null},logFailure:()=>{}});try{const first=Images.eventSVG({id:'fixture',type:'move',message:'移动已保存',details:{remaining:20}},null,{},0),buffer=await r.queue([first,'invalid svg'],{format:'gif',width:640});const meta=await require('sharp')(buffer).metadata();assert.equal(meta.format,'png');assert.equal(meta.width,640);assert.ok(meta.height>0);}finally{r.close();}
});
test('a busy animation job stays durable without using failure attempts and resumes after restore',async()=>{
 const h=runtime(),st=createStore(h.deps),O=require('../src/rpg/outbox');await st.load(C.DEFAULT_GUILD_ID);await st.transact(C.DEFAULT_GUILD_ID,'image-task','GM',s=>O.put(s,'eventImage','fixture/player/event',{priority:20}),null,{delivery:false});let calls=0;const box=O.createOutbox({store:st,client:h.deps.client,handlers:{eventImage:async()=>{calls++;throw Object.assign(Error('busy'),{code:'RPG_RENDER_BUSY'});}},logFailure:()=>{}});box.start();
 try{for(let n=0;n<100;n++){const j=st.snapshot(C.DEFAULT_GUILD_ID).deliveryJobs['eventImage:fixture/player/event'];if(calls===1&&j.status==='pending'&&j.availableAt>Date.now())break;await new Promise(r=>setTimeout(r,10));}const j=st.snapshot(C.DEFAULT_GUILD_ID).deliveryJobs['eventImage:fixture/player/event'];assert.equal(j.status,'pending');assert.equal(j.attempts,0);assert.equal(calls,1);}finally{box.stop();await box.drain();}
 const restored=createStore(h.deps);await restored.load(C.DEFAULT_GUILD_ID);await restored.transact(C.DEFAULT_GUILD_ID,'retry-image','GM',s=>{s.deliveryJobs['eventImage:fixture/player/event'].availableAt=0;},null,{delivery:false});const next=O.createOutbox({store:restored,client:h.deps.client,handlers:{eventImage:async()=>{calls++;}},logFailure:()=>{}});next.start();try{for(let n=0;n<100&&restored.snapshot(C.DEFAULT_GUILD_ID).deliveryJobs['eventImage:fixture/player/event'].status!=='done';n++)await new Promise(r=>setTimeout(r,10));assert.equal(restored.snapshot(C.DEFAULT_GUILD_ID).deliveryJobs['eventImage:fixture/player/event'].status,'done');assert.equal(calls,2);}finally{next.stop();await next.drain();}
});
