'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),crypto=require('node:crypto');
const C=require('../src/rpg/constants'),M=require('../src/rpg/model'),F=require('../src/rpg/forms'),G=require('../src/rpg/gm-service'),U=require('../src/rpg/ui');
const {createStore}=require('../src/rpg/store'),{createGmWeb}=require('../src/rpg/gm-web');
const gm='123456789012345678';
const {seed,harness}=require('./helpers/gm-web-fixture.cjs');
test('upgrade 9 initializes only web devices and is idempotent, preserving assets and active deadlines',()=>{const s=seed();s.upgrade=8;s.forms.f={expiresAt:Date.now()+1234};const before=C.clone(s);assert.deepEqual(require('../src/rpg/gm-web-upgrade').migrate(s),{gmWeb:9});assert.deepEqual(s.players,before.players);assert.deepEqual(s.forms,before.forms);assert.equal(require('../src/rpg/gm-web-upgrade').migrate(s),null);assert.ok(require('../src/rpg/postgres').COLLECTIONS.has('gmWebDevices'));});
test('template batch validates each row, rejects stale publishing and keeps legacy entered text',()=>{const s=seed(),rows=[{kind:'trait',data:{name:'合法',description:'',effects:[]},baseVersion:0},{kind:'trait',data:{name:'',effects:[]},baseVersion:0}];const check=G.validateBatch(s,rows,gm);assert.equal(check[0].success,true);assert.equal(check[1].success,false);assert.equal(Object.values(s.traits).length,1);const t=G.publishBatch(s,[rows[0]],gm)[0],first=F.create(s,gm,'trait',null,t.id),second=F.create(s,gm,'trait',null,t.id);first.data.name='新名称';F.publish(s,first);second.data.name='保留填写';assert.throws(()=>F.publish(s,second),/修改/);assert.equal(second.data.name,'保留填写');delete second.baseTemplateVersion;assert.throws(()=>F.publish(s,second),/旧修改草稿/);});
test('binding is private, one-use and device-bound; reads and revocation always enforce current GM',async t=>{const h=await harness(t);assert.equal((await h.call('/session')).status,401);const b=await h.bind();assert.equal((await h.call('/session')).data.userId,gm);assert.equal((await h.call('/pair',{...b.p,deviceId:crypto.randomUUID()},false)).status,422);const devices=await h.call('/devices');assert.ok(devices.data.every(d=>!d.credentialHash));h.setRole(false);assert.equal((await h.call('/session')).status,403);h.setRole(true);await h.call('/devices/revoke',{id:b.deviceId});assert.equal((await h.call('/session')).status,401);});
test('batch grants preserve recipient atomicity and exclude junk without cancelling other recipients',()=>{const s=seed(),heavy=M.publishTemplate(s,{...F.defaults('item','药品'),name:'超重药品',weightKg:1000,heal:'1',rarity:'white'}),light=M.publishTemplate(s,{...F.defaults('item','药品'),name:'轻药',weightKg:0,heal:'1',rarity:'white'}),rows=[{uid:'1',characterId:s.players['1'].id,type:'item',ref:light.id,quantity:1},{uid:'1',characterId:s.players['1'].id,type:'item',ref:heavy.id,quantity:1},{uid:'2',characterId:s.players['2'].id,type:'item',ref:light.id,quantity:2}];const result=G.grantBatch(s,rows);assert.equal(result[0].success,false);assert.equal(Object.keys(s.players['1'].inventory).length,0);assert.equal(result[1].success,true);assert.equal(Object.values(s.players['2'].inventory)[0].quantity,2);const junk=Object.values(s.catalog).find(t=>t.kind==='杂物');assert.throws(()=>G.grantOne(s,'1','item',junk.id,1),/杂物/);});
test('HTTP duplicate burst executes once and survives receipt expiry/restart and reply loss',async t=>{const h=await harness(t);await h.bind();const p=h.store.select(C.DEFAULT_GUILD_ID,s=>s.players['1']),f=(await h.call('/previews',{command:'grant',params:{rows:[{uid:'1',characterId:p.id,type:'points',quantity:3}]}})).data;assert.ok(f?.id);h.failAfterCommit();const replies=await Promise.all(Array.from({length:50},()=>h.call('/commands',{draftId:f.id})));assert.ok(replies.every(r=>[200,202].includes(r.status)));assert.equal(h.store.select(C.DEFAULT_GUILD_ID,s=>s.players['1'].points),5);const op=await h.call('/operations/gm-web:'+f.id);assert.equal(op.data.status,'committed');await h.store.transact(C.DEFAULT_GUILD_ID,'expire-receipt',gm,s=>{delete s.receipts['gm-web:'+f.id];});await h.store.recover(C.DEFAULT_GUILD_ID);assert.equal((await h.call('/commands',{draftId:f.id})).data.status,'committed');assert.equal(h.store.select(C.DEFAULT_GUILD_ID,s=>s.players['1'].points),5);});
test('concurrent state or permission change keeps a draft unexecuted and input recoverable',async t=>{const h=await harness(t);await h.bind();const p=h.store.select(C.DEFAULT_GUILD_ID,s=>s.players['1']),draft=(await h.call('/previews',{command:'grant',params:{rows:[{uid:'1',characterId:p.id,type:'points',quantity:3}]}})).data;await h.store.transact(C.DEFAULT_GUILD_ID,'another-gm',gm,s=>{s.players['1'].points++;});assert.equal((await h.call('/commands',{draftId:draft.id})).status,409);assert.equal((await h.call('/operations/gm-web:'+draft.id)).data.status,'uncommitted');h.setConfig(false);assert.equal((await h.call('/previews',{command:'config.save',params:{data:{gmRoleIds:[]}}})).status,403);});
test('frozen store permits safe reads and authority recovery, not a duplicate write',async t=>{const h=await harness(t);await h.bind();h.store.freeze(C.DEFAULT_GUILD_ID);assert.equal((await h.call('/session')).data.frozen,true);assert.equal((await h.call('/collections/players')).status,200);assert.equal((await h.call('/previews',{command:'grant',params:{rows:[]}})).status,503);assert.equal((await h.call('/recover',{})).status,200);assert.equal(h.store.frozen(C.DEFAULT_GUILD_ID),false);});
test('20 HTTP operations finish independently of blocked publications and expose saved metadata only',async t=>{const h=await harness(t);await h.bind();const never=new Promise(()=>{});h.store.onCommit(()=>never);const drafts=[];for(let n=1;n<=20;n++){const uid=String(n),p=h.store.select(C.DEFAULT_GUILD_ID,s=>s.players[uid]);drafts.push((await h.call('/previews',{command:'grant',params:{rows:[{uid,characterId:p.id,type:'points',quantity:1}]}})).data);}const times=[];const results=await Promise.all(drafts.map(async f=>{const start=performance.now(),r=await h.call('/commands',{draftId:f.id});times.push(performance.now()-start);return r;}));assert.ok(results.every(r=>r.status===200));assert.ok(h.store.select(C.DEFAULT_GUILD_ID,s=>Object.values(s.players).every(p=>p.points===3)));times.sort((a,b)=>a-b);console.log(JSON.stringify({test:'gm-web-http-20-mock-discord',resultP95Ms:Math.ceil(times[18])}));assert.ok(times[18]<3000);const schemas=await h.call('/schemas');assert.equal(schemas.status,200);assert.ok(schemas.data.commands.some(c=>c.id==='battle.partyDeath'));assert.ok(!(await h.call('/collections/forms')).data.items.some(f=>f.kind==='gmWebBind'));});


test('web uses zero-based map clicks consistently, pauses skill changes and previews death without altering life',()=>{const s=seed(),X=require('../src/rpg/exploration'),cf=F.create(s,gm,'mapcategory');cf.data.name='隔离类别';const cat=F.publish(s,cf),m=X.create(s,gm,'channel','坐标验收',2,3,'random',cat.id);G.apply(s,gm,'map.cell',{mapId:m.id,x:2,y:1,type:'corridor',passable:true});assert.equal(m.cells['2,1'].type,'corridor');assert.equal(m.width,3);const B=require('../src/rpg/combat'),b=B.createBattle(s,'webbattle',gm,'隔离战斗');B.join(s,b,'1');const f=F.create(s,gm,'skill');f.data.name='隔离技能';const skill=F.publish(s,f);b.status='active';assert.throws(()=>G.grantOne(s,'1','skill',skill.id,1),/暂停/);b.status='paused';const before=C.clone(s.players['1']);const result=require('../src/rpg/gm-web-preview').preview(s,gm,'battle.death',{battleId:b.id,actorId:b.actors[0].id,reason:'隔离验收'});assert.equal(result.affected[0].name,b.actors[0].name);assert.deepEqual(s.players['1'],before);});
test('duplicate import IDs and NPC skills cannot silently overwrite a newer template',()=>{const s=seed(),t=G.publishBatch(s,[{kind:'trait',baseVersion:0,data:{name:'基线',effects:[]}}],gm)[0],row={kind:'trait',id:t.id,baseVersion:t.version,data:{name:'修改',effects:[]}},rows=G.validateBatch(s,[row,row],gm);assert.equal(rows[0].success,true);assert.equal(rows[1].success,false);assert.match(rows[1].reason,/重复/);});
test('GM permission is checked again after a queued preview, not just before joining the queue',async t=>{const h=await harness(t);await h.bind();let release,entered;const ready=new Promise(r=>entered=r),hold=h.store.transact(C.DEFAULT_GUILD_ID,'hold','test',async()=>{entered();await new Promise(r=>release=r);});await ready;const request=h.call('/previews',{command:'grant',params:{rows:[{uid:'1',characterId:h.canonical().players['1'].id,type:'points',quantity:1}]}});await new Promise(r=>setTimeout(r,20));h.setRole(false);release();await hold;assert.equal((await request).status,403);assert.equal(h.store.select(C.DEFAULT_GUILD_ID,s=>s.players['1'].points),2);});
test('publication repair rejects same-title foreign objects and rechecks the saved delivery state',async()=>{const s=seed(),B=require('../src/rpg/combat'),b=B.createBattle(s,'channel',gm,'同名战斗');let message={id:'123456789012345679',channelId:'channel',author:{id:'bot'},embeds:[{title:'同名战斗',footer:{text:'战斗 wrong-id'}}],components:[]};const ctx=require('../src/rpg/gm-web-context').createContext({store:{snapshot:()=>s},client:{user:{id:'bot'}},outbox:{active:new Set()},textChannel:async()=>({id:'channel',messages:{fetch:async()=>message}})}),a={g:s.guildId},p={kind:'battle',ref:b.id,messageId:message.id};await assert.rejects(ctx.checkPublication(a,p),/属于Bot/);message.embeds[0].footer.text='战斗 '+b.id+' · active';await ctx.checkPublication(a,p);b.boardPublication={status:'uncertain'};assert.throws(()=>ctx.repairPublication(s,a,p),/变化/);await ctx.checkPublication(a,p);const r=ctx.repairPublication(s,a,p);assert.equal(r.status,'queued');assert.equal(b.messageId,message.id);});
test('shipped template import examples use valid targets and versions',()=>{const rows=JSON.parse(require('node:fs').readFileSync(require('node:path').join(__dirname,'../gm-web/samples/模板-新建.json'),'utf8')),s=seed();assert.ok(G.validateBatch(s,rows,gm).every(r=>r.success));});

test('duplicate grant rows obey existing per-project caps and Discord ticket result remains compatible',()=>{const s=seed(),p=s.players['1'],before=p.points;const r=G.grantBatch(s,[{uid:'1',characterId:p.id,type:'points',quantity:60000},{uid:'1',characterId:p.id,type:'points',quantity:60000}]);assert.equal(r[0].success,false);assert.equal(p.points,before);const t=G.grantOne(s,'1','tickets','抽卡',3);assert.equal(t.type,'抽卡');assert.equal(t.amount,3);});
test('loot repair binds only the checked multipart message and preserves already delivered parts',async()=>{const s=seed(),id='loot-record',first={id:'part-0',messageId:'111111111111111111',status:'sent'},second={id:'part-1',status:'uncertain'};s.lootPublications[id]={id,channelId:'channel',result:{pending:false,batchId:'batch',items:[M.makeItem(s.catalog.special_heart),M.makeItem(s.catalog.special_tear)]},userId:'1',publicationParts:[first,second]};const msg={id:'222222222222222222',channelId:'channel',author:{id:'bot'},embeds:require('../src/rpg/activities-ui').lootMessages(s.lootPublications[id])[1].embeds.map(e=>e.data),components:[]};const ctx=require('../src/rpg/gm-web-context').createContext({store:{snapshot:()=>s},client:{user:{id:'bot'}},outbox:{active:new Set()},textChannel:async()=>({id:'channel',messages:{fetch:async()=>msg}})}),p={kind:'loot',ref:id,partIndex:1,messageId:msg.id},before=C.clone(first);await ctx.checkPublication({g:s.guildId},p);ctx.repairPublication(s,{g:s.guildId},p);assert.deepEqual(first,before);assert.equal(second.messageId,msg.id);assert.equal(second.status,'sent');});

test('protected media renders actual battle and map PNG using current renderer signature',async t=>{const s=seed(),B=require('../src/rpg/combat'),b=B.createBattle(s,'channel',gm,'图像验收');B.join(s,b,'1');const f=F.create(s,gm,'mapcategory');f.data.name='图像类别';const cat=F.publish(s,f),m=require('../src/rpg/exploration').create(s,gm,'channel','图像地图',2,3,'random',cat.id),renderer=require('../src/rpg/map-image').createRenderer({portraits:{load:async()=>null},logFailure:()=>{}});t.after(()=>renderer.close());const ctx=require('../src/rpg/gm-web-context').createContext({store:{select:(g,fn)=>C.clone(fn(s))},renderer});for(const key of ['battle/'+b.id,'map/'+m.id]){const r=await ctx.media({g:s.guildId},key,new URLSearchParams('wide=1&gm=1'));assert.equal(r.type,'image/png');assert.equal(r.bytes.subarray(1,4).toString(),'PNG');}});

test('GM map dimensions remain numeric while bulk operations require row arrays',async t=>{
 const s=seed(),cf=F.create(s,gm,'mapcategory');cf.data.name='地图入口验收';cf.data.mapTypes=['indoor','region'];const cat=F.publish(s,cf),h=await harness(t,{seed:s});await h.bind();
 for(const mapType of ['indoor','region'])for(const mode of ['manual','fixed','full']){
  const params={name:'入口-'+mapType+'-'+mode,channelId:'123456789012345679',categoryId:cat.id,mapType,mode,rows:4,width:3,blockedPercent:15,stairsMin:1,stairsMax:3,maxRank:3};
  const preview=await h.call('/previews',{command:'map.create',params});assert.equal(preview.status,200,JSON.stringify(preview.error));
  const before=Object.keys(h.canonical().explorations).length;const result=await h.call('/commands',{draftId:preview.data.id});assert.equal(result.status,200,JSON.stringify(result.error));
  const again=await h.call('/commands',{draftId:preview.data.id});assert.equal(again.data.result.id,result.data.result.id);assert.equal(Object.keys(h.canonical().explorations).length,before+1);
  const m=h.canonical().explorations[result.data.result.id];assert.equal(m.mapType,mapType);if(mode!=='full'){assert.equal(m.floors,4);assert.equal(m.width,3);}
 }
 for(const command of ['grant','templates.publish']){const r=await h.call('/previews',{command,params:{rows:4}});assert.equal(r.status,422);assert.match(r.error.message,/清单|列表/);assert.doesNotMatch(r.error.message,/iterable|function|TypeError/);}
});
test('new battle preview validates recruitment without requiring an existing battle',async t=>{
 const h=await harness(t);await h.bind();const p={name:'新战斗入口',channelId:'123456789012345679',width:3,height:4};
 const f=await h.call('/previews',{command:'battle.create',params:p});assert.equal(f.status,200,JSON.stringify(f.error));assert.equal(Object.keys(h.canonical().battles).length,0);
 const r=await h.call('/commands',{draftId:f.data.id});assert.equal(r.status,200,JSON.stringify(r.error));assert.equal(r.data.result.status,'recruiting');assert.equal(Object.keys(h.canonical().battles).length,1);
 const invalid=await h.call('/previews',{command:'battle.create',params:p});assert.equal(invalid.status,422);assert.match(invalid.error.message,/已有战斗/);
});

test('narrow random maps retain a room and minimum vertical links even when every candidate becomes stairs',()=>{
 const s=seed(),f=F.create(s,gm,'mapcategory');f.data.name='窄图';const cat=F.publish(s,f),Layout=require('../src/rpg/random-layout'),X=require('../src/rpg/exploration');
 const m=Layout.create(s,gm,'channel','全楼梯边界','indoor','manual',cat.id,4,3,{blockedPercent:0,stairsMin:1,stairsMax:3},(min,max)=>max-1);
 assert.ok(Object.values(m.cells).some(c=>c.type==='room'));assert.doesNotThrow(()=>X.validateMap(m));
 for(let y=1;y<m.floors;y++){let links=0;for(let x=0;x<m.width;x++)if(['stairs','entrance'].includes(m.cells[x+','+(y-1)]?.type)&&['stairs','entrance'].includes(m.cells[x+','+y]?.type))links++;assert.ok(links>=1);}
});


test('quick map creation saves content atomically, preserves previews and recovers one result',async t=>{
 const s=seed(),f=F.create(s,gm,'mapcategory');f.data.name='快速主题';f.data.mapTypes=['indoor','region'];const category=F.publish(s,f),r=F.create(s,gm,'room');r.data.name='快速房间';r.data.categoryIds=[category.id];F.publish(s,r);
 const h=await harness(t,{seed:s});await h.bind();const base={name:'完整地图',channelId:'123456789012345679',categoryId:category.id,mapType:'indoor',mode:'manual',rows:4,width:3,stairsMin:1,stairsMax:3,maxRank:3};
 for(const mapType of ['indoor','region'])for(const mode of ['manual','full','fixed']){
  const before=Object.keys(h.canonical().explorations).length,f=await h.call('/previews',{command:'map.quickCreate',params:{...base,mapType,mode}});assert.equal(f.status,200,JSON.stringify(f.error));assert.equal(Object.keys(h.canonical().explorations).length,before);
  const replies=await Promise.all(Array.from({length:mode==='manual'?50:20},()=>h.call('/commands',{draftId:f.data.id})));assert.ok(replies.every(r=>[200,202].includes(r.status)),JSON.stringify(replies.find(r=>![200,202].includes(r.status))));const id=replies.find(r=>r.status===200).data.result.id,m=h.canonical().explorations[id];assert.equal(Object.keys(h.canonical().explorations).length,before+1);assert.equal(m.status,'draft');assert.equal(!!m.generated,mode!=='fixed');if(mode!=='fixed')assert.ok(Object.values(m.cells).filter(c=>c.type==='room'||c.hasContents).every(c=>c.room));await h.store.recover(s.guildId);assert.deepEqual(h.canonical().explorations[id].cells,m.cells);
 }
 const invalid=await h.call('/previews',{command:'map.quickCreate',params:{...base,width:1}});assert.equal(invalid.status,422);assert.match(invalid.error.message,/楼梯|列数/);
 const before=C.clone(h.canonical().explorations),state=h.canonical();state.roomTemplates={};assert.throws(()=>G.apply(state,gm,'map.quickCreate',base),/主题/);assert.deepEqual(state.explorations,before);
});

test('map options and GM battle context expose consistent names and action data',async t=>{
 const h=await harness(t);await h.bind();const opts=await h.call('/context/maps');assert.equal(opts.status,200);assert.ok(opts.data.cellTypes.indoor.room);assert.ok(Array.isArray(opts.data.rooms));
 await h.store.transact(C.DEFAULT_GUILD_ID,'context-fixture',gm,s=>{const b=require('../src/rpg/combat').createBattle(s,'123456789012345679',gm,'数据接口',3,4);require('../src/rpg/combat').join(s,b,'1');});
 const id=Object.keys(h.canonical().battles)[0],r=await h.call('/context/battle?id='+id);assert.equal(r.status,200);assert.equal(r.data.actors[0].ap,h.canonical().players['1'].ap);assert.equal(r.data.actors[0].opportunities,0);assert.equal(r.data.actors[0].nextCost,100);assert.ok(r.data.actors[0].health.maxHP>0);
});


test('editing map labels preserves generated room snapshots; replacing terrain requires regeneration',()=>{
 const s=seed(),f=F.create(s,gm,'mapcategory');f.data.name='编辑主题';const cat=F.publish(s,f),r=F.create(s,gm,'room');r.data.name='冻结房间';r.data.categoryIds=[cat.id];F.publish(s,r);
 const m=G.apply(s,gm,'map.quickCreate',{name:'编辑验收',channelId:'channel',categoryId:cat.id,mapType:'indoor',mode:'manual',rows:4,width:3,stairsMin:1,stairsMax:3,maxRank:3}),map=s.explorations[m.id],ref=Object.keys(map.cells).find(k=>map.cells[k].room),c=map.cells[ref],before=C.clone(c.room),[x,y]=ref.split(',').map(Number);
 const params={mapId:map.id,x,y,type:c.type,categoryId:c.categoryId,templateId:c.templateId,variantId:c.variantId,name:'可读名字',passable:true,hasContents:!!c.hasContents};
 G.apply(s,gm,'map.cell',params);assert.deepEqual(map.cells[ref].room,before);assert.equal(map.generated,true);
 map.cells[ref].touched=true;assert.throws(()=>G.apply(s,gm,'map.cell',{...params,variantId:'changed'}),/交互记录/);assert.deepEqual(map.cells[ref].room,before);
 map.cells[ref].touched=false;G.apply(s,gm,'map.cell',{...params,type:'corridor'});assert.equal(map.generated,false);assert.equal(map.cells[ref].room,undefined);
});
