'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../src/rpg/constants'),M=require('../src/rpg/model'),B=require('../src/rpg/combat'),F=require('../src/rpg/forms'),H=require('../src/rpg/health'),X=require('../src/rpg/exploration'),V=require('../src/rpg/merchant'),Move=require('../src/rpg/movement-panel'),Draft=require('../src/rpg/action-drafts'),BE=require('../src/rpg/battle-events'),{createStore}=require('../src/rpg/store'),{createRpg}=require('../src/rpg');
const {state,fight,harness,weapon,minRng}=require('./helpers/rpg-harness');
const controls=v=>(v.components||[]).flatMap(r=>r.toJSON().components),click=(v,label)=>{const c=controls(v).find(c=>c.label===label);assert.ok(c,label);return c.custom_id;};
function runtime(seed){const h=harness();require('../src/rpg/activities').migrate(seed);require('../src/rpg/skills').migrate(seed);seed.config.gmRoleIds=['gm'];seed.config.playerRoleIds=['player'];let saved=C.clone(seed);h.deps.database={assertLease(){},load:async()=>C.clone(saved),save:async(_,before,next)=>{assert.equal(saved.revision,before.revision);saved=C.clone(next);}};return h;}
function consumable(s,extra={}){const t=M.publishTemplate(s,{...F.defaults('item','药品'),name:'急救药',heal:'1d6',weightKg:0,value:10,...extra});return t;}
function merchant(s=state(),extra={}){const t=consumable(s),w=weapon(s,{weightKg:0}),pool=V.publish(s,{name:'流浪商人',sellMode:'fixed',entries:[{ref:t.id,quantity:10}],buyQuota:10,...extra});
 const m={id:C.id('m'),status:'draft',version:1,mapType:'indoor',width:3,floors:1,participants:{},revealed:{},cells:{'0,0':{type:'entrance'},'1,0':{type:'corridor'},'2,0':{type:'room'}}};s.explorations[m.id]=m;const node=V.assign(s,m,'2,0',pool.id,minRng);m.generated=true;X.publish(s,m);for(const uid of ['1','2','3']){X.join(s,m,uid);m.participants[uid].cell='2,0';s.players[uid].balance=1000;}m.cells['2,0'].touched=true;m.revealed['2,0']=true;return {s,m,node,t,w,pool};}
function valid(v){assert.ok(v.components.length<=5);for(const row of controls(v)){if(row.custom_id)assert.ok(row.custom_id.length<=100);if(row.options)assert.ok(row.options.length<=25);}assert.deepEqual(v.allowedMentions,{parse:[]});}
test('upgrade 8 extends unfinished future confirmations once and cancels action media without changing assets or opportunity',()=>{
 const {s,b}=fight(),now=100000;s.upgrade=7;s.forms={open:{expiresAt:now+1},expired:{expiresAt:now},done:{done:true,expiresAt:now+1},ended:{battleId:'ended',expiresAt:now+1}};s.battles.ended={status:'ended',actors:[]};s.offers={q:{status:'ready',expiresAt:now+1}};s.explorations={m:{moves:{q:{status:'pending',expiresAt:now+1},past:{status:'pending',expiresAt:now-1}}}};b.pending={id:'hit',expiresAt:now+1};s.deliveryJobs={gif:{kind:'eventImage',status:'running'},past:{kind:'eventImage',status:'done'},map:{kind:'map',status:'pending'}};const assets=C.clone(s.players),turn=C.clone(b.current),ap=s.players['1'].ap;const r=require('../src/rpg/interaction-upgrade').migrate(s,now);assert.equal(r.deadlines,4);assert.equal(s.forms.open.expiresAt,now+60001);assert.equal(s.forms.expired.expiresAt,now);assert.equal(s.forms.done.expiresAt,now+1);assert.equal(s.forms.ended.expiresAt,now+1);assert.equal(s.deliveryJobs.gif.status,'done');assert.equal(s.deliveryJobs.map.status,'pending');assert.deepEqual(s.players,assets);assert.deepEqual(b.current,turn);assert.equal(s.players['1'].ap,ap);assert.equal(require('../src/rpg/interaction-upgrade').migrate(s,now),null);
});
test('new defense/ordinary/AOE/trade deadlines add exactly sixty seconds; RP and pagination never renew them',async()=>{
 const {s,b}=fight(),before=Date.now(),f=Draft.create(s,'1',{battleId:b.id,actorId:b.current.actorId,turnId:b.current.id,action:'move',params:{x:26,y:25}});assert.ok(f.expiresAt>=before+360000&&f.expiresAt<Date.now()+360001);B.attack(s,b,b.current.id,s.players['1'].equipped.weapon,b.actors[1].id,'formal',minRng);assert.ok(b.pending.expiresAt>=before+120000);const d=Draft.create(s,'2',{battleId:b.id,actorId:b.actors[1].id,action:'defend',params:{hitId:b.pending.id,choice:'none'}});assert.equal(d.expiresAt,b.pending.expiresAt);Draft.view(s,d.id,'2');assert.equal(d.expiresAt,b.pending.expiresAt);assert.equal(C.OFFER_TTL,360000);assert.equal(C.confirmationDeadline(600000,0),660000);
 const nav=require('../src/rpg/navigation').createNavigation(()=>s),i={guildId:s.guildId,user:{id:'1'}},v=require('../src/rpg/ui').personalView(s,b,b.actors[0],'1');const first=nav.wrap(i,v),route=controls(first).find(c=>c.custom_id).custom_id,j={guildId:s.guildId,user:{id:'1'},customId:route};nav.resolve(j);nav.wrap(j,v);assert.ok(j.rpgResponseGroup===i.rpgResponseGroup);
});
test('reachable cell points use true distance and difficult-terrain cost, exclude obstacles and respect tiny budgets',async()=>{
 const {s,b}=fight(),a=b.actors[0];b.terrain['1,0']='blocked';b.current.move=0.1;a.x=49.95;a.y=25;const p=Move.points(s,b,a,0,0).filter(p=>p.cost);assert.ok(p.length);assert.ok(p.every(p=>p.cost<=.1));assert.ok(!Move.points(s,b,a,1,0).some(p=>p.cost));b.terrain['1,0']='difficult';b.current.move=10;const range=await Move.reachable(s,b,a);for(const c of range)for(const p of c.points){assert.equal(p.cost,B.movementCost(b,a,p));assert.ok(p.cost<=10);}
});
test('relative movement stops at target, boundary, obstacle or budget and never routes around a wall',()=>{
 const {s,b}=fight(),a=b.actors[0],enemy=b.actors[1];enemy.team='enemy';a.x=25;a.y=25;enemy.x=30;enemy.y=25;b.current.move=20;assert.equal(Move.relative(s,b,a,enemy,'20').x,30);const away=Move.relative(s,b,a,enemy,'remaining',true);assert.ok(away.x>=0&&away.distance<=20);b.terrain['1,0']='blocked';enemy.x=120;const close=Move.relative(s,b,a,enemy,'remaining');assert.ok(close.x<50);enemy.x=a.x;enemy.y=a.y;const first=Move.relative(s,b,a,enemy,'5',true);assert.deepEqual(Move.relative(s,b,a,enemy,'5',true),first);assert.ok(first.distance>0);assert.throws(()=>Move.relative(s,b,a,enemy,'7'),/距离/);
});
test('movement cache invalidates on position, remaining budget and terrain; preview commit rechecks both geometry and enemy',async()=>{
 const {s,b}=fight(),a=b.actors[0],enemy=b.actors[1];enemy.team='enemy';const first=Move.fingerprint(s,b,a);await Move.reachable(s,b,a);b.current.move--;assert.notEqual(Move.fingerprint(s,b,a),first);const p=Move.relative(s,b,a,enemy,'5',true),f=Draft.create(s,'1',{battleId:b.id,actorId:a.id,turnId:b.current.id,action:'move',params:{...p,movementFingerprint:Move.fingerprint(s,b,a)}});enemy.x++;assert.throws(()=>Draft.execute(s,f.id,'1','测试'),/敌人位置/);assert.equal(f.status,'ready');b.terrain['0,1']='blocked';assert.notEqual(Move.fingerprint(s,b,a),first);
});
test('20 by 20 handmade battlefield cell pages and nine-point selector fit Discord limits and issue no coordinate modal',async()=>{
 const {s,b}=fight();b.width=b.height=20;const h=runtime(s),rpg=createRpg(h.deps);await rpg.start();try{const i=h.interaction('1',null,{},'rpg:move:'+b.id+':'+b.actors[0].id+':1:'+b.current.id);await rpg.handle(i);valid(i.result);assert.equal(i.modal,undefined);const cell=controls(i.result).find(c=>c.label==='A1');assert.ok(cell);const j=h.interaction('1',null,{},cell.custom_id);await rpg.handle(j);valid(j.result);assert.ok(controls(j.result).some(c=>c.label?.startsWith('正中')));}finally{rpg.stop();await rpg.drain();}
});
test('old arbitrary coordinate route is rejected and restores a latest usable panel without moving',async()=>{
 const {s,b}=fight(),h=runtime(s),rpg=createRpg(h.deps);await rpg.start();try{const i=h.interaction('1',null,{},'rpg:movevalue:'+b.id+':'+b.actors[0].id+':1:'+b.current.id,[],{x:'26',y:'25'});await rpg.handle(i);assert.match(i.result.content,/停用|失效/);assert.ok(i.result.components.length);assert.equal(rpg.store.snapshot(s.guildId).battles[b.id].actors[0].x,25);}finally{rpg.stop();await rpg.drain();}
});
test('stale navigation restores valid buttons and never replays the stale mutation',async()=>{
 const {s,b}=fight(),h=runtime(s),rpg=createRpg(h.deps);await rpg.start();try{const open=h.interaction('1',null,{},'rpg:view:'+b.id+':'+b.actors[0].id+':1:'+b.current.id+':move');await rpg.handle(open);const route=controls(open.result).find(c=>c.label==='点地图移动').custom_id;const j=h.interaction('1',null,{},route);await rpg.handle(j);const old=h.interaction('1',null,{},route);await rpg.handle(old);assert.match(old.result.content,/失效/);assert.ok(old.result.components.length);assert.equal(rpg.store.snapshot(s.guildId).battles[b.id].publicEvents?.length||0,0);}finally{rpg.stop();await rpg.drain();}
});
test('a committed action whose first reply fails is read through its receipt and not executed twice',async()=>{
 const {s,b}=fight(),f=Draft.create(s,'1',{battleId:b.id,actorId:b.actors[0].id,turnId:b.current.id,action:'move',params:{x:26,y:25}}),h=runtime(s),rpg=createRpg(h.deps);await rpg.start();try{const i=h.interaction('1',null,{},'rpg:act:do:'+f.id),edit=i.editReply;let calls=0;i.editReply=async v=>{if(++calls===1)throw Error('reply failed');return edit(v);};await rpg.handle(i);assert.match(i.result.content,/操作已保存/);assert.ok(i.result.components.length);const saved=rpg.store.snapshot(s.guildId);assert.equal(saved.battles[b.id].actors[0].x,26);assert.equal(saved.battles[b.id].publicEvents.length,1);}finally{rpg.stop();await rpg.drain();}
});
test('battle bulk medicines consume one quick action each, keep AP, save per-unit rolls and produce one paged RP event',()=>{
 const {s,b}=fight(),t=consumable(s),item=M.issue(s,'1',t.id,3)[0];s.players['1'].hp=1;b.current.quick=3;const ap=s.players['1'].ap,f=Draft.create(s,'1',{battleId:b.id,actorId:b.actors[0].id,turnId:b.current.id,action:'item',params:{itemId:item.id,quantity:3}});let rolls=0;Draft.execute(s,f.id,'1','连续急救',(lo,hi)=>{rolls++;return lo;});assert.equal(rolls,3);assert.equal(b.current.quick,0);assert.equal(s.players['1'].ap,ap);assert.equal(s.players['1'].inventory[item.id],undefined);const e=b.publicEvents.find(e=>e.type==='item');assert.equal(e.details.children.length,3);assert.equal(e.rpEntries.length,1);for(let page=0;page<3;page++){const v=BE.view(b,e,page);assert.match(v.embeds[0].data.description,/使用件次/);assert.doesNotMatch(v.embeds[0].data.description,/undefined|NaN/);assert.equal(v.rpgMap,undefined);}Draft.execute(s,f.id,'1','重试',()=>{throw Error('reroll');});
});
test('bulk medicine stages every piece and rolls back a late invalid effect without consuming items or health',()=>{
 const s=state(),t=consumable(s,{duration:{kind:'actions',count:2},effects:[{target:'attr:constitution',op:'add',value:1}]}),item=M.issue(s,'1',t.id,3)[0];s.players['1'].inventory[item.id].snapshot.duration.kind='bad';const before=C.clone(s.players);assert.throws(()=>M.consumeMany(s.players['1'],item.id,3,minRng),/持续时间/);assert.deepEqual(s.players,before);
});
test('bulk medicine rejects quantities beyond inventory, reserved pieces, quick actions, and special repair items',()=>{
 const {s,b}=fight(),t=consumable(s),item=M.issue(s,'1',t.id,3)[0];assert.throws(()=>B.useItem(s,b,b.current.id,item.id,minRng,null,null,2),/快速行动/);b.current.quick=3;const o=M.createOffer(s,'1','3');M.updateOffer(s,o.id,'1',[{id:item.id,quantity:2}],0);assert.throws(()=>B.useItem(s,b,b.current.id,item.id,minRng,null,null,2),/预留/);assert.equal(s.players['1'].inventory[item.id].quantity,3);assert.equal(b.current.quick,3);assert.throws(()=>M.consumeMany(s.players['1'],item.id,101),/数量/);
});
test('bulk-use quantity page keeps original expiry and transitions into one stable direct/RP draft',async()=>{
 const {s,b}=fight(),t=consumable(s),item=M.issue(s,'1',t.id,3)[0];b.current.quick=3;const h=runtime(s),rpg=createRpg(h.deps);await rpg.start();try{const i=h.interaction('1','使用',{物品:item.id,数量:2});await rpg.handle(i);assert.ok(controls(i.result).some(c=>c.label==='修改数量'));const f=Object.values(rpg.store.snapshot(s.guildId).forms).find(f=>f.kind==='bulkUse'),deadline=f.expiresAt;const j=h.interaction('1',null,{},click(i.result,'继续 / 填写 RP'));await rpg.handle(j);assert.ok(controls(j.result).some(c=>c.label==='RP 并行动'));const action=Object.values(rpg.store.snapshot(s.guildId).forms).find(f=>f.kind==='battleAction');assert.equal(action.params.quantity,2);assert.equal(action.expiresAt,deadline);const result=h.interaction('1',null,{},click(j.result,'直接执行'));await rpg.handle(result);assert.match(result.result.content,/已保存/);assert.equal(rpg.store.snapshot(s.guildId).players['1'].inventory[item.id].quantity,1);}finally{rpg.stop();await rpg.drain();}
});
test('bulk draft version change invalidates an earlier action confirmation',()=>{
 const {s,b}=fight(),t=consumable(s),item=M.issue(s,'1',t.id,3)[0];b.current.quick=3;const source={id:'source',kind:'bulkUse',owner:'1',quantity:2,version:0,status:'ready',expiresAt:Date.now()+100000};s.forms.source=source;const data={battleId:b.id,actorId:b.actors[0].id,turnId:b.current.id,action:'item',params:{itemId:item.id,quantity:2},sourceFormId:'source',expiresAt:source.expiresAt},f=Draft.create(s,'1',data);assert.equal(Draft.create(s,'1',data).id,f.id);source.version++;source.quantity=3;assert.throws(()=>Draft.execute(s,f.id,'1'),/失效/);assert.equal(s.players['1'].inventory[item.id].quantity,3);
});
test('merchant random stock is frozen once, excludes junk by default and is not regenerated by map refresh or restart',()=>{
 const {s,m,node,pool}=merchant(state(),{sellMode:'random',buyMode:'random',sellCategories:['consumable'],buyCategories:['weapon'],sellCount:3,buyCount:2});assert.ok(node.stock.every(e=>C.CONSUMABLES.includes(e.template.kind)||e.template.kind==='修复道具'));assert.ok(node.wanted.every(id=>s.catalog[id].kind==='武器'));const before=C.clone(node);m.status='draft';X.generate(s,m,minRng);assert.deepEqual(m.cells['2,0'].room.merchant,before);assert.deepEqual(C.clone(s).explorations[m.id].cells['2,0'].room.merchant,before);assert.throws(()=>require('../src/rpg/random-layout').build(m),/行商/);
});
test('GM explicitly selecting junk makes a separate merchant category, without changing ordinary grants',()=>{
 const {s,node}=merchant(state(),{sellMode:'random',sellCategories:['junk'],buyCategories:['junk'],sellCount:20});assert.ok(node.stock.length===20&&node.stock.every(e=>e.template.kind==='杂物'));assert.ok(V.buyable(node,M.makeItem(s.catalog.seed_0_gold)));assert.ok(!V.buyable(node,M.makeItem(weapon(s))));
});
test('merchant purchase at 100 percent and buyback at 110 percent change balance/inventory/stock/quota atomically',()=>{
 const {s,m,node,t}=merchant(),q=V.quote(s,'1',m.id,'2,0','purchase',node.stock[0].id,2);const r=V.execute(s,'1',q.id);assert.equal(r.total,20);assert.equal(s.players['1'].balance,980);assert.equal(node.stock[0].remaining,8);const item=Object.values(s.players['1'].inventory).find(i=>i.templateId===t.id),sell=V.quote(s,'1',m.id,'2,0','sell',item.id,2);assert.equal(sell.total,22);V.execute(s,'1',sell.id);assert.equal(s.players['1'].balance,1002);assert.equal(node.buyRemaining,8);assert.equal(s.players['1'].inventory[item.id],undefined);assert.equal(Object.keys(s.merchantTrades).length,2);assert.deepEqual(V.execute(s,'1',q.id),r);assert.equal(V.price(11,true),12);
});
test('merchant insufficient funds or overweight batch rejects all staged goods and does not decrement shared stock',()=>{
 const {s,m,node}=merchant();s.players['1'].balance=0;const q=V.quote(s,'1',m.id,'2,0','purchase',node.stock[0].id,2),before=C.clone(s.players);assert.throws(()=>V.execute(s,'1',q.id),/余额/);assert.deepEqual(s.players,before);assert.equal(node.stock[0].remaining,10);s.players['1'].balance=1000;node.stock[0].template.weight=1000000;assert.throws(()=>V.execute(s,'1',q.id),/超重/);assert.equal(s.players['1'].balance,1000);assert.equal(Object.keys(s.players['1'].inventory).length,0);assert.equal(node.stock[0].remaining,10);assert.equal(q.status,'ready');
});
test('merchant reservations/equipment and changed quantity/character/cell/pause/downed state prevent unsafe trade',()=>{
 const {s,m,node,t}=merchant(),item=M.issue(s,'1',t.id,3)[0],o=M.createOffer(s,'1','2');M.updateOffer(s,o.id,'1',[{id:item.id,quantity:3}],0);assert.throws(()=>V.quote(s,'1',m.id,'2,0','sell',item.id),/预留/);o.status='cancelled';const q=V.quote(s,'1',m.id,'2,0','sell',item.id,2);s.players['1'].inventory[item.id].snapshot.value++;assert.throws(()=>V.execute(s,'1',q.id),/变化/);const buy=V.quote(s,'1',m.id,'2,0','purchase',node.stock[0].id);m.participants['1'].cell='1,0';assert.throws(()=>V.execute(s,'1',buy.id),/身处/);m.participants['1'].cell='2,0';m.status='paused';assert.throws(()=>V.execute(s,'1',buy.id),/暂停/);m.status='active';H.damage(s.players['1'],999);assert.throws(()=>V.execute(s,'1',buy.id),/参加|倒地/);
});
test('only GM manual restock increases stock/quota; old quotes become invalid and templates never change assigned goods',()=>{
 const {s,m,node,pool,t}=merchant(),q=V.quote(s,'1',m.id,'2,0','purchase',node.stock[0].id);V.restock(s,m.id,'2,0',t.id,2,3);assert.equal(node.stock[0].remaining,12);assert.equal(node.buyRemaining,13);assert.throws(()=>V.execute(s,'1',q.id),/货单/);V.publish(s,{...pool,name:'新版'},pool.id,pool.version);assert.equal(node.name,'流浪商人');assert.throws(()=>V.assign(s,m,'2,0',pool.id),/暂停/);m.status='paused';assert.throws(()=>V.assign(s,m,'2,0',pool.id),/进入/);assert.throws(()=>V.clear(s,m,'2,0'),/未进入/);
});
test('50 duplicate merchant requests execute once, two characters cannot buy the same final item or exceed a shared buy quota',async()=>{
 const {s,m,node}=merchant();node.stock[0].remaining=1;const qa=V.quote(s,'1',m.id,'2,0','purchase',node.stock[0].id),qb=V.quote(s,'2',m.id,'2,0','purchase',node.stock[0].id),h=runtime(s),st=createStore(h.deps);await st.load(s.guildId);let calls=0;const results=await Promise.allSettled(Array.from({length:50},(_,n)=>st.transact(s.guildId,'merchant:'+qa.id,'1',s=>{calls++;return V.execute(s,'1',qa.id);})));assert.ok(results.every(r=>r.status==='fulfilled'));assert.equal(calls,1);await assert.rejects(st.transact(s.guildId,'merchant:'+qb.id,'2',s=>V.execute(s,'2',qb.id)),/货单|库存/);const restored=createStore(h.deps);await restored.load(s.guildId);assert.equal(Object.keys(restored.snapshot(s.guildId).merchantTrades).length,1);assert.equal(restored.snapshot(s.guildId).players['1'].balance,990);assert.equal(restored.snapshot(s.guildId).players['2'].balance,1000);
});
test('GM merchant native modal, multi-category editor, preview and publish obey permissions and component limits',async()=>{
 const h=runtime(state()),rpg=createRpg(h.deps);await rpg.start();try{const denied=h.interaction('1','gm',{sub:'行商'});await rpg.handle(denied);assert.match(denied.result.content,/GM/);const home=h.interaction('GM','gm',{sub:'行商'});await rpg.handle(home);const open=h.interaction('GM',null,{},click(home.result,'新建行商模板'));await rpg.handle(open);assert.ok(open.modal);const submit=h.interaction('GM',null,{},open.modal.toJSON().custom_id,[],{name:'游商',description:'@everyone 商品'});await rpg.handle(submit);valid(submit.result);assert.equal(controls(submit.result).filter(c=>c.options).length,4);const preview=h.interaction('GM',null,{},click(submit.result,'预览发布'));await rpg.handle(preview);const done=h.interaction('GM',null,{},click(preview.result,'确认发布'));await rpg.handle(done);assert.equal(Object.values(rpg.store.snapshot(C.DEFAULT_GUILD_ID).merchantTemplates)[0].name,'游商');}finally{rpg.stop();await rpg.drain();}
});
test('merchant player modal commits once at the displayed quantity, stale modal is refused, and public fog hides the node',async()=>{
 const {s,m,node}=merchant(),h=runtime(s),rpg=createRpg(h.deps);await rpg.start();try{const i=h.interaction('1','行商');await rpg.handle(i);valid(i.result);const select=controls(i.result).find(c=>c.placeholder==='选择行商出售货品'),choose=h.interaction('1',null,{},select.custom_id,[node.stock[0].id]);await rpg.handle(choose);const quantity=h.interaction('1',null,{},click(choose.result,'修改件数'));await rpg.handle(quantity);const update=h.interaction('1',null,{},quantity.modal.toJSON().custom_id,[],{quantity:'2'});await rpg.handle(update);assert.match(update.result.embeds[0].data.description,/×2/);const stale=h.interaction('1',null,{},click(choose.result,'确认交易'));await rpg.handle(stale);assert.match(stale.result.content,/失效/);const fresh=h.interaction('1','行商');await rpg.handle(fresh);const q=Object.values(rpg.store.snapshot(s.guildId).forms).find(f=>f.kind==='merchantTrade');const commit=h.interaction('1',null,{},'rpg:merchant:commit:'+q.id+':'+q.version);await rpg.handle(commit);assert.match(commit.result.content,/购买[\s\S]*×2/);assert.equal(rpg.store.snapshot(s.guildId).players['1'].balance,980);}finally{rpg.stop();await rpg.drain();}delete m.revealed['2,0'];const svg=require('../src/rpg/map-image').explorationSVG(m);assert.doesNotMatch(svg,/流浪商人|>商</);
});
test('20 separate player text results finish while all static rendering and public notifications are blocked',async()=>{
 const seed=state();for(let n=0;n<20;n++){const uid='load-'+n,p=M.newCharacter('负载'+n,{strength:5,constitution:5,mind:5,appearance:5,intelligence:5,agility:5,knowledge:5},1);p.userId=uid;seed.players[uid]=p;const b=B.createBattle(seed,'load-'+n,'GM','负载');B.join(seed,b,uid);B.start(seed,b,null,minRng);Draft.create(seed,uid,{battleId:b.id,actorId:b.current.actorId,turnId:b.current.id,action:'move',params:{x:26,y:25}});}
 const h=runtime(seed);for(let n=0;n<20;n++){const uid='load-'+n;h.members[uid]={...h.members['1'],id:uid,user:{id:uid}};}let release;const gate=new Promise(r=>release=r),samples={};h.deps.renderer={decorate:async(_,v)=>{await gate;return v;},close(){}};h.ch.send=async()=>{await gate;return {id:'blocked'};};h.deps.metrics={observe:(k,v)=>(samples[k]||=[]).push(v),start:k=>{const at=performance.now();return()=>h.deps.metrics.observe(k,performance.now()-at);},gauge(){},close(){}};const rpg=createRpg(h.deps);await rpg.start();try{const fs=Object.values(rpg.store.snapshot(seed.guildId).forms).filter(f=>f.kind==='battleAction');await Promise.all(fs.map(f=>rpg.handle(h.interaction(f.owner,null,{},'rpg:act:do:'+f.id))));const p95=k=>samples[k].sort((a,b)=>a-b)[Math.ceil(samples[k].length*.95)-1];assert.ok(p95('interaction.ack')<1000);assert.ok(p95('interaction.result')<3000);console.log(JSON.stringify({test:'local-text-static-and-public-blocked',clicks:20,ackP95Ms:Math.round(p95('interaction.ack')),resultP95Ms:Math.round(p95('interaction.result'))}));assert.ok(fs.every(f=>rpg.store.snapshot(seed.guildId).forms[f.id].status==='done'));}finally{release();rpg.stop();await rpg.drain();}
});


test('GM assignment preview freezes one node and manual restock confirmation adds exact stock without reroll',async()=>{
 const {s,m,pool,node,t}=merchant();m.status='paused';m.participants={};m.cells['2,0'].touched=false;const h=runtime(s),rpg=createRpg(h.deps);await rpg.start();try{
  const assign=h.interaction('GM',null,{},'rpg:merchant:assignpick:'+m.id+':'+pool.id,['2,0']);await rpg.handle(assign);valid(assign.result);const draft=Object.values(rpg.store.snapshot(s.guildId).forms).find(f=>f.kind==='merchantAssign'),frozen=C.clone(draft.node);const commit=h.interaction('GM',null,{},click(assign.result,'确认保存'));await rpg.handle(commit);assert.match(commit.result.embeds[0].data.title,/保存/);assert.deepEqual(rpg.store.snapshot(s.guildId).explorations[m.id].cells['2,0'].room.merchant,frozen);
  const pick=h.interaction('GM',null,{},'rpg:merchant:restockpick:'+m.id+':_',['2,0']);await rpg.handle(pick);valid(pick.result);const form=Object.values(rpg.store.snapshot(s.guildId).forms).find(f=>f.kind==='merchantRestockSelect'),open=h.interaction('GM',null,{},'rpg:merchant:restockitem:'+form.id,[t.id]);await rpg.handle(open);assert.ok(open.modal);const submit=h.interaction('GM',null,{},open.modal.toJSON().custom_id,[],{quantity:'2',quota:'3'});await rpg.handle(submit);valid(submit.result);const done=h.interaction('GM',null,{},click(submit.result,'确认保存'));await rpg.handle(done);const n=rpg.store.snapshot(s.guildId).explorations[m.id].cells['2,0'].room.merchant;assert.equal(n.stock[0].remaining,12);assert.equal(n.buyRemaining,13);assert.equal(n.id,frozen.id);
 }finally{rpg.stop();await rpg.drain();}
});
test('shared merchant buy quota permits only available pieces while independent valid stock quotes remain usable',()=>{
 const {s,m,node,t}=merchant();node.buyRemaining=3;const a=M.issue(s,'1',t.id,2)[0],b=M.issue(s,'2',t.id,2)[0],qa=V.quote(s,'1',m.id,'2,0','sell',a.id,2),qb=V.quote(s,'2',m.id,'2,0','sell',b.id,2);V.execute(s,'1',qa.id);assert.throws(()=>V.execute(s,'2',qb.id),/额度/);assert.equal(s.players['2'].balance,1000);assert.equal(s.players['2'].inventory[b.id].quantity,2);const x=V.quote(s,'1',m.id,'2,0','purchase',node.stock[0].id),y=V.quote(s,'2',m.id,'2,0','purchase',node.stock[0].id);V.execute(s,'1',x.id);V.execute(s,'2',y.id);assert.equal(node.stock[0].remaining,8);
});
