'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../src/rpg/constants'),B=require('../src/rpg/combat'),H=require('../src/rpg/health'),DT=require('../src/rpg/mortality');
const {fight}=require('./helpers/rpg-harness'),Sections=require('../src/web/game-sections'),P=require('../src/web/game-service');
function fixture(){const {s,b}=fight();s.platform='web';const enemy={id:'foe',name:'敌方',team:'enemy',character:C.clone(s.players['3']),retreated:false};delete enemy.character.userId;delete enemy.character.life;b.actors.push(enemy);return {s,b,enemy};}
test('website last enemy death ends before another paid opportunity and only once',()=>{const {s,b,enemy}=fixture(),before=C.clone(s),count=C.clone(b.actionRound.counts),xp=s.players['1'].xp;H.damage(enemy.character,999);DT.settle(s,b,enemy,b.actors[0].id);DT.reconcile(s,before);assert.equal(b.status,'ended');assert.equal(b.outcome,'victory');assert.equal(b.current,null);assert.deepEqual(b.actionRound.counts,count);assert.equal(s.players['1'].xp,xp);const history=b.history.length;DT.reconcile(s,C.clone(s));assert.equal(b.history.length,history);assert.equal(Object.keys(s.deaths).length,1);});
test('pending saved attacks delay terminal result; manual pause and empty practice remain controlled',()=>{const {s,b,enemy}=fixture();enemy.retreated=true;b.pending={id:'saved-hit'};assert.equal(B.autoEnd(s,b),false);b.pending=null;b.status='paused';assert.equal(B.autoEnd(s,b),false);b.status='active';assert.equal(B.autoEnd(s,b),true);const practice=fight();practice.s.platform='web';assert.equal(B.autoEnd(practice.s,practice.b),false);});
test('all downed allies retain rescue judgment instead of being marked defeated or silently ending',()=>{const {s,b,enemy}=fixture();for(const a of b.actors.filter(a=>a.userId))H.damage(s.players[a.userId],999);enemy.retreated=true;assert.equal(B.autoEnd(s,b),false);assert.equal(b.status,'paused');assert.equal(b.judgment.status,'pending');assert.equal(b.outcome,undefined);});
test('all allied retreats defeat; downed opposing players are alive and cannot award victory',()=>{const {s,b}=fixture();for(const a of b.actors.filter(a=>a.team==='ally'))a.retreated=true;assert.equal(B.autoEnd(s,b),true);assert.equal(b.outcome,'defeat');const f=fight();f.s.platform='web';f.b.actors[1].team='enemy';H.damage(f.s.players['2'],999);assert.equal(B.autoEnd(f.s,f.b),false);assert.equal(f.b.status,'active');});
test('automatic endings are website scoped and do not change Discord practice opportunity rules',()=>{const {s,b,enemy}=fixture();delete s.platform;enemy.retreated=true;b.current=null;B.nextOpportunity(s,b,min=>min);assert.equal(b.status,'active');});
test('opposing-side eligibility survives GM removal, while initially empty practice remains manual',()=>{
  const {s,b,enemy}=fixture(),before=C.clone(s);b.status='paused';b.actors=b.actors.filter(a=>a!==enemy);DT.reconcile(s,before);assert.equal(b.autoEndEligible,true);B.pause(b,true);B.nextOpportunity(s,b);assert.equal(b.outcome,'victory');
  const f=fight();f.s.platform='web';const practice=B.createBattle(f.s,'practice-channel','GM','练习');practice.actors=C.clone(f.b.actors);B.start(f.s,practice,null,min=>min);assert.equal(practice.autoEndEligible,false);practice.actors.push({...C.clone(enemy),retreated:true});assert.equal(B.autoEnd(f.s,practice),false);
});
test('completed manual room batches advance once and preserve the next GM encounter entry',()=>{
  for(const remaining of [[],[{quantity:2}]]){const {s,b,enemy}=fixture();enemy.retreated=true;b.exploration={mapId:'m',cell:'0,0'};
    const room={snapshot:{autoStart:false},encounter:'battle',battleId:b.id,remainingNpcs:remaining};s.explorations.m={id:'m',status:'active',version:1,cells:{'0,0':{room}},participants:{},rps:{}};
    DT.reconcile(s,C.clone(s));assert.equal(b.outcome,'victory');assert.equal(room.encounter,remaining.length?'pending':'resolved');assert.equal(Object.keys(s.battles).length,1);const version=s.explorations.m.version;DT.reconcile(s,C.clone(s));assert.equal(s.explorations.m.version,version);
  }
});
test('automatic room waves reuse saved layout; BOSS subsequent wave waits for a fresh approval',()=>{
  const F=require('../src/rpg/forms'),X=require('../src/rpg/exploration'),Boss=require('../src/rpg/boss'),Team=require('../src/rpg/team-movement'),{state}=require('./helpers/rpg-harness');
  for(const boss of [false,true]){
    const s=state();s.platform='web';let seq=0;const rng=(lo,hi)=>lo+(seq++%(hi-lo));
    const cf=F.create(s,'GM','mapcategory');cf.data.name='验收';const cat=F.publish(s,cf),t=B.validateNPC(s,{...F.defaults('npc'),name:'守卫',hpMax:1});t.id='guard';t.published=true;t.version=1;s.npcTemplates[t.id]=t;
    const rf=F.create(s,'GM','room');Object.assign(rf.data,{name:'机房',categoryIds:[cat.id],npcIds:[t.id],autoStart:true});F.publish(s,rf);
    s.config.rpChannelId='hidden';const m=X.create(s,'GM','channel','分批',1,3,'random',cat.id);X.generate(s,m,rng);
    if(boss){const pool=Boss.publish(s,{name:'BOSS',entries:[{ref:t.id,quantity:19}]});Boss.assign(s,m,'2,0',pool.id,rng);}
    X.publish(s,m);for(const uid of ['1','2']){X.join(s,m,uid);m.participants[uid].cell='2,0';}m.revealed['2,0']=true;
    const r=m.cells['2,0'].room;if(!boss)r.remainingNpcs[0].quantity=19;
    let b;if(boss){Boss.reconcile(s);b=Boss.confirm(s,m.id,'2,0',r.bossRequest.id,1,rng);}else{Team.autoEncounters(s);b=s.battles[r.battleId];}
    const layout=C.clone(r.tacticalLayout);for(const a of b.actors.filter(a=>a.team==='enemy'))a.retreated=true;
    DT.reconcile(s,C.clone(s));assert.equal(b.outcome,'victory');assert.deepEqual(r.tacticalLayout,layout);
    if(boss){assert.equal(r.encounter,'pending');assert.equal(r.bossRequest.status,'pending');assert.equal(Object.keys(s.battles).length,1);}else{assert.equal(r.encounter,'battle');assert.notEqual(r.battleId,b.id);assert.equal(Object.keys(s.battles).length,2);}
  }
});
test('section projections do not evaluate unrelated large history and changes ignore outbox receipts',()=>{const {s}=fixture();const before=C.clone(s);(s.deliveryJobs||={}).x={status:'done'};s.receipts.x={at:Date.now()};assert.deepEqual(Sections.changed(before,s),[]);s.players['1'].balance++;assert.ok(Sections.changed(before,s).includes('core'));assert.throws(()=>Sections.parse('secret'),/分区/);assert.deepEqual(Sections.parse('core,core,battle'),['core','battle']);Object.defineProperty(s,'forms',{get(){throw Error('history must not be read');}});const value=P.playerView(s,'1',{fields:Sections.fields(['core'])});assert.equal(value.player.userId,'1');assert.equal(value.actionHistory,undefined);});
test('partial refreshes merge only newer sections and a single read runs at once',async()=>{const {mergeGame,refreshQueue}=await import('../web/src/refresh-state.js');const current={revision:8,sectionVersions:{core:8,battle:7},player:{name:'new'},battles:[{id:'a'}],versions:{'players:1':'new'}};const value=mergeGame(current,{revision:6,sections:['core'],sectionVersions:{core:6},player:{name:'old'},versions:{'players:1':'old'}});assert.equal(value.player.name,'new');let count=0,maximum=0,release,reads=[];const q=refreshQueue(async keys=>{maximum=Math.max(maximum,++count);await new Promise(r=>release=r);count--;return keys;},r=>reads.push(r));const a=q(['battle']);await new Promise(r=>setImmediate(r));const b=q(['core']);q(['bag']);release();await new Promise(r=>setImmediate(r));release();await Promise.all([a,b]);assert.equal(maximum,1);assert.deepEqual(reads,[['battle'],['core','bag']]);});
test('unread and read events only change channel state and pending task navigation is read-only',async()=>{const {unreadEvent,markRead}=await import('../web/src/refresh-state.js'),{chatTasks}=await import('../web/src/chat-tasks.js');const rooms=[{id:'a',sequence:4,unread:2},{id:'b',sequence:1,unread:0}];const next=unreadEvent(rooms,{roomId:'a',sequence:5});assert.equal(next[0].unread,3);assert.equal(next[1],rooms[1]);assert.equal(markRead(next,'a',5)[0].unread,0);const tasks=chatTasks({battles:[{id:'b',name:'战斗',status:'active',pending:[{id:'hit'}],actors:[{id:'p',userId:'1'}],current:{actorId:'p'}}],maps:[],offers:[],corpses:[]},'1');assert.equal(tasks.length,2);assert.equal(tasks[0].system.hitId,'hit');});
test('channel listing reuses one current membership and never opens restricted channels',async()=>{const repo=require('./helpers/web-demo.cjs').memoryRepository();await repo.put('room',{id:'a',groupId:'g',kind:'chat'},{scope:'g'});await repo.put('room',{id:'b',groupId:'g',kind:'gm'},{scope:'g'});let checks=0;const accounts={member:async()=>{checks++;return {user:{id:'u'},group:{id:'g'},role:'player'};},gm:a=>assert.ok(a.role==='gm')};const chat=require('../src/web/chat').createChat(repo,accounts);assert.deepEqual((await chat.rooms('g','u')).map(r=>r.id),['a']);assert.equal(checks,1);});
test('late unread and read responses cannot restore counts that have already been read',async()=>{const {unreadEvent,markRead}=await import('../web/src/refresh-state.js');let rooms=[{id:'a',sequence:10,readSequence:5,unread:5}];rooms=unreadEvent(rooms,{roomId:'a',sequence:8});assert.equal(rooms[0].unread,5);rooms=markRead(rooms,'a',10);rooms=markRead(rooms,'a',7);assert.equal(rooms[0].unread,0);assert.equal(rooms[0].readSequence,10);});
