'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
const MAX=2*1024*1024;
function dpapi(bytes,decode=false){return new Promise((resolve,reject)=>{const command=`Add-Type -AssemblyName System.Security; $taskBytes=[Convert]::FromBase64String([Console]::ReadLine()); $taskResult=[Security.Cryptography.ProtectedData]::${decode?'Unprotect':'Protect'}($taskBytes,$null,[Security.Cryptography.DataProtectionScope]::CurrentUser); [Console]::Write([Convert]::ToBase64String($taskResult))`;
 const proc=spawn('powershell.exe',['-NoProfile','-NonInteractive','-Command',command],{windowsHide:true,stdio:['pipe','pipe','pipe']});let output='';proc.stdout.on('data',b=>output+=b.toString());proc.stderr.on('data',()=>{});proc.on('error',()=>reject(Error('无法访问Windows凭证保护，请检查PowerShell。')));proc.on('exit',c=>c?reject(Error('Windows凭证保护失败。')):resolve(Buffer.from(output.trim(),'base64')));proc.stdin.end(bytes.toString('base64')+'\n');});}
function createLocal({directory=path.join(process.env.LOCALAPPDATA||process.cwd(),'DiscordRpgGM'),remoteUrl,staticDir=path.join(__dirname,'../dist'),protect=dpapi,fetcher=fetch,port=47831,allowTestHttp=false}={}){
 fs.mkdirSync(directory,{recursive:true});let localWrites=Promise.resolve();let credentials,server,origin,nonce=crypto.randomBytes(24).toString('hex'),session=crypto.randomBytes(32).toString('hex'),csrf=crypto.randomBytes(24).toString('hex'),reopenKey=crypto.randomBytes(24).toString('hex');const vault=path.join(directory,'credential.bin'),drafts=path.join(directory,'drafts.bin'),pendingVault=path.join(directory,'pending-binding.bin');
 function remote(value){const u=new URL(value);if(u.protocol!=='https:'&&!(allowTestHttp&&['127.0.0.1','localhost'].includes(u.hostname)))throw Error('服务地址必须使用HTTPS。');if(u.username||u.password||u.search||u.hash||u.pathname!=='/')throw Error('请输入服务根地址。');return u.origin;}
 async function save(file,value){const b=await protect(Buffer.from(JSON.stringify(value)));fs.writeFileSync(file+'.tmp',b,{mode:0o600});fs.renameSync(file+'.tmp',file);}
 async function load(file){try{return JSON.parse((await protect(fs.readFileSync(file),true)).toString('utf8'));}catch{return null;}}
 async function initialize(){credentials=await load(vault);if(credentials)remoteUrl=credentials.remote;else if(remoteUrl)remoteUrl=remote(remoteUrl);}
 const respond=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data));};
 async function read(req,limit=MAX){let length=0;const chunks=[];for await(const b of req){length+=b.length;if(length>limit)throw Error('内容超过大小限制。');chunks.push(b);}return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}',(k,v)=>{if(['__proto__','constructor','prototype'].includes(k))throw Error('字段无效。');return v;});}
 function headers(){if(!credentials)throw Error('请先绑定。');return {'content-type':'application/json',authorization:'Bearer '+credentials.guildId+'.'+credentials.deviceId+'.'+credentials.secret};}
 async function route(req,res){const host=req.headers.host;if(host!==new URL(origin).host)return respond(res,403,{error:{message:'访问来源无效。'}});const u=new URL(req.url,origin),cookie=req.headers.cookie||'';
  if(u.pathname==='/local/reopen'&&u.searchParams.get('key')===reopenKey){nonce=crypto.randomBytes(24).toString('hex');res.writeHead(302,{location:'/start?nonce='+nonce,'cache-control':'no-store'});return res.end();}
  if(u.pathname==='/start'&&nonce&&u.searchParams.get('nonce')===nonce){nonce=null;res.writeHead(302,{'set-cookie':'gm_local='+session+'; HttpOnly; SameSite=Strict; Path=/','location':'/','cache-control':'no-store'});return res.end();}
  if(!cookie.split(';').some(c=>c.trim()==='gm_local='+session))return respond(res,401,{error:{message:'请从本地启动入口打开工作台。'}});
  const incoming=req.headers.origin;if(incoming&&incoming!==origin)return respond(res,403,{error:{message:'访问来源无效。'}});
  try{if(req.method!=='GET'&&(incoming!==origin||req.headers['x-gm-csrf']!==csrf))throw Error('请求校验失败，请重新打开工作台。');
   if(u.pathname==='/local/status')return respond(res,200,{data:{csrf,bound:!!credentials,remote:remoteUrl||'',deviceId:credentials?.deviceId}});
   if(req.method==='POST'&&u.pathname==='/local/pair'){const p=await read(req),target=remote(p.url||remoteUrl),bindingHash=crypto.createHash('sha256').update(target+':'+p.code).digest('hex');let candidate=await load(pendingVault);if(candidate?.bindingHash!==bindingHash){candidate={bindingHash,deviceId:crypto.randomUUID(),secret:crypto.randomBytes(32).toString('hex')};await save(pendingVault,candidate);}const {deviceId,secret}=candidate;const r=await fetcher(target+'/api/gm/v1/pair',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:p.code,deviceId,credentialHash:crypto.createHash('sha256').update(secret).digest('hex'),deviceName:p.name||require('node:os').hostname()}),redirect:'error',signal:AbortSignal.timeout(15000)});const result=await r.json();if(!r.ok)return respond(res,r.status,result);credentials={...result.data,deviceId,secret,remote:target};remoteUrl=target;await save(vault,credentials);if(fs.existsSync(pendingVault))fs.unlinkSync(pendingVault);return respond(res,200,{data:{bound:true,guildName:credentials.guildName}});}
   if(req.method==='POST'&&u.pathname==='/local/logout'){credentials=null;if(fs.existsSync(vault))fs.unlinkSync(vault);return respond(res,200,{data:{bound:false}});}
   if(u.pathname==='/local/drafts'){if(req.method==='GET')return respond(res,200,{data:await load(drafts)||{}});const p=await read(req);await save(drafts,p);return respond(res,200,{data:{saved:true}});}
   if(req.method==='POST'&&u.pathname==='/local/stop'){respond(res,200,{data:{stopped:true}});setTimeout(()=>server.close(),100);return;}
   if(u.pathname.startsWith('/api/gm/v1/')){if(!['GET','POST'].includes(req.method))throw Error('请求方法无效。');const data=req.method==='POST'?await read(req,u.pathname.endsWith('/portraits')?6*1024*1024:MAX):undefined,r=await fetcher(remoteUrl+u.pathname+u.search,{method:req.method,headers:headers(),body:data===undefined?undefined:JSON.stringify(data),redirect:'error',signal:AbortSignal.timeout(30000)});res.writeHead(r.status,{'content-type':r.headers.get('content-type')||'application/json','cache-control':'no-store','x-content-type-options':'nosniff'});return res.end(Buffer.from(await r.arrayBuffer()));}
   if(req.method!=='GET')throw Error('接口不存在。');const filename=path.resolve(staticDir,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(!filename.startsWith(path.resolve(staticDir)+path.sep))throw Error('路径无效。');const bytes=fs.readFileSync(filename);res.writeHead(200,{'content-type':({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.svg':'image/svg+xml'})[path.extname(filename)]||'application/octet-stream','content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",'x-content-type-options':'nosniff','cache-control':'no-cache'});res.end(bytes);
  }catch(e){respond(res,422,{error:{message:/timeout|abort/i.test(e.message)?'请求超时，请查询操作结果；原输入仍保留。':e.message}});}
 }
 async function start(){await initialize();server=http.createServer((req,res)=>{const call=()=>route(req,res);const job=req.method==='POST'&&req.url.startsWith('/local/')?(localWrites=localWrites.catch(()=>{}).then(call)):call();job.catch(()=>respond(res,500,{error:{message:'本地服务异常，请重新打开。'}}));});server.requestTimeout=40000;server.headersTimeout=10000;await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve);});origin='http://127.0.0.1:'+server.address().port;return {url:origin+'/start?nonce='+nonce,origin,reopenKey};}
 return {start,stop:()=>new Promise(resolve=>{server.closeIdleConnections();server.close(resolve);}),route,get server(){return server;}};
}
function openBrowser(url){const proc=spawn('powershell.exe',['-NoProfile','-NonInteractive','-Command','Start-Process -FilePath $env:GM_LAUNCH_URL'],{windowsHide:true,stdio:'ignore',env:{...process.env,GM_LAUNCH_URL:url}});proc.on('error',()=>{});}
if(require.main===module){let config={};try{config=JSON.parse(fs.readFileSync(path.join(__dirname,'../connection.json'),'utf8'));}catch{}const directory=path.join(process.env.LOCALAPPDATA,'DiscordRpgGM'),launch=path.join(directory,'launch.json'),app=createLocal({remoteUrl:config.url,port:Number(process.env.GM_LOCAL_PORT||47831)});app.start().then(({url,origin,reopenKey})=>{fs.writeFileSync(launch,JSON.stringify({origin,reopenKey,pid:process.pid}));openBrowser(url);}).catch(async e=>{if(e.code==='EADDRINUSE'){try{const saved=JSON.parse(fs.readFileSync(launch)),u=new URL(saved.origin);if(u.hostname!=='127.0.0.1'||u.port!==String(process.env.GM_LOCAL_PORT||47831)||!/^[a-f0-9]{48}$/.test(saved.reopenKey))throw Error('入口无效');openBrowser(saved.origin+'/local/reopen?key='+saved.reopenKey);return;}catch{}}fs.mkdirSync(directory,{recursive:true});fs.writeFileSync(path.join(directory,'startup-error.txt'),e.message);process.exitCode=1;});}
module.exports={createLocal,dpapi};
