export const kindNames={item:'物品',skill:'战斗技能',checkskill:'鉴定技能',trait:'词条',condition:'异常',npc:'NPC',mapcategory:'地图分类',room:'房间',rolepanel:'身份组领取面板',coupon:'兑换池',boss:'BOSS池',merchant:'行商',glossary:'名词'};
export const labels={name:'名称',description:'说明',ref:'模板',quantity:'数量',target:'效果目标',op:'运算',value:'数值',id:'编号',version:'版本',physical:'物理',magical:'魔法',mental:'精神',attributes:'属性',str:'力量',agi:'敏捷',con:'体质',int:'智力',per:'感知',wil:'意志',hp:'正常HP',hpMax:'生命上限',reserveHP:'倒地HP',state:'状态',effects:'效果',damage:'伤害骰',heal:'治疗骰',duration:'持续时间',kind:'类型',count:'次数',mode:'模式',action:'行动类型',abilityKey:'武器／技能',targetId:'目标',itemId:'物品',ammoId:'弹药',weaponId:'武器',magazineId:'弹夹',recipientId:'治疗目标',choice:'防守选择',hitId:'受击编号',type:'类型',hand:'主副手',x:'横坐标',y:'纵坐标',radius:'半径',allowAlly:'允许友军',allowSelf:'允许自身',level:'等级',enabled:'启用',weight:'重量',weightKg:'重量（kg）',rangeMeters:'距离（米）',firing:'射击模式',startsAt:'北京时间',rule:'鉴定规则',threshold:'门槛',attribute:'属性',maxAttempts:'尝试次数',skillId:'鉴定技能',weights:'行动权重',strategy:'策略',normal:'普通',quick:'快速',formal:'正式',until:'直到解除',round:'行动轮',templateId:'模板编号',column:'列',row:'行',rarity:'稀有度'};
let csrf='',transport;export function setCsrf(v){csrf=v;}export function setTransport(fn){transport=fn;}
export async function api(path,body){if(transport)return transport(path,body);const r=await fetch(path.startsWith('/local/')?path:'/api/gm/v1'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'content-type':'application/json','x-gm-csrf':csrf},body:body===undefined?undefined:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw Object.assign(Error(result.error?.message||'请求失败，原输入已保留。'),{code:result.error?.code,details:result.error?.details});return result.data;}
export function get(o,path){return path.split('.').reduce((v,k)=>v?.[k],o);}
export function set(o,path,value){if(path.split('.').some(k=>['__proto__','constructor','prototype'].includes(k)))throw Error('字段名称无效。');const copy=structuredClone(o),keys=path.split('.');let next=copy;for(const k of keys.slice(0,-1))next=next[k]??={};next[keys.at(-1)]=value;return copy;}
export function csvParse(text){const separator=text.includes('\t')?'\t':',',rows=[];let row=[],cell='',quoted=false;for(let n=0;n<text.length;n++){const c=text[n];if(c==='"'){if(quoted&&text[n+1]==='"'){cell+='"';n++;}else quoted=!quoted;}else if(!quoted&&c===separator){row.push(cell);cell='';}else if(!quoted&&(c==='\n'||c==='\r')){if(c==='\r'&&text[n+1]==='\n')n++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('表格引号未闭合。');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows;}
export function parseImport(text,kind){text=text.trim().replace(/^\uFEFF/,'');if(!text)throw Error('请粘贴表格或选择文件。');if(text.startsWith('[')||text.startsWith('{')){const value=JSON.parse(text);return (Array.isArray(value)?value:value.rows||[value]).map(r=>r.data?{...r,kind:r.kind||kind}:{kind,data:r,baseVersion:0});}const [headers,...rows]=csvParse(text);return rows.map((cells,index)=>{let row={kind,data:{},baseVersion:0};headers.forEach((header,n)=>{const key=header.trim(),raw=(cells[n]||'').trim();if(!raw)return;let v=raw;if(raw==='true'||raw==='false')v=raw==='true';else if(/^-?\d+(\.\d+)?$/.test(raw)&&!['id','userId','uid','ref','characterId','templateId'].includes(key))v=Number(raw);else if(/^[\[{]/.test(raw)){try{v=JSON.parse(raw);}catch{throw Error('第'+(index+2)+'行 '+key+' JSON无效。');}}if(['id','baseVersion'].includes(key))row[key]=v;else if(key==='templateKind'||key==='kind'&&kindNames[v])row.kind=v;else if(key==='data')row.data=v;else row.data=set(row.data,key.replace(/^data\./,''),v);});return row;});}
export function exportCsv(rows){const values=rows.map(r=>{const{id,version,published,...data}=r.data;return{templateKind:r.kind,id:r.id||'',baseVersion:r.baseVersion||0,...data};}),keys=[...new Set(values.flatMap(Object.keys))];const cell=v=>{if(v&&typeof v==='object')v=JSON.stringify(v);if(typeof v==='string'&&/^[=+@\-\t\r]/.test(v))v="'"+v;return '"'+String(v??'').replaceAll('"','""')+'"';};return '\uFEFF'+[keys,...values.map(r=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n');}
export function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export const rowSeeds={effects:{target:'attr:constitution',op:'add',value:0},conditionEffects:{target:'hp',amount:'1'},entries:{ref:'',quantity:1},conditions:{id:'',severity:'一般'},equipmentPreset:{ref:'',hand:'auto'},randomRoom:{ref:'',probabilities:[0,100]},variants:{id:'',name:'',weight:1,overrides:{}}};
export const actionDefaults={attack:{abilityKey:'',targetId:'',action:'formal',firing:{mode:'semi',count:1}},move:{x:25,y:25},reload:{ammoId:'',magazineId:'',weaponId:''},switch:{weaponId:'',hand:'auto'},item:{itemId:'',quantity:1},cast:{},pass:{type:'quick'},finish:{},flee:{},defend:{hitId:'',choice:'defend'},ammo:{ammoVersion:0,operation:{type:'fill',magazineId:'',ammoId:'',quantity:1}}};
export const objectDefaults={ai:{mode:'manual',target:'nearest',strategy:'smart',weights:{quick:{reload:35,extract:15,fill:15,heal:20,switch:5,cast:10},formal:{'attack:*':100},defense:{defend:100,dodge:0,both:0,none:0}}},data:{name:'',description:'',startsAt:'2026-10-10 20:00'},params:actionDefaults.attack};
