import React,{useEffect,useRef,useState} from 'react';
import {api} from './data';
import {Commands,Field} from './main';
import {mapStage,gridCells,mapCommandAllowed} from './ui-state';
import {useQuery} from './use-query';
const defaults={name:'',mapType:'indoor',mode:'manual',rows:4,width:3,blockedPercent:15,stairsMin:1,stairsMax:3,maxRank:3};
const labels={draft:'草稿',active:'进行中',paused:'已暂停',ended:'已结束'};
export function MapWorkspace(props){
  const {run,error,prepare,revision,lastResult,drafts={},saveLocal}=props;
  const [items,Items]=useState([]),[page,Page]=useState(0),[total,Total]=useState(0),[id,Id]=useState(''),[item,Item]=useState(null),[cell,Cell]=useState(''),[options,Options]=useState(null),[creating,Creating]=useState(false),[form,Form]=useState(()=>({...defaults,...drafts.mapCreate})),[command,Command]=useState('map.cell'),[image,Image]=useState(''),[full,Full]=useState(true),[selection,Selection]=useState(0);
  useEffect(()=>{if(props.navigation?.type==='map'){Id(props.navigation.id);Cell(props.navigation.cell||'');Creating(false);}},[props.navigation?.key]);
  const imageRef=useRef(''),active=useRef('');active.current=id+':'+(item?.version||'')+':'+full;
  useQuery(()=>api('/context/maps'),[revision],Options,error);
  useQuery(()=>api('/collections/explorations?size=25&page='+page),[revision,page],r=>{Items(r.items);Total(r.total);},error);
  useQuery(()=>id?api('/collections/explorations?id='+id):null,[id,revision],r=>Item(r?.item||null),error);
  useEffect(()=>{Item(null);Cell(props.navigation?.id===id?props.navigation.cell||'':'');Selection(n=>n+1);},[id]);
  useEffect(()=>{if(lastResult?.createdMap){Id(lastResult.id);Creating(false);Command('map.cell');}},[lastResult]);
  useEffect(()=>{if(!options)return;Form(f=>({...f,channelId:f.channelId||options.channelId,categoryId:options.categories.some(c=>c.id===f.categoryId&&c.mapTypes.includes(f.mapType)&&(f.mode==='fixed'||c.usable))?f.categoryId:options.categories.find(c=>c.mapTypes.includes(f.mapType)&&(f.mode==='fixed'||c.usable))?.id||''}));},[options,form.mapType,form.mode]);
  useEffect(()=>{const timer=setTimeout(()=>saveLocal?.('mapCreate',form),600);return()=>clearTimeout(timer);},[form]);
  useEffect(()=>{if(imageRef.current)URL.revokeObjectURL(imageRef.current);imageRef.current='';Image('');},[id,item?.version,full]);
  useEffect(()=>()=>{active.current='closed';if(imageRef.current)URL.revokeObjectURL(imageRef.current);},[]);
  const set=(k,v)=>Form(f=>({...f,[k]:v})),current=item?.cells?.[cell],types=options?.cellTypes[item?.mapType||'indoor']||{},roomOptions=options?.rooms.filter(r=>r.categoryIds?.includes(current?.categoryId||item?.categoryId))||[];
  const initial={mapId:id,cell,x:Number(cell.split(',')[0]||0),y:Number(cell.split(',')[1]||0),type:current?.type||'empty',categoryId:current?.categoryId||item?.categoryId||'',templateId:current?.templateId||'',variantId:current?.variantId||'',name:current?.name||'',description:current?.description||'',passable:current?.passable!==false,hasContents:!!current?.hasContents,buildingMapId:current?.buildingMapId||'',rpId:item?.rpPendingId||'',rpVersion:item?.rps?.[item?.rpPendingId]?.version,requestId:current?.room?.bossRequest?.id||'',requestVersion:current?.room?.bossRequest?.version,selection};
  const commands=props.schema.commands.filter(c=>c.group==='map'&&!['map.create','map.quickCreate','map.cleanup'].includes(c.id));
  const allowed=commands.filter(c=>mapCommandAllowed(c.id,item,cell));
  async function loadImage(){const selected=id,version=item?.version,proof=active.current,scope=window.gmSession.guildId;await run(async()=>{const response=await fetch((window.gmMediaBase||'/api/gm/v1')+'/media/map/'+selected+'?gm='+(full?'1':'0')+'&wide=1&v='+version);if(!response.ok)throw Error('静态图暂时无法读取，地图仍可操作。');const blob=await response.blob();if(active.current!==proof||window.gmSession.guildId!==scope)return;const url=URL.createObjectURL(blob);if(imageRef.current)URL.revokeObjectURL(imageRef.current);imageRef.current=url;Image(url);}).catch(()=>{});}
  return <>
    <section className="panel">
      <div className="section-title"><div><span className="eyebrow">MAP WORKSPACE</span><h3>探索地图</h3></div><button className="primary" onClick={()=>Creating(true)}>＋ 新建地图</button></div>
      <div className="toolbar"><select aria-label="选择管理地图" value={id} onChange={e=>Id(e.target.value)}><option value="">选择已有地图</option>{id&&!items.some(m=>m.id===id)&&<option value={id}>{item?.name||'新建地图'}</option>}{items.map(m=><option key={m.id} value={m.id}>{m.name} · {labels[m.status]||m.status}</option>)}</select><button disabled={!page} onClick={()=>Page(page-1)}>上一页</button><span>{total} 张地图</span><button disabled={(page+1)*25>=total} onClick={()=>Page(page+1)}>下一页</button></div>
      {!id&&!creating&&<p className="empty-note">点击“新建地图”，填写名称和主题即可生成草稿。发布后玩家才能加入。</p>}
      {item&&!creating&&<>
        <div className="map-status toolbar"><strong>{item.name}</strong><span className="badge">{mapStage(item)}</span><span>{item.floors}行 × {item.width}列 · v{item.version}</span>{['map.generate','map.publish','map.pause','map.resume'].filter(c=>mapCommandAllowed(c,item,cell)).map(c=><button key={c} className={c==='map.publish'?'primary':''} disabled={props.busy} onClick={()=>prepare(c,{mapId:id})}>{({'map.generate':'生成房间内容','map.publish':window.gmDirect?'发布地图':'预览并发布','map.pause':'暂停地图','map.resume':'恢复探索'})[c]}</button>)}</div>
        {mapStage(item)==='待布置'&&<p>固定布局：点击房间格选择房间模板，布置完成后生成内容。</p>}
        <div className="toolbar"><button onClick={loadImage}>查看最新静态大图</button><label><input type="checkbox" checked={full} onChange={e=>Full(e.target.checked)}/>GM 全图</label></div>
        {image&&<img className="map-image" src={image} alt="当前保存的地图"/>}
        <div className="map-edit-layout"><div className="map-scroll"><div className="map-grid" style={{gridTemplateColumns:'repeat('+item.width+',minmax(64px,1fr))'}}>{gridCells(item.width,item.floors,item.cells).map(({ref,cell:c})=><button key={ref} className={(ref===cell?'selected ':'')+(!c?'empty-cell ':c.passable===false||c.type==='wall'?'blocked':'')} onClick={()=>{Cell(ref);Command('map.cell');Selection(n=>n+1);}}><small>{String.fromCharCode(65+Number(ref.split(',')[0]))}{Number(ref.split(',')[1])+1}</small><b>{!c?'空格':!full&&!item.revealed?.[ref]?'迷雾':c.room?.merchant?.name||c.room?.snapshot?.name||c.name||types[c.type]||c.type}</b>{full&&c?.room?.boss&&<span>BOSS</span>}</button>)}</div></div>
        <aside className="map-inspector"><h4>{cell?'格子 '+String.fromCharCode(65+Number(cell.split(',')[0]))+(Number(cell.split(',')[1])+1):'选择格子编辑'}</h4>{cell&&<><p>{types[current?.type]||'空格'} · {current?.touched?'已有交互记录，替换受保护':'尚无交互记录'}</p><p>{current?.room?.snapshot?.name||current?.name||''}</p></>}<p>选择下方操作。不可用操作会说明所需状态；服务端提交时再次校验。</p><div className="map-actions">{commands.map(c=><button key={c.id} disabled={!mapCommandAllowed(c.id,item,cell)} title={!mapCommandAllowed(c.id,item,cell)?'请先选择格子，或暂停地图；生成和发布仅适用于草稿。':''} onClick={()=>Command(c.id)}>{c.label}</button>)}</div></aside></div>
      </>}
    </section>
    {item&&!creating&&allowed.length>0&&<Commands {...props} groups={['map']} commandId={allowed.some(c=>c.id===command)?command:allowed.find(c=>c.id===(mapStage(item)==='可发布'?'map.publish':item.status==='active'?'map.pause':item.status==='paused'?'map.resume':'map.generate'))?.id||allowed[0]?.id} lockedContext allowedCommands={allowed.map(c=>c.id)} initial={initial} fieldOptions={(p,selectedCommand)=>({type:[...Object.entries(types).map(([value,label])=>({value,label})),{value:'empty',label:'删除／空格'}],templateId:selectedCommand==='map.merchant'?options?.merchants:selectedCommand==='map.restock'?undefined:options?.rooms.filter(r=>r.categoryIds?.includes(p.categoryId||item.categoryId)),variantId:(options?.rooms.find(r=>r.id===p.templateId)?.variants||[]),poolId:options?.bossPools})}/>}
    {creating&&<section className="panel map-create"><div className="section-title"><h3>创建地图草稿</h3><button onClick={()=>Creating(false)}>收起，保留填写</button></div><p>{window.gmDirect?'点击创建时保存一次随机结果，完成后自动打开地图；需要时点击发布。':'随机结果在确认时保存一次。生成后自动打开地图，发布由你确认。'}</p><div className="form-grid"><Field def={{key:'name',label:'地图名称',type:'text'}} value={form.name} onChange={v=>set('name',v)}/><Field def={{key:'mapType',label:'地图类型',type:'choice',values:[{value:'indoor',label:'室内地图'},{value:'region',label:'区域地图'}]}} value={form.mapType} onChange={v=>set('mapType',v)}/><Field def={{key:'categoryId',label:'地图主题',type:'choice',values:(options?.categories||[]).filter(c=>c.mapTypes.includes(form.mapType)&&(form.mode==='fixed'||c.usable)).map(c=>({value:c.id,label:c.name}))}} value={form.categoryId} onChange={v=>set('categoryId',v)}/></div>
      {!form.categoryId&&<div className="banner error">没有适用的已发布主题和房间。请到“内容录入”发布地图分类，并为该分类添加房间。<button onClick={()=>props.openTemplates?.('mapcategory')}>打开内容录入</button></div>}
      <details><summary>高级设置</summary><div className="form-grid"><Field def={{label:'生成方式',type:'choice',values:[{value:'manual',label:'指定尺寸，随机布局与内容'},{value:'full',label:'主题与尺寸全部随机（4—8）'},{value:'fixed',label:'固定布局，逐格布置房间'}]}} value={form.mode} onChange={v=>set('mode',v)}/>{form.mode!=='full'&&['rows','width'].map(k=><Field key={k} def={{label:k==='rows'?'层／行数（1—20）':'列数（1—20）',type:'number'}} value={form[k]} onChange={v=>set(k,v)}/>)}{form.mode!=='fixed'&&<Field def={{label:'阻挡比例（0—30%）',type:'number'}} value={form.blockedPercent} onChange={v=>set('blockedPercent',v)}/ >}{form.mapType==='indoor'&&form.mode!=='fixed'&&['stairsMin','stairsMax'].map(k=><Field key={k} def={{label:k==='stairsMin'?'最少楼梯连接（1—3）':'最多楼梯连接（1—3）',type:'number'}} value={form[k]} onChange={v=>set(k,v)}/>)}<Field def={{label:'怪物等级上限（1—10）',type:'number'}} value={form.maxRank} onChange={v=>set('maxRank',v)}/><Field def={{label:'公示频道',type:'channel'}} value={form.channelId} onChange={v=>set('channelId',v)}/></div></details>
      <button className="primary" disabled={props.busy||!form.name.trim()||!form.categoryId||!form.channelId} onClick={()=>prepare('map.quickCreate',form)}>{window.gmDirect?(form.mode==='fixed'?'创建固定布局草稿':'创建并生成地图'):(form.mode==='fixed'?'预览固定布局草稿':'预览并生成草稿')}</button>
    </section>}
    <details className="panel"><summary>清理已结束地图</summary><Commands {...props} groups={['map']} allowedCommands={['map.cleanup']}/></details>
  </>;
}
