'use strict';
const C=require('./constants'),M=require('./model'),B=require('./combat'),H=require('./health'),T=require('./treatment'),U=require('./ui');
function createBulkUse({snapshot,tx,store,actionPanel}){
 function owned(s,id,uid){const f=s.forms[id];C.requireThat(f?.kind==='bulkUse'&&f.owner===uid,'批量使用草稿不属于你。');return f;}
 function validate(s,f){const p=M.player(s,f.owner);H.requireAction(p);C.requireThat(p.id===f.characterId,'角色已经变化。');C.requireThat(C.CONSUMABLES.includes(p.inventory[f.itemId]?.snapshot.kind)&&M.available(s,f.owner,f.itemId)>=f.quantity,'道具数量不足、不支持批量或已被预留。');
  if(f.battleId){const b=s.battles[f.battleId],a=b?.actors.find(a=>a.id===f.actorId);C.requireThat(b?.status==='active'&&a?.userId===f.owner&&B.current(s,b,f.turnId).actor.id===a.id&&!b.pending,'行动机会已经变化。');const target=T.battle(s,b,a,f.recipientId);C.requireThat(target.p.id===f.targetCharacterId&&b.current.quick>=f.quantity,'目标已变化或快速行动不足，每件消耗一次。');return {p,target:target.p,b,a};}
  const target=T.outside(s,f.owner,f.targetUid);C.requireThat(target.id===f.targetCharacterId,'治疗目标角色已经变化。');return {p,target};}
 function view(s,f){const p=M.player(s,f.owner),item=p.inventory[f.itemId],target=f.battleId?B.actorCharacter(s,s.battles[f.battleId].actors.find(a=>a.id===f.recipientId)):s.players[f.targetUid];const v=U.payload('确认批量使用', (item?.snapshot.name||'物品已失效')+' ×'+f.quantity+' → '+target.name+'\n'+(f.battleId?'消耗 '+f.quantity+' 次快速行动，剩余 '+s.battles[f.battleId].current.quick+' 次。\n':'')+'每件分别结算治疗骰：'+(item?.snapshot.heal||'0')+'。持续效果替换，不叠加。\n'+H.text(target)+'\n截止 <t:'+Math.floor(f.expiresAt/1000)+':R>',[U.row(U.button('bulkuse:quantity:'+f.id+':'+f.version,'修改数量'),U.button('bulkuse:commit:'+f.id+':'+f.version,f.battleId?'继续 / 填写 RP':'确认使用',U.D.ButtonStyle.Success),U.button('bulkuse:cancel:'+f.id,'取消'))]);v.rpgPanel=f.battleId?{kind:'battle',battleId:f.battleId,actorId:f.actorId,tab:'quick'}:{kind:'bag'};return v;}
 async function prepare(i,itemId,quantity=1,targetUid=i.user.id,recipientActorId){quantity=C.number(quantity,'使用数量',1,100);const f=await tx(i,st=>{const p=M.player(st,i.user.id),b=M.battleFor(st,i.user.id),f={id:C.id('f'),kind:'bulkUse',owner:i.user.id,characterId:p.id,itemId,targetUid,quantity,version:0,status:'ready',expiresAt:C.confirmationDeadline(300000)};
   if(b){const a=b.actors.find(a=>a.userId===i.user.id),recipient=b.actors.find(a=>recipientActorId?a.id===recipientActorId:a.userId===targetUid);C.requireThat(a&&recipient,'当前行动或受疗者无效。');Object.assign(f,{battleId:b.id,actorId:a.id,turnId:b.current?.id,recipientId:recipient.id,targetCharacterId:B.actorCharacter(st,recipient).id});}else f.targetCharacterId=M.player(st,targetUid).id;validate(st,f);st.forms[f.id]=f;return f;},'准备批量道具');return view(snapshot(i.guildId),f);}
 async function openModal(i,s){if(i.isModalSubmit?.()||!i.customId?.startsWith('rpg:bulkuse:quantity:'))return false;const [,,,id,version]=i.customId.split(':'),f=owned(s,id,i.user.id);C.requireThat(f.status==='ready'&&f.expiresAt>Date.now()&&f.version===Number(version),'数量步骤已失效。');await i.showModal(U.modal('bulkuse:quantitysubmit:'+id+':'+version,'批量使用道具',[{key:'quantity',label:'使用数量（1—100）',value:f.quantity}]));return true;}
 async function component(i){const [,,action,id,version]=i.customId.split(':'),s=snapshot(i.guildId),f=owned(s,id,i.user.id);
  if(action==='quantitysubmit'){const updated=await tx(i,st=>{const f=owned(st,id,i.user.id);C.requireThat(f.status==='ready'&&f.expiresAt>Date.now()&&f.version===Number(version),'数量步骤已失效。');f.quantity=C.number(i.fields.getTextInputValue('quantity'),'数量',1,100);validate(st,f);f.version++;return f;},'修改使用数量');return view(snapshot(i.guildId),updated);}
  if(action==='cancel'){await tx(i,st=>{const f=owned(st,id,i.user.id);if(f.status==='ready')f.status='cancelled';},'取消批量使用');return U.inventoryView(snapshot(i.guildId),i.user.id,i.user.id);}
  C.requireThat(action==='commit','使用入口失效。');C.requireThat(f.expiresAt>Date.now()&&f.version===Number(version),'使用确认已变化或过期。');
  if(f.battleId){validate(s,f);return actionPanel.prepare(i,{battleId:f.battleId,actorId:f.actorId,turnId:f.turnId,action:'item',expiresAt:f.expiresAt,sourceFormId:f.id,params:{itemId:f.itemId,quantity:f.quantity,recipientId:f.recipientId,recipientCharacterId:f.targetCharacterId}});}
  i.rpgOperation='bulk-use:'+id;const r=await store.transact(i.guildId,i.rpgOperation,i.user.id,st=>{const f=owned(st,id,i.user.id);if(f.status==='done')return f.result;C.requireThat(f.status==='ready'&&f.expiresAt>Date.now()&&f.version===Number(version),'使用确认已变化或过期。');const {p,target}=validate(st,f),result=M.consumeMany(p,f.itemId,f.quantity,undefined,null,Date.now(),target);f.status='done';f.done=true;f.result=result;return result;},'批量使用道具');return U.payload('批量使用已保存',r.name+' ×'+r.quantity+'\n恢复正常HP '+r.healed+' · 倒地HP '+r.reserveHealed+'\n'+H.text(M.player(snapshot(i.guildId),f.targetUid))+'\n逐件治疗骰：'+(r.results||[r]).map((v,n)=>(n+1)+'. '+v.roll.expression+' = '+v.roll.total).join('、').slice(0,2800),[U.row(U.button('reopen:bag','返回背包'))]);}
 return {prepare,view,component,openModal};
}
module.exports={createBulkUse};
