'use strict';
const C=require('./constants'),K=require('./containers'),V=require('./room-variants');
const CATEGORY_NAMES=['现代建筑群','民房建筑群','丛林区域','山谷哨站','研究基地','军事基地','摩天大楼','医疗中心','工业园区','商业街区','地下交通枢纽','物流仓储园','港口码头','机场航站区','大学园区','农业聚落','能源设施','山地矿区','废弃小镇','边境检查区'];
const ROOM_NAMES=['便利店卖场','药房仓库','医务室','实验室','设备机房','保安室','警务值班室','办公室','会议室','档案室','工具间','维修车间','地下车库','员工宿舍','公共厨房','食堂后厨','临时营地','山谷观察哨','林间检查站','地下避难室'];
const ROOM_TEXT=['货架分列在狭窄过道两侧，收银台后留有价格标签与补货记录。','药品分类柜沿墙摆放，纸盒上还能辨认批号和储存要求。','检查床与洗手池占据两侧，柜内分格存放着医疗用具。','实验台上布满连接管和标记，通风柜后留有样本操作记录。','散热风道穿过机柜，线缆束沿墙汇入控制柜。','值班桌面向出入口，监控屏下摆着巡查登记簿。','装备柜围着值班台，墙上的辖区图仍标着巡逻路线。','隔断将工位分开，桌面文具与文件映照着灾前工作的日常。','长桌周围摆着座椅，投影幕下留有讨论记录。','成排文件架按年代编号，索引柜仍保持着可辨认的顺序。','挂板悬着工具轮廓，工作台边堆着分类零件盒。','拆开的机器占据维修台，地面有长期使用留下的油痕。','车位线穿过昏暗空间，坡道旁留着设备检修标记。','床铺与储物柜相对排列，窗边挂着褪色的日用品。','公共料理台围绕水池，餐具架保留着共享使用的痕迹。','灶台、冷藏设备和备料桌依次排列，墙上贴着旧菜单。','临时铺位环绕一处遮蔽空间，包装和脚印记录着停留的痕迹。','观察窗口面向山谷，地图和通信器材留在值守位置。','检查设施掩在林木之间，简易路障旁留有来往登记。','厚门后的空间设有备用照明、储存架和应急通风装置。'];
const MONSTERS=[['残次','保洁员'],['游荡','保安'],['猎行','消防员'],['缝合','巡警'],['重塑','研究员'],['畸变','军械员'],['侵蚀','指挥官'],['裂隙','执行者'],['原点残响','现实校准员'],['界限崩解','秩序守望者']];
function install(state){if(state.contentPackVersion===1)return null;const report={items:0,npcs:0,rooms:0,categories:0,variants:0};state.catalog||={};state.skillTemplates||={};state.mapCategories||={};state.roomTemplates||={};state.npcTemplates||={};state.templateTombstones||={};
 const insert=(root,t)=>{if(!state[root][t.id]&&!state.templateTombstones[t.id]){state[root][t.id]=t;return true;}return false;};
 for(const t of Object.values(require('./modern-props').catalog()))if(insert('catalog',t))report.items++;
 state.containerDefinitions||=K.definitions();state.config.containerRates||=C.clone(K.DEFAULTS);state.config.legacySafeRatesBackup||=C.clone(state.config.safeRates||{});state.config.rpChannelId??=null;state.mapTombstones||={};
 CATEGORY_NAMES.forEach((name,n)=>{const id='area_'+n;insert('mapCategories',{id,name,description:'原点之后的'+name+'，保留现代设施与灾后变化，可在GM面板编辑。',version:1,published:true,mapTypes:['丛林区域','山地矿区','农业聚落'].includes(name)?['region']:['indoor','region'],seedPackage:'exploration-v1'})&&report.categories++;});
 const police=Object.values(state.npcTemplates).find(t=>t.name==='异常腐化的警察'),weak=Object.values(state.npcTemplates).find(t=>t.name==='异常造物（劣等）');state.conditionTemplates||={};
 MONSTERS.forEach(([creation,job],rank)=>{for(let family=0;family<2;family++){const id='monster_'+rank+'_'+family,name=family?'异常腐化的'+job:'异常造物（'+creation+'）',skills=[];
   const conditionId=id+'_condition',type=family?'mental':'physical',target=['agility','mind','strength','constitution','intelligence','knowledge','agility','mind','strength','constitution'][rank];insert('conditionTemplates',{id:conditionId,version:1,published:true,name:name+' · '+['迟滞','惊扰','牵制','压迫','感官偏移','震颤','侵蚀','失衡','现实脱节','界限磨损'][rank],description:'该异常施加于目标，短暂削弱'+C.ATTRIBUTES[target]+'，持续自身行动机会。',type,effectType:'numeric',levels:{'一般':{difficulty:10,duration:{kind:'actions',count:2},worsenAfter:0,description:'临时'+C.ATTRIBUTES[target]+'降低1点。',effects:[{target:'attr:'+target,amount:'1'}]}}});
   for(let j=0;j<2;j++){const sid=id+'_skill'+j,skill={id:sid,version:1,published:true,kind:'技能',name:name+' · '+(j?'失序回响':'扭曲冲击'),description:j?'以异常回响侵袭目标的感知。':'由自身异常力量发动的直接攻击。',rarity:'white',weight:0,value:0,boxes:[],traitIds:[],effects:[],ownEffects:[],requiresWeapon:false,melee:!j&&!family,rangeMeters:j||family?50:0,hit:10,damage:j?{physical:'',magical:'',mental:'1d4'}:{physical:'1d6',magical:'',mental:''},primary:j?'mental':'physical',action:'formal',casting:j?1:0,conditions:j?[{id:conditionId,severity:'一般'}]:[],aoe:{mode:'single',radius:0,allowAlly:false,allowSelf:false}};insert('skillTemplates',skill);skills.push(C.clone(state.skillTemplates[sid]||skill));}
   const t={id,name,description:family?'灾前的'+job+'被原点扭曲，残存习惯变成重复而危险的行动。':'由现实不稳定区凝结的'+creation+'异常造物，形态和行为均受到局部扭曲影响。',version:1,published:true,humanoid:!!family,baseXP:family?30:10,attributes:C.clone(family?(police?.attributes||{strength:5,constitution:6,mind:0,appearance:0,intelligence:0,agility:6,knowledge:3}):(weak?.attributes||{strength:1,constitution:3,mind:0,appearance:0,intelligence:0,agility:3,knowledge:0})),hpMax:family?(police?.hpMax||20):(weak?.hpMax||18),anomalyRank:require('./npc-strength').LEVELS[rank],levelMin:rank*10+1,levelMax:(rank+1)*10,randomStrength:true,itemIds:family&&police?C.clone(police.itemIds||[]):[],loadout:family&&police?C.clone(police.loadout||[]):[],equipmentPreset:family&&police&&police.equipmentPreset!==undefined?C.clone(police.equipmentPreset):[],skillIds:skills.map(t=>t.id),skillSnapshots:skills,ai:require('./npc-auto').config({mode:'auto',strategy:'smart'}),seedPackage:'exploration-v1'};if(insert('npcTemplates',t))report.npcs++;}});
 ROOM_NAMES.forEach((name,n)=>{const id='room_seed_'+n,outdoor=n>=16&&n<=18,ids=CATEGORY_NAMES.map((_,i)=>'area_'+i).filter((_,i)=>outdoor?[2,3,15,17,18,19].includes(i):![2,17].includes(i));
   const boxes=n===1||n===2?['药品柜','医疗包']:n===3?['实验样本箱','工具包']:n===4?['服务器机柜','工具包']:n===5||n===6?['安保装备柜','储物柜']:n===9?['档案密集柜']:n===10||n===11?['机械维修箱','工具包']:n===14||n===15?['冷藏箱','饭盒']:outdoor?['旅行包','战术补给箱']:['抽屉','储物柜'];
   const raw={id,name,description:ROOM_TEXT[n],version:1,published:true,categoryIds:ids,boxes:[],containerCounts:{},supplyIds:[],supplyQuantities:{},npcIds:[],npcQuantities:{},keyIds:[],autoStart:true,spawn:{playerX:25,playerY:25,npcX:475,npcY:475},randomContainers:boxes.map(ref=>({ref,probabilities:[35,45,15,5,0,0,0]})),randomSupplies:[],randomNpcs:[{ref:'monster_'+(n%3)+'_'+(n%2),probabilities:[65,25,8,2,0,0,0,0,0,0,0]}],seedPackage:'exploration-v1'};
   const t=require('./exploration').validateRoom(state,raw);t.variants=V.defaults(t);if(insert('roomTemplates',t)){report.rooms++;report.variants+=t.variants.length;}});
 for(const t of Object.values(state.roomTemplates)){if(!t.variants){t.variants=V.defaults(t);report.variants+=t.variants.length;}t.categoryIds||=[];}
 for(const t of Object.values(state.mapCategories))t.mapTypes||=['indoor','region'];
 for(const t of Object.values(state.npcTemplates)){t.anomalyRank||='I';t.randomStrength??=false;}
 state.contentPackVersion=1;state.contentMigration={at:Date.now(),report:C.clone(report)};return report;
}
module.exports={install,CATEGORY_NAMES,ROOM_NAMES,MONSTERS};
