'use strict';
const C=require('./constants'),K=require('./containers'),L=require('./loot'),U=require('./ui'),X=require('./exploration'),Layout=require('./random-layout'),Clean=require('./map-cleanup');
const {requireThat:ok}=C,labels=Object.fromEntries(C.RARITIES.map(r=>[r.id,r.name]));
function controller({snapshot,tx,store,client,textChannel,needGM,manage,publishMap,logFailure}){
 function boxes(s,page=0){page=Math.max(0,Math.min(Number(page)||0,Math.ceil(K.ALL.length/20)-1));return U.payload('52种现代容器','下拉选容器修改档位；同色容器共用一套概率。',[U.row(U.select('mapx:boxpick','选择容器',K.ALL.slice(page*20,page*20+20).map(name=>({label:name+' · '+labels[K.get(s,name).grade]+'类'+(K.get(s,name).enabled?'':' · 停用'),value:name})))),U.row(U.button('mapx:boxes:'+(page-1),'上一页',undefined,!page),U.button('mapx:boxes:'+(page+1),'下一页',undefined,(page+1)*20>=K.ALL.length),U.button('mapx:grades','六色概率'),U.button('map:config','返回'))]);}
 function box(s,name){const d=K.get(s,name);ok(d,'容器不存在。');return U.payload(name+' · '+labels[d.grade]+'类','物品概率（红 金 紫 蓝 绿 白）：'+L.rates(s,name).slice().reverse().join('% / ')+'%\n已生成结果保持原样。',[U.row(U.select('mapx:boxgrade:'+name,'修改容器档位',C.RARITIES.map(r=>({label:r.name+'类',value:r.id,default:r.id===d.grade})))),U.row(U.button('mapx:boxenabled:'+name,d.enabled?'停用容器':'启用容器'),U.button('mapx:boxes:0','返回容器列表'))]);}
 function grades(s,grade){if(!grade)return U.payload('六色容器概率','概率按红、金、紫、蓝、绿、白输入，必须合计100%。',[U.row(U.select('mapx:gradepick','选择六色档位',C.RARITIES.map(r=>({label:r.name+'类',value:r.id})))),U.row(U.button('mapx:boxes:0','容器分档'),U.button('map:config','返回'))]);return U.payload(labels[grade]+'类 · 掉落概率',(s.config.containerRates?.[grade]||K.DEFAULTS[grade]).slice().reverse().map((n,i)=>['红','金','紫','蓝','绿','白'][i]+' '+n+'%').join('\n'),[U.row(U.button('mapx:gradeedit:'+grade,'编辑概率'),U.button('mapx:gradereset:'+grade,'恢复默认'),U.button('mapx:grades','返回'))]);}
 function form(s,f){const d=f.data;return U.payload('地图生成 · '+({full:'全随机',manual:'手动随机',fixed:'固定编辑'}[d.mode]),'地图类型：'+(d.mapType==='region'?'区域地图':'建筑内部')+'\n主题：'+(d.mode==='full'?'自动选择':s.mapCategories[d.categoryId]?.name||'请选择')+'\n名称：'+d.name+'\n尺寸：'+(d.mode==='full'?'自动4—8层/行，不规则4—8宽':d.rows+' × '+d.width)+'\n阻挡 '+d.blockedPercent+'% · 楼梯连接 '+d.stairsMin+'—'+d.stairsMax+' · 难度上限 '+require('./npc-strength').LEVELS[d.maxRank-1],[
 U.row(U.select('mapx:mode:'+f.id,'生成方式',[{label:'全随机 · 自动主题尺寸',value:'full'},{label:'手动随机 · 指定主题尺寸',value:'manual'},{label:'固定编辑 · 保留逐格操作',value:'fixed'}].map(v=>({...v,default:v.value===d.mode})))),
 U.row(U.select('mapx:difficulty:'+f.id,'怪物异常等级上限',require('./npc-strength').LEVELS.map((label,n)=>({label:label+'级及以下',value:String(n+1),default:d.maxRank===n+1})))),
 U.row(U.button('mapx:settings:'+f.id,'名称 / 尺寸 / 生成限制'),U.button('mapx:categories:'+f.id+':0','选择主题',undefined,d.mode==='full'),U.button('mapx:generate:'+f.id+':'+f.version,'生成私有预览',U.D.ButtonStyle.Success),U.button('map:home','退出，草稿保留'))]);}
 function categories(s,f,page=0){const entries=Object.values(s.mapCategories).filter(t=>t.published&&(t.mapTypes||['indoor','region']).includes(f.data.mapType));page=Math.max(0,Math.min(Number(page)||0,Math.max(0,Math.ceil(entries.length/20)-1)));return U.payload('选择兼容大类','第'+(page+1)+'页',[...(entries.length?[U.row(U.select('mapx:category:'+f.id,'选择主题',entries.slice(page*20,page*20+20).map(t=>({label:t.name,value:t.id}))))]:[]),U.row(U.button('mapx:categories:'+f.id+':'+(page-1),'上一页',undefined,!page),U.button('mapx:categories:'+f.id+':'+(page+1),'下一页',undefined,(page+1)*20>=entries.length),U.button('mapx:form:'+f.id,'返回'))]);}
 async function openModal(i,s){if(i.isModalSubmit?.()||!i.customId?.startsWith('rpg:mapx:'))return false;const [,,action,ref]=i.customId.split(':');if(!['settings','gradeedit'].includes(action))return false;needGM(s,i.member);if(action==='gradeedit'){ok(K.DEFAULTS[ref],'档位无效。');await i.showModal(U.modal('mapx:gradesubmit:'+ref,'六色概率',[{key:'values',label:'红 金 紫 蓝 绿 白，空格分隔',value:(s.config.containerRates?.[ref]||K.DEFAULTS[ref]).slice().reverse().join(' ')}]));}else{const f=require('./forms').owned(s,ref,i.user.id),d=f.data;await i.showModal(U.modal('mapx:settingssubmit:'+ref+':'+f.version,'地图生成配置',[{key:'name',label:'地图名称',value:d.name},{key:'rows',label:'层数/行数1—20（全随机忽略）',value:d.rows},{key:'width',label:'最大宽度2—20（全随机忽略）',value:d.width},{key:'blocked',label:'阻挡比例0—30',value:d.blockedPercent},{key:'stairs',label:'最少和最多楼梯连接，各1—3，空格隔开',value:d.stairsMin+' '+d.stairsMax}]));}return true;}
 function cleanup(s,f){const list=f?.entries||Clean.preview(s),eligible=list.filter(e=>!e.reason);return U.payload('清理已结束地图 · 预览',list.map(e=>e.name+' · '+(e.reason?'跳过：'+e.reason:'房间 '+e.rooms+'，关联公示 '+e.publications+'，未领取物资/容器 '+e.unclaimed+'，NPC掉落 '+e.corpses)).join('\n').slice(0,3500)||'没有已结束地图。',f?[U.row(U.button('mapx:cleanconfirm:'+f.id,'确认清理 '+eligible.length+' 张',U.D.ButtonStyle.Danger,!eligible.length),U.button('map:home','取消'))]:[]);}
 async function disable(guild,result){for(const e of result.messages){try{const ch=await textChannel(guild,e.channelId),m=await ch.messages.fetch(e.messageId);if(m.author.id!==client.user.id)continue;await m.edit({content:'地图已清理。历史奖励与已入背包资产保留。',embeds:[],components:[],attachments:[],allowedMentions:{parse:[]}});await store.transact(guild,'map-clean-msg:'+e.messageId,client.user.id,st=>{st.mapCleanupMessages[e.channelId+':'+e.messageId].done=true;},'旧地图按钮已停用');}catch(error){if(error.code===10008)await store.transact(guild,'map-clean-gone:'+e.messageId,client.user.id,st=>{st.mapCleanupMessages[e.channelId+':'+e.messageId].done=true;},'旧地图消息已不存在');else logFailure('旧地图已清理，公示按钮更新失败；旧按钮不能再执行。',error);}}}
 async function component(i,member){const [,,action,ref,arg]=i.customId.split(':'),s=snapshot(i.guildId);needGM(s,member);
 if(action==='boxes')return boxes(s,ref);if(action==='boxpick')return box(s,i.values[0]);if(action==='grades')return grades(s);if(action==='gradepick')return grades(s,i.values[0]);
 if(['boxgrade','boxenabled','gradesubmit','gradereset'].includes(action)){await tx(i,st=>{needGM(st,member);if(action==='boxgrade')K.setGrade(st,ref,i.values[0]);else if(action==='boxenabled'){st.containerDefinitions||=K.definitions();ok(st.containerDefinitions[ref],'容器无效。');st.containerDefinitions[ref].enabled=!st.containerDefinitions[ref].enabled;st.containerDefinitions[ref].version++;}else L.setGradeRates(st,ref,action==='gradereset'?K.DEFAULTS[ref]:i.fields.getTextInputValue('values').trim().split(/\s+/).map(Number).reverse());},'调整六色容器');return action.startsWith('box')?box(snapshot(i.guildId),ref):grades(snapshot(i.guildId),ref);}
 if(action==='start')return U.payload('创建随机探索地图','先选择地图类型，再设置生成模式和异常难度。',[U.row(U.select('mapx:type','地图类型',[{label:'建筑内部',value:'indoor'},{label:'区域大地图',value:'region'}])),U.row(U.button('map:home','返回'))]);
 if(action==='type'){const f=await tx(i,st=>{needGM(st,member);ok(['indoor','region'].includes(i.values[0]),'类型无效。');const f={id:C.id('f'),owner:i.user.id,kind:'mapbuild',version:1,data:{name:'未知探索区域',mapType:i.values[0],mode:'full',categoryId:null,rows:5,width:8,blockedPercent:15,stairsMin:1,stairsMax:3,maxRank:3}};st.forms[f.id]=f;return f;},'新地图生成草稿');return form(snapshot(i.guildId),f);}
 if(action==='cleanuppreview'){const f=await tx(i,st=>{const f={id:C.id('f'),owner:i.user.id,kind:'mapcleanup',entries:Clean.preview(st),expiresAt:Date.now()+300000};st.forms[f.id]=f;return f;},'旧地图清理预览');return cleanup(snapshot(i.guildId),f);}
 if(action==='cleanconfirm'){const result=await tx(i,st=>{needGM(st,member);const f=require('./forms').owned(st,ref,i.user.id);ok(f.kind==='mapcleanup'&&!f.done&&f.expiresAt>Date.now(),'清理预览已失效。');const r=Clean.remove(st,f.entries.filter(e=>!e.reason));f.done=true;st.mapCleanupMessages||={};for(const e of r.messages)st.mapCleanupMessages[e.channelId+':'+e.messageId]={...e,done:false};return r;},'清理已结束地图');await disable(i.guildId,result);return U.payload('旧地图清理完成','已清理：'+(result.deleted.map(e=>e.name).join('、')||'无')+'\n跳过：'+(result.skipped.map(e=>e.name+'：'+e.reason).join('、')||'无'),[U.row(U.button('map:home','返回地图列表'))]);}
 if(action==='layout'){const m=s.explorations[ref];ok(m?.status==='draft','仅能重抽草稿布局。');const f=await tx(i,st=>{const m=st.explorations[ref];ok(m.status==='draft'&&m.version===Number(arg),'地图已变化。');Layout.build(m,{...m.generation,mode:m.generation?.mode||'manual'});X.generate(st,m);return m.id;},'重抽草稿布局与房间');return manage(snapshot(i.guildId),snapshot(i.guildId).explorations[f]);}
 const F=require('./forms'),f=F.owned(s,ref,i.user.id);ok(f.kind==='mapbuild'&&!f.done,'地图生成草稿已结束。');if(action==='form')return form(s,f);if(action==='categories')return categories(s,f,arg);
 const result=await tx(i,st=>{needGM(st,member);const f=F.owned(st,ref,i.user.id);ok(f.kind==='mapbuild'&&!f.done,'草稿已完成。');if(action==='mode'){ok(['full','manual','fixed'].includes(i.values[0]),'生成方式无效。');f.data.mode=i.values[0];}else if(action==='difficulty')f.data.maxRank=C.number(i.values[0],'异常上限',1,10);else if(action==='category'){ok(st.mapCategories[i.values[0]]?.published,'大类失效。');f.data.categoryId=i.values[0];}else if(action==='settingssubmit'){ok(f.version===Number(arg),'草稿已变化。');f.data.name=C.text(i.fields.getTextInputValue('name'),'地图名称',80);f.data.rows=C.number(i.fields.getTextInputValue('rows'),'层数/行数',1,20);f.data.width=C.number(i.fields.getTextInputValue('width'),'宽度',2,20);const stairs=i.fields.getTextInputValue('stairs').trim().split(/\s+/).map(Number);ok(stairs.length===2,'填写两个楼梯数量。');Object.assign(f.data,Layout.options({blockedPercent:i.fields.getTextInputValue('blocked'),stairsMin:stairs[0],stairsMax:stairs[1],maxRank:f.data.maxRank}));}else if(action==='generate'){ok(f.version===Number(arg),'生成配置已经变化。');const d=f.data,m=Layout.create(st,i.user.id,i.channelId,d.name,d.mapType,d.mode,d.categoryId,d.rows,d.width,d);if(d.mode!=='fixed')X.generate(st,m);f.done=true;return m.id;}else throw Error('地图生成操作失效。');f.version++;return null;},'编辑或生成探索地图');return result?manage(snapshot(i.guildId),snapshot(i.guildId).explorations[result]):form(snapshot(i.guildId),F.owned(snapshot(i.guildId),ref,i.user.id));
 }
 async function recover(guild){const pending=Object.values(snapshot(guild).mapCleanupMessages||{}).filter(e=>!e.done);if(pending.length)await disable(guild,{messages:pending});}
 return {openModal,component,boxes,grades,form,cleanup,recover};
}
module.exports={controller};
