'use strict';
const http=require('node:http'),crypto=require('node:crypto'),C=require('./constants'),U=require('./ui'),F=require('./forms'),G=require('./gm-service');
const ok=C.requireThat,hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const MAX_BODY=2*1024*1024;
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data));};
async function body(req,limit=MAX_BODY){let n=0;const chunks=[];for await(const b of req){n+=b.length;if(n>limit)G.error('内容超过大小限制。','TOO_LARGE');chunks.push(b);}try{const text=Buffer.concat(chunks).toString('utf8');return JSON.parse(text||'{}',(k,v)=>{if(['__proto__','constructor','prototype'].includes(k))G.error('字段无效。');return v;});}catch(e){if(e.code)throw e;G.error('JSON格式无效。');}}
const fd=(key,label,type='text',values)=>({key,label,type,values});
const ref=(key,label,source)=>({...fd(key,label,'ref'),source});
const enumf=(key,label,values)=>fd(key,label,'choice',values);
function commandSchema(){const commonMap=[ref('mapId','地图','explorations')],commonBattle=[ref('battleId','战斗','battles')],actor=fd('actorId','参战者','actor'),num=(k,l)=>fd(k,l,'number');
  const defs=[];const add=(id,label,fields,group)=>defs.push({id,label,fields,group:group||id.split('.')[0]});
  add('character.key','调整钥匙次数',[ref('uid','角色','players'),fd('itemId','钥匙','inventory'),num('quantity','剩余次数')]);
  add('death.reward','指定未结算击杀经验',[ref('id','死亡记录','deaths'),ref('uid','获得经验角色','players')],'public');
  add('npc.portrait','NPC头像／立绘',[ref('id','NPC模板','npcTemplates'),num('baseVersion','当前版本'),enumf('slot','位置',['avatar','illustration']),fd('uploadId','已上传图片编号'),fd('clear','清除图片','bool')],'content');
  add('map.cleanup','清理已结束地图',[fd('ids','地图','mapList')]);
  add('map.layout','重抽草稿布局',commonMap);
  add('map.link','绑定建筑内部地图',[...commonMap,fd('cell','建筑格'),ref('buildingMapId','内部地图','explorations')]);
  add('map.auto','自动遭遇设置',[...commonMap,fd('cell','格子'),fd('enabled','自动开战','bool')]);
  add('map.transfer','转交未领取容器',[...commonMap,fd('cell','格子'),fd('containerId','容器编号'),ref('uid','接收者','players')]);
  add('map.playerPosition','调整队员探索位置',[...commonMap,ref('uid','队员','players'),fd('cell','目标格')]);
  add('map.playerRemove','移出探索队员',[...commonMap,ref('uid','队员','players')]);
  add('battle.skill','NPC技能授予／移除',[...commonBattle,actor,ref('ref','技能模板（授予）','skillTemplates'),fd('remove','移除（选择实例编号）','bool')]);
  add('character.luck','调整时运',[ref('uid','角色','players'),num('value','基础时运 -9—11')]);
  add('character.delete','销卡',[ref('uid','角色','players'),fd('characterId','角色编号'),fd('reason','销卡理由','long')]);
  add('character.skillRemove','移除战斗技能',[ref('uid','角色','players'),fd('ref','已学技能','learnedSkill')]);
  add('character.checkXP','鉴定技能经验',[ref('uid','角色','players'),ref('ref','技能','checkSkillTemplates'),num('quantity','经验')]);
  add('buyback','GM收购报价',[ref('uid','角色','players'),fd('itemId','背包物品','inventory'),num('quantity','数量'),num('price','总价'),fd('channelId','操作频道','channel')],'character');
  add('map.create','创建地图',[fd('name','名称'),fd('channelId','公开频道','channel'),enumf('mapType','类型',['indoor','region']),enumf('mode','生成方式',['full','manual','fixed']),ref('categoryId','大类','mapCategories'),num('rows','层／行数'),num('width','列数'),num('blockedPercent','阻挡百分比'),num('stairsMin','最少楼梯'),num('stairsMax','最多楼梯'),num('maxRank','等级上限')]);
  add('map.quickCreate','快速创建地图草稿',[fd('name','名称'),fd('channelId','公开频道','channel'),enumf('mapType','类型',['indoor','region']),enumf('mode','生成方式',['full','manual','fixed']),ref('categoryId','大类','mapCategories'),num('rows','层／行数'),num('width','列数'),num('blockedPercent','阻挡百分比'),num('stairsMin','最少楼梯'),num('stairsMax','最多楼梯'),num('maxRank','等级上限')]);
  for(const [action,label]of Object.entries({generate:'生成房间',publish:'发布地图',pause:'暂停地图',resume:'恢复地图',end:'结束地图'}))add('map.'+action,label,commonMap);
  add('map.cell','编辑地图格子',[...commonMap,num('x','列（从0开始）'),num('y','行（从0开始）'),fd('type','格子类型'),ref('categoryId','大类','mapCategories'),ref('templateId','房间','roomTemplates'),fd('variantId','变种编号'),fd('name','地点名称'),fd('description','地点说明','long'),fd('passable','允许通行','bool'),fd('hasContents','生成内容','bool'),ref('buildingMapId','内部地图','explorations')]);
  add('map.encounter','确认普通遭遇',[...commonMap,fd('cell','格子 x,y'),fd('users','参战玩家','playerList')]);add('map.resolve','解除／结束本批遭遇',[...commonMap,fd('cell','格子 x,y')]);
  add('map.boss','分配BOSS房',[...commonMap,fd('cell','格子 x,y'),ref('poolId','BOSS池','bossPools')]);add('map.bossClear','移除未进入BOSS房',[...commonMap,fd('cell','格子 x,y')]);
  add('map.bossConfirm','确认BOSS开战',[...commonMap,fd('cell','格子 x,y'),fd('requestId','确认请求编号'),num('requestVersion','请求版本')]);
  add('map.merchant','分配行商',[...commonMap,fd('cell','格子 x,y'),ref('templateId','行商模板','merchantTemplates')]);add('map.merchantClear','移除未进入行商',[...commonMap,fd('cell','格子 x,y')]);
  add('map.restock','行商补货',[...commonMap,fd('cell','格子 x,y'),ref('templateId','物品','catalog'),num('quantity','追加库存'),num('buyQuota','追加收购额度')]);
  add('map.rp','发布环境RP／取消等待',[...commonMap,fd('rpId','RP编号'),num('rpVersion','RP版本'),fd('description','环境描述','long'),fd('skip','取消等待','bool')]);add('map.rpEnabled','设置环境RP',[...commonMap,fd('enabled','启用','bool')]);
  add('battle.create','战斗招募',[fd('name','名称'),fd('channelId','战斗频道','channel'),num('width','列数'),num('height','行数')]);
  for(const [action,label]of Object.entries({start:'开战',pause:'暂停',resume:'恢复',finish:'代结束机会',end:'结束战斗'}))add('battle.'+action,label,[...commonBattle,...(action==='start'?[enumf('surprise','偷袭',['','ally','enemy'])]:[])]);
  add('battle.npc','添加NPC',[...commonBattle,ref('templateId','NPC','npcTemplates'),enumf('team','阵营',['ally','enemy'])]);add('battle.reinforce','玩家援军',[...commonBattle,ref('uid','角色','players')]);
  add('battle.position','调整位置／阵营',[...commonBattle,actor,num('x','横坐标（米）'),num('y','纵坐标（米）'),enumf('team','阵营',['ally','enemy'])]);
  add('battle.terrain','地形编辑',[...commonBattle,num('x','列（从1开始）'),num('y','行（从1开始）'),enumf('type','地形',['normal','difficult','blocked'])]);
  add('battle.hp','调整双血条',[...commonBattle,actor,enumf('bar','血条',['normal','reserve']),num('value','生命值')]);
  add('battle.condition','施加异常',[...commonBattle,actor,ref('templateId','异常','conditionTemplates'),enumf('severity','等级',C.SEVERITIES)]);add('battle.clearCondition','解除异常',[...commonBattle,actor,fd('conditionId','异常','conditionInstance')]);
  add('battle.remove','移出参战者',[...commonBattle,actor]);add('battle.ai','NPC自动行动设置',[...commonBattle,actor,fd('ai','AI配置','object')]);add('battle.equip','NPC装备',[...commonBattle,actor,fd('itemId','物品','inventory'),enumf('hand','位置',['auto','main','off']),fd('remove','卸下','bool')]);
  add('battle.action','NPC实际行动',[...commonBattle,actor,enumf('action','行动',Object.keys(require('./action-drafts').labels)),fd('params','行动参数','object'),fd('rp','RP','long')]);
  add('battle.rescue','救援事件',[...commonBattle,fd('judgmentId','裁决编号'),num('judgmentVersion','裁决版本'),fd('refs','受益参战者编号','list'),num('amount','每人治疗量'),fd('rp','救援RP','long')]);
  add('battle.partyDeath','全队死亡裁决',[...commonBattle,fd('judgmentId','裁决编号'),num('judgmentVersion','裁决版本'),fd('reason','理由','long')]);add('battle.death','明确判死',[...commonBattle,actor,fd('reason','理由','long')]);
  add('text.save','发布正文',[enumf('key','章节',require('./texts').definitions().map(x=>({value:x.key,label:x.label}))),num('baseVersion','当前版本'),fd('text','正文','long')],'content');
  add('container.set','容器档位与启用',[enumf('name','容器',C.BOXES),enumf('grade','档位',C.RARITIES.map(r=>({value:r.id,label:r.name}))),fd('enabled','启用','bool')],'content');add('container.rates','六色概率',[enumf('grade','档位',C.RARITIES.map(r=>({value:r.id,label:r.name}))),fd('rates','白绿蓝紫金红概率','list')],'content');
  add('check.create','发布鉴定',[fd('channelId','频道','channel'),fd('data','鉴定配置','object')],'public');add('check.end','结束鉴定',[ref('id','鉴定','checks')],'public');
  add('session.create','发布开团',[fd('channelId','频道','channel'),fd('data','团名／说明／北京时间','object')],'public');add('session.edit','修改开团',[ref('id','开团','sessions'),num('baseVersion','版本'),fd('data','团名／说明／北京时间','object')],'public');add('session.retry','核对后补发未送达提醒',[ref('id','开团','sessions'),fd('absent','已核对提醒没有送达','bool')],'public');add('session.close','关闭开团报名',[ref('id','开团','sessions')],'public');add('session.delivered','核对提醒已送达',[ref('id','开团','sessions')],'public');add('session.cancel','取消开团',[ref('id','开团','sessions')],'public');
  add('config.save','跑团配置',[fd('data','配置','object')],'config');add('storage.recover','读取权威存档',[],'public');
  add('publication.repair','核对／补发公示',[enumf('kind','类型',['battle','map','loot','check','session','gmNotice','rolepanel','corpse','attempt','move','rp','rpDraft']),fd('ref','对象编号'),num('partIndex','开箱分段（从0开始）'),fd('messageId','核实存在的消息ID（可空）'),fd('absent','已检查频道，确认没有消息','bool')],'public');
  return defs;
}
function createGmWeb(ctx){const {store,client,snapshot,needGM,needConfig,textChannel,safeRoles,metrics}=ctx;let server;const pending=new Map(),authFlights=new Map(),limits=new Map();
  const enabled=()=>process.env.GM_WEB_ENABLED==='1';
  function state(g){return store.select(g,s=>({revision:s.revision,config:s.config}));}
  function livePermission(a,s,command){const m=a.guild.members.cache?.get(a.device.userId)||a.member;needGM(s,m);if(command==='config.save'||command==='templates.publish'&&a.configCommand)needConfig(m);}
  async function member(g,u){ok(client.isReady?.()!==false,'Discord连接未就绪，暂不能核验GM身份。');const key=g+':'+u;if(authFlights.has(key))return authFlights.get(key);const job=(async()=>{const guild=await client.guilds.fetch(g),m=await Promise.race([guild.members.fetch({user:u,force:true}),new Promise((_,reject)=>{const t=setTimeout(()=>reject(Error('暂时无法核验Discord权限，请稍后。')),8000);t.unref?.();})]);needGM(state(g),m);return {guild,member:m};})();authFlights.set(key,job);try{return await job;}finally{authFlights.delete(key);}}
  async function bindCommand(i){ok(enabled(),'网页入口尚未启用。');needGM(snapshot(i.guildId),i.member);const code='GW-'+crypto.randomBytes(16).toString('hex'),id=C.id('f');await store.transact(i.guildId,'gm-web-bind:'+i.id,i.user.id,s=>{s.forms[id]={id,kind:'gmWebBind',owner:i.user.id,hash:hash(code),expiresAt:Date.now()+600000};return {id};},'创建私密网页绑定');const devices=store.select(i.guildId,s=>Object.values(s.gmWebDevices||{}).filter(d=>d.userId===i.user.id&&!d.revokedAt&&d.expiresAt>Date.now()).slice(0,20));return U.payload('本地GM工作台','绑定码（10分钟内有效，仅用于你自己的电脑）：\n`'+code+'`\n\n服务地址：'+(process.env.GM_WEB_PUBLIC_URL||'由启动包提供')+'\n设备有效期30天；每次操作仍核验GM权限。',[...(devices.length?[U.row(U.select('gmweb:revoke','撤销已绑定设备',devices.map(d=>({label:d.name,value:d.id}))))]:[])]);}
  async function component(i){needGM(snapshot(i.guildId),i.member);await store.transact(i.guildId,'gm-web-revoke:'+i.id,i.user.id,s=>{const d=s.gmWebDevices[i.values[0]];ok(d?.userId===i.user.id,'设备不属于你。');d.revokedAt=Date.now();return {revoked:d.id};},'撤销网页设备');return U.payload('设备已撤销','该电脑须重新绑定才能操作。');}
  async function pair(p){ok(/^GW-[a-f0-9]{32}$/.test(p.code||'')&&/^[a-zA-Z0-9-]{20,60}$/.test(p.deviceId||'')&&/^[a-f0-9]{64}$/.test(p.credentialHash||''),'绑定信息无效。');let found;for(const g of store.guilds()){const f=store.select(g,s=>Object.values(s.forms).find(f=>f.kind==='gmWebBind'&&f.hash===hash(p.code)));if(f){found={g,f};break;}}ok(found,'绑定码无效。');const {g,f}=found,{guild,member:gmMember}=await member(g,f.owner);
    await store.transact(g,'gm-web-pair:'+p.deviceId,f.owner,s=>{needGM(s,guild.members.cache?.get(f.owner)||gmMember);const live=s.forms[f.id];ok(live&&!live.done&&live.expiresAt>Date.now(),'绑定码已使用或过期。');ok(Object.values(s.gmWebDevices).filter(d=>d.userId===f.owner&&!d.revokedAt&&d.expiresAt>Date.now()).length<20,'请先撤销旧设备。');ok(!s.gmWebDevices[p.deviceId],'设备编号冲突。');live.done=true;s.gmWebDevices[p.deviceId]={id:p.deviceId,userId:f.owner,credentialHash:p.credentialHash,name:C.text(p.deviceName||'本地电脑','设备名称',80),createdAt:Date.now(),expiresAt:Date.now()+30*86400000};return {paired:p.deviceId};},'绑定GM网页设备',{delivery:false});
    const d=store.select(g,s=>s.gmWebDevices[p.deviceId]);ok(d?.credentialHash===p.credentialHash&&!d.revokedAt,'设备凭证不匹配。');return {guildId:g,guildName:guild.name,userId:f.owner,expiresAt:d.expiresAt};
  }
  async function authenticate(req){const a=/^Bearer ([0-9]{17,20})\.([a-zA-Z0-9-]{20,60})\.([a-f0-9]{64})$/.exec(req.headers.authorization||'');if(!a)G.error('请先绑定本地电脑。','UNAUTHORIZED');const [,g,id,secret]=a;ok(store.guilds().includes(g),'服务器未启用。');const d=store.select(g,s=>s.gmWebDevices?.[id]);if(!d||d.revokedAt||d.expiresAt<=Date.now()||!crypto.timingSafeEqual(Buffer.from(d.credentialHash,'hex'),Buffer.from(hash(secret),'hex')))G.error('登录已失效，请重新绑定。','UNAUTHORIZED');const m=await member(g,d.userId);return {g,device:d,...m};}
  async function preflight(a,command,p){const s=snapshot(a.g),rows=G.rowsFor(command,p);const configured=command==='config.save'||(command==='templates.publish'&&rows.some(r=>r.kind==='rolepanel'));a.configCommand=configured;if(configured)needConfig(a.member);
    if(p.channelId){const ch=await textChannel(a.g,p.channelId);ok(ch.permissionsFor(client.user).has(U.D.PermissionFlagsBits.ViewChannel|U.D.PermissionFlagsBits.SendMessages),'Bot无法查看或发送该频道。');}
    if(command==='templates.publish')for(const r of rows)if(r.kind==='rolepanel')await safeRoles(a.guild,r.data.roleIds,s);
    if(command==='config.save'){ok(p.data&&Object.keys(p.data).every(k=>['gmRoleIds','playerRoleIds','announcementChannelId','rpChannelId'].includes(k)),'配置字段无效。');for(const k of ['gmRoleIds','playerRoleIds'])if(p.data[k]){ok(Array.isArray(p.data[k])&&p.data[k].length<=10,'身份组选择无效。');await a.guild.roles.fetch();ok(p.data[k].every(id=>id!==a.g&&a.guild.roles.cache.has(id)),'身份组不存在。');}for(const k of ['announcementChannelId','rpChannelId'])if(p.data[k])await textChannel(a.g,p.data[k]);}
    if(['map.boss','map.bossConfirm','map.rp','map.rpEnabled'].includes(command)&&!p.skip&&p.enabled!==false||command==='config.save'&&s.config.rpChannelId){const next={...s,config:{...s.config,...(command==='config.save'?p.data:{})}},ch=await textChannel(a.g,next.config.rpChannelId);await require('./rp').verifyChannel(a.guild,ch,next);}
    if(command==='buyback')ok(p.channelId,'请选择收购操作频道。');
    if(command==='publication.repair'){ok(p.absent||p.messageId,'须核对频道并确认无消息，或输入核实存在的消息编号。');await ctx.checkPublication(a,p);}
  }
  function read(a,source,q){const allowed=new Set([...Object.values(G.KINDS),'players','explorations','battles','offers','checks','sessions','lootPublications','deaths','corpses','deliveryJobs','forms','events','containerDefinitions','couponRedemptions','merchantTrades']);ok(allowed.has(source),'查询类型无效。');const id=q.get('id');return store.select(a.g,s=>{let all=Object.values(s[source]||{});if(source==='forms')all=all.filter(f=>f.owner===a.device.userId&&!['gmWebBind'].includes(f.kind));if(source==='events')all=all.map(e=>({id:e.id,at:e.at,actorId:e.actorId,label:e.label,revision:e.revision,result:e.result}));if(id){const item=all.find(x=>x.id===id||x.userId===id||x.key===id);ok(item,'对象不存在或无权查看。');return {revision:s.revision,item:source==='players'?{...item,stats:require('./model').stats(item)}:item};}const search=(q.get('q')||'').normalize('NFKC').toLowerCase(),cat=q.get('category');all=all.filter(t=>(t.name||t.title||t.label||t.key||t.id||'').normalize('NFKC').toLowerCase().includes(search));if(source==='catalog'&&cat)all=all.filter(t=>require('./item-categories').matches(t,cat,true));if(source==='events')all.reverse();const page=C.number(q.get('page')||0,'页',0,100000),size=C.number(q.get('size')||25,'每页数量',1,100);return {revision:s.revision,total:all.length,page,items:all.slice(page*size,(page+1)*size).map(t=>source==='players'?{id:t.id,userId:t.userId,name:t.name,hp:t.hp,life:t.life,balance:t.balance,points:t.points,stats:require('./model').stats(t)}:t)};});}
  async function route(req,res){if(!enabled())return json(res,503,{error:{code:'DISABLED',message:'网页入口已关闭。'}});const started=performance.now(),url=new URL(req.url,'http://api.local'),path=url.pathname.replace(/^\/api\/gm\/v1/,'');
    const key=req.headers.authorization?'device:'+hash(req.headers.authorization):req.socket.remoteAddress||'local',now=Date.now();let rate=limits.get(key);if(!rate||now-rate.at>60000){rate={at:now,n:0};limits.set(key,rate);}if(limits.size>2000)for(const [k,v]of limits)if(now-v.at>60000)limits.delete(k);if(++rate.n>240)return json(res,429,{error:{code:'RATE_LIMIT',message:'操作过于频繁，请稍后。'}});
    try{ok(url.pathname.startsWith('/api/gm/v1/'),'接口不存在。');if(req.method==='POST'&&path==='/pair')return json(res,200,{data:await pair(await body(req))});const a=await authenticate(req);metrics?.observe('gmWeb.accept',performance.now()-started);
      if(req.method==='GET'&&path==='/session'){const s=state(a.g);return json(res,200,{data:{...s,guildId:a.g,guildName:a.guild.name,userId:a.device.userId,userName:a.member.displayName,deviceId:a.device.id,expiresAt:a.device.expiresAt,frozen:!!store.frozen(a.g),canConfig:a.member.permissions.has(U.D.PermissionFlagsBits.ManageGuild)}});}
      if(req.method==='POST'&&path==='/portraits'){const p=await body(req,6*1024*1024);ok(/^[a-zA-Z0-9-]{20,60}$/.test(p.uploadId||''),'上传编号无效。');ok(['avatar','illustration'].includes(p.slot),'图片位置无效。');const bytes=Buffer.from(p.data||'','base64');require('./portraits').format(bytes);const id='f'+hash(p.uploadId).slice(0,24),old=store.select(a.g,s=>s.forms[id]);if(old){ok(old.owner===a.device.userId&&old.npcId===p.npcId&&old.slot===p.slot&&old.hash===hash(bytes),'上传编号冲突。');ok(old.status==='done','该次上传结果待核对，不能自动重发。');return json(res,200,{data:old});}const f=await store.transact(a.g,'gm-web-image-intent:'+id,a.device.userId,s=>{livePermission(a,s);const npc=s.npcTemplates[p.npcId];ok(npc,'先选择NPC模板。');const f={id,kind:'gmWebPortrait',owner:a.device.userId,npcId:npc.id,slot:p.slot,baseVersion:npc.version,assetId:C.id('image'),hash:hash(bytes),status:'sending',at:Date.now()};s.forms[id]=f;return f;},'网页图片上传意图',{delivery:false});try{const ref=await ctx.portraits.upload(a.g,a.device.userId,{size:bytes.length,bytes,id:f.assetId});const saved=await store.transact(a.g,'gm-web-image-sent:'+id,a.device.userId,s=>{const live=s.forms[id];live.status='done';live.ref=ref;return live;},'网页图片加密保存',{delivery:false});return json(res,200,{data:saved});}catch(e){await store.transact(a.g,'gm-web-image-uncertain:'+id,a.device.userId,s=>{s.forms[id].status='uncertain';},'网页图片待核对',{delivery:false}).catch(()=>{});throw e;}}
      if(req.method==='POST'&&path==='/recover'){livePermission(a,state(a.g));await store.recover(a.g);return json(res,200,{data:{revision:state(a.g).revision,status:'recovered'}});}
      if(req.method==='GET'&&path==='/context/battle')return json(res,200,{data:store.select(a.g,s=>require('./gm-context-data').battle(s,url.searchParams.get('id'),url.searchParams.get('actorId')))});
      if(req.method==='GET'&&path==='/context/maps')return json(res,200,{data:store.select(a.g,s=>require('./gm-context-data').mapOptions(s))});
      if(req.method==='GET'&&path==='/devices')return json(res,200,{data:store.select(a.g,s=>Object.values(s.gmWebDevices).filter(d=>d.userId===a.device.userId).map(({credentialHash,...d})=>d))});
      if(req.method==='POST'&&path==='/devices/revoke'){const p=await body(req);return json(res,200,{data:await store.transact(a.g,'gm-web-revoke:'+crypto.randomUUID(),a.device.userId,s=>{const d=s.gmWebDevices[p.id];ok(d?.userId===a.device.userId,'设备不属于你。');d.revokedAt=Date.now();return {revoked:d.id};},'撤销网页设备',{delivery:false})});}
      if(req.method==='GET'&&path==='/schemas')return json(res,200,{data:{kinds:G.KINDS,commands:commandSchema(),attributeLabels:C.ATTRIBUTES,effectTargets:C.EFFECT_TARGETS.map(value=>({value,label:C.targetLabel(value)})),conditionTargets:C.CONDITION_TARGETS.map(value=>({value,label:C.targetLabel(value)})),severities:C.SEVERITIES,itemKinds:C.ITEM_KINDS.filter(k=>k!=='技能'),boxes:C.BOXES,categories:require('./item-categories').groups.map(([value,label])=>({value,label})),defaults:ctx.defaults()}});
      if(req.method==='POST'&&path==='/fields'){const p=await body(req);ok(G.KINDS[p.kind],'类型无效。');const s=snapshot(a.g);if(['coupon','boss','merchant','glossary'].includes(p.kind))return json(res,200,{data:ctx.specialFields(p.kind)});return json(res,200,{data:[...F.fields({kind:p.kind,data:p.data||F.defaults(p.kind,p.itemKind)}),...(p.kind==='npc'?[{key:'equipmentPreset',label:'初始装备槽位',type:'equipmentPreset'},{key:'ai',label:'自动策略与行动权重',type:'object'}]:[])].map(d=>({...d,predicate:undefined,options:['refs','multi','choice','conditions'].includes(d.type)?F.options(s,d):undefined}))});}
      if(req.method==='GET'&&path==='/directory'){if(!a.guild.channels.cache.size)await a.guild.channels.fetch();if(!a.guild.roles.cache.size)await a.guild.roles.fetch();return json(res,200,{data:{channels:[...a.guild.channels.cache.values()].filter(c=>c?.isTextBased()&&c.send).map(c=>({id:c.id,name:c.name})),roles:[...a.guild.roles.cache.values()].map(r=>({id:r.id,name:r.name})),texts:store.select(a.g,s=>require('./texts').definitions().map(d=>({...d,value:require('./texts').get(s,d.key),version:s.config.textOverrides?.[d.key]?.version||0})))}});}
      if(req.method==='GET'&&path.startsWith('/collections/'))return json(res,200,{data:read(a,path.slice(13),url.searchParams)});
      if(req.method==='POST'&&path==='/template'){const p=await body(req);ok(G.KINDS[p.kind],'类型无效。');const s=snapshot(a.g);let f;if(['coupon','boss','merchant','glossary'].includes(p.kind)){const t=s[G.KINDS[p.kind]][p.id];ok(t,'模板不存在。');f={data:{...t,enabled:t.enabled??t.published},baseVersion:t.version};}else {f=F.create(s,a.device.userId,p.kind,undefined,p.id);f.baseVersion=f.baseTemplateVersion;}return json(res,200,{data:f});}
      if(req.method==='POST'&&path==='/drafts'){const p=await body(req);ok(p.data&&JSON.stringify(p.data).length<=MAX_BODY,'草稿无效。');return json(res,200,{data:await store.transact(a.g,'gm-web-draft:'+crypto.randomUUID(),a.device.userId,s=>{livePermission(a,s);const d=s.gmWebDevices[a.device.id];ok(d&&!d.revokedAt&&d.expiresAt>Date.now(),'设备已撤销。');const prior=p.id&&s.forms[p.id];ok(!p.id||prior?.owner===a.device.userId&&prior.kind==='gmWebDraft','草稿不属于你。');if(prior)G.version(prior.version,p.version);const f={id:p.id||C.id('f'),kind:'gmWebDraft',owner:a.device.userId,data:p.data,version:(prior?.version||0)+1,at:Date.now()};s.forms[f.id]=f;return f;},'保存GM网页草稿',{delivery:false})});}
      if(req.method==='POST'&&path==='/previews'){const p=await body(req);ok(p.command==='templates.publish'||p.command==='grant'||commandSchema().some(c=>c.id===p.command),'操作无效。');ok(p.params&&typeof p.params==='object'&&!Array.isArray(p.params),'参数无效。');await preflight(a,p.command,p.params);return json(res,200,{data:await store.transact(a.g,'gm-web-preview:'+crypto.randomUUID(),a.device.userId,s=>{livePermission(a,s,p.command);const guards=G.guards(s,p.command,p.params),f={id:C.id('f'),kind:'gmWebAction',owner:a.device.userId,deviceId:a.device.id,command:p.command,params:C.clone(p.params),guards,status:'ready',expiresAt:C.confirmationDeadline(300000)};
        if(p.command==='templates.publish'){f.preview=G.validateBatch(s,p.params.rows,a.device.userId);f.canCommit=f.preview.every(r=>r.success);}
        else if(p.command==='grant')f.preview=G.grantBatch(C.clone(s),p.params.rows);
        else if(p.command==='battle.rescue'){const b=s.battles[p.params.battleId];f.preview=p.params.refs.map(id=>{const actor=require('./combat').actorById(b,id),player=require('./combat').actorCharacter(s,actor);return {name:actor.name,...require('./health').heal(C.clone(player),p.params.amount)};});}
        else f.preview=require('./gm-web-preview').preview(s,a.device.userId,p.command,p.params);
        if(p.command==='templates.publish'){f.differences=p.params.rows.filter(r=>r.id).map(r=>({id:r.id,before:s[G.KINDS[r.kind]][r.id],after:r.data}));}
        if(p.command==='battle.action'&&p.params.action==='defend'){const hit=require('./aoe').hit(s.battles[p.params.battleId],p.params.params.hitId);ok(hit,'受击已失效。');f.expiresAt=Math.min(f.expiresAt,hit.expiresAt);}
        s.forms[f.id]=f;return f;},'GM网页操作预览',{delivery:false})});}
      if(req.method==='POST'&&path==='/commands'){const p=await body(req),f=store.select(a.g,s=>s.forms[p.draftId]);ok(f?.kind==='gmWebAction'&&f.owner===a.device.userId&&f.deviceId===a.device.id,'确认不属于本设备。');const operation='gm-web:'+f.id;
        if(pending.has(operation))return json(res,202,{data:{operationId:operation,status:'processing'}});const old=store.select(a.g,s=>s.receipts[operation]?.result||s.forms[f.id]?.result);if(old)return json(res,200,{data:old});ok(f.status==='ready'&&f.expiresAt>Date.now(),'确认已失效，请重新预览。');await preflight(a,f.command,f.params);if(pending.has(operation))return json(res,202,{data:{operationId:operation,status:'processing'}});
        const job=(async()=>{if(f.command==='storage.recover')await store.recover(a.g);return store.transact(a.g,operation,a.device.userId,s=>{livePermission(a,s,f.command);const live=s.forms[f.id],device=s.gmWebDevices[a.device.id];ok(device&&!device.revokedAt&&device.expiresAt>Date.now(),'设备已撤销。');ok(live?.status==='ready'&&live.expiresAt>Date.now()&&live.canCommit!==false,'确认已失效或清单仍有错误。');G.verifyGuards(s,live.guards);let result;if(live.command==='storage.recover')result={revision:s.revision};else if(live.command==='publication.repair')result=ctx.repairPublication(s,a,live.params);else result=G.apply(s,a.device.userId,live.command,live.params);if(live.command==='buyback')s.offers[result.id].channelId=live.params.channelId;if(live.command==='templates.publish')for(const r of result)if(r.kind==='rolepanel')require('./outbox').put(s,'rolepanel',r.id,{priority:2});live.status='done';live.done=true;live.result={operationId:operation,status:'committed',result};return live.result;},'GM网页 · '+f.command);})();pending.set(operation,job);try{const result=await job;metrics?.observe('gmWeb.result',performance.now()-started);return json(res,200,{data:result});}finally{pending.delete(operation);}}
      if(req.method==='GET'&&path.startsWith('/operations/')){const id=decodeURIComponent(path.slice(12));ok(/^gm-web:f[a-f0-9]+$/.test(id),'操作编号无效。');const fid=id.slice(7);const result=store.select(a.g,s=>{const f=s.forms[fid];ok(f?.owner===a.device.userId&&f.deviceId===a.device.id,'操作不属于你。');return s.receipts[id]?.result||f.result||{operationId:id,status:pending.has(id)?'processing':store.frozen(a.g)?'uncertain':f.status==='ready'?'uncommitted':f.status};});return json(res,200,{data:result});}
      if(req.method==='GET'&&path.startsWith('/media/')){const result=await ctx.media(a,path.slice(7),url.searchParams);res.writeHead(200,{'content-type':result.type,'cache-control':'private, max-age=20','x-content-type-options':'nosniff'});return res.end(result.bytes);}
      G.error('接口不存在。','NOT_FOUND');
    }catch(e){const code=e.code||(/存档写入|运行锁|已暂停修改/.test(e.message)?'FROZEN':/权限|需要.*GM|身份组|不属于/.test(e.message)?'FORBIDDEN':'VALIDATION');json(res,({UNAUTHORIZED:401,FORBIDDEN:403,NOT_FOUND:404,CONFLICT:409,TOO_LARGE:413,FROZEN:503}[code]|| (store.guilds().some(g=>store.frozen(g))?503:422)),{error:{code,message:e.message||'操作失败，原输入已保留。',details:e.details}});}
  }
  function start(){if(!enabled()||server)return;server=http.createServer((req,res)=>{route(req,res).catch(()=>{if(!res.writableEnded)json(res,500,{error:{code:'INTERNAL',message:'接口异常，请查询操作回执。'}});});});server.requestTimeout=30000;server.headersTimeout=10000;server.listen(Number(process.env.PORT||process.env.GM_WEB_PORT||3000),'::');server.on('error',e=>ctx.logFailure?.('GM网页接口启动失败。',e));}
  function stop(){server?.close();server?.closeIdleConnections();server=null;}
  async function drain(){await Promise.allSettled([...pending.values()]);}
  return {start,stop,drain,route,bindCommand,component,pair,preflight,read,pending};
}
module.exports={createGmWeb,commandSchema,body,MAX_BODY};
