'use strict';
const path=require('node:path'),{Worker}=require('node:worker_threads'),{createHash}=require('node:crypto');
const FONT=path.join(__dirname,'../../assets/fonts/NotoSansCJKsc-Regular.otf');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const clip=(s,n=16)=>[...String(s||'')].slice(0,n).join('')+([...String(s||'')].length>n?'…':'');
const text=(s,x,y,size=16,color='#c8d9e5',extra='')=>`<text x="${x}" y="${y}" font-size="${size}" fill="${color}" ${extra}>${esc(s)}</text>`;
const rect=(x,y,w,h,fill,stroke='',r=0)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="${fill}" ${stroke?`stroke="${stroke}"`:''}/>`;
const colors={room:'#254650',corridor:'#243747',stairs:'#635282',entrance:'#20594e',wall:'#35434e',road:'#404852',wild:'#314b41',forest:'#254336',ruins:'#594a43',water:'#244e67',mountain:'#4b4b51',landmark:'#63593e',building:'#35516b',fog:'#15232d'};
const labels={room:'房间',corridor:'走廊',stairs:'楼梯',entrance:'入口',wall:'墙体',road:'道路',wild:'野地',forest:'森林',ruins:'废墟',water:'水域',mountain:'山地',landmark:'地标',building:'建筑'};
function base(w,h,title,sub){return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" font-family="Noto Sans CJK SC"><defs><pattern id="texture" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M0 10L10 0" stroke="#ffffff" stroke-opacity=".025"/></pattern><pattern id="trees" width="18" height="18" patternUnits="userSpaceOnUse"><path d="M9 3L15 13H3Z" fill="#82ad7e" opacity=".14"/></pattern></defs>${rect(0,0,w,h,'#0c1822')}${rect(18,18,w-36,h-36,'#12232f','#2a4455',16)}<path d="M32 74H${w-32}" stroke="#42bac8" stroke-width="2"/>${text(title,34,48,24,'#eef7f8')}${text(sub,34,67,12,'#88a7b7')}`;}
function bar(x,y,w,value,max){const ratio=Math.max(0,Math.min(1,value/Math.max(1,max)));return rect(x,y,w,5,'#293c48','',2)+rect(x,y,w*ratio,5,ratio>.5?'#58d0a0':ratio>.2?'#ecc171':'#ef7777','',2);}
function token(n,a,x,y,r,avatar,current){const color=a.team==='enemy'?'#f17a7e':'#53bcf5',cid='portrait'+n;return `<defs><clipPath id="${cid}"><circle cx="${x}" cy="${y}" r="${r-2}"/></clipPath></defs>`+(current?`<circle cx="${x}" cy="${y}" r="${r+5}" fill="none" stroke="#f7d781" stroke-width="2"/>`:'')+`<circle cx="${x}" cy="${y}" r="${r}" fill="#203747" stroke="${color}" stroke-width="2"/>`+(avatar?`<image x="${x-r+2}" y="${y-r+2}" width="${r*2-4}" height="${r*2-4}" xlink:href="${avatar}" clip-path="url(#${cid})"/>`+rect(x+r*.3,y+r*.25,r*.8,14,'#142735',color,4)+text(String(n).replace(/^side/,''),x+r*.7,y+r*.25+11,10,'#ffffff','text-anchor="middle"'):text(String(n).replace(/^side/,''),x,y+5,Math.max(12,r*.65),'#ffffff','text-anchor="middle"'));}
function explorationSVG(m,full=false,floor=null,wide=false){const region=m.mapType==='region',current=Object.values(m.participants)[0]?.cell?.split(',').map(Number)||[0,0],chosen=floor===null?current[1]:Math.max(0,Math.min(Number(floor)||0,m.floors-1));const size=Math.max(20,Math.min(region?90:140,Math.floor((wide?1060:540)/m.width))),levels=region?Array.from({length:m.floors},(_,n)=>n):[chosen],left=50,top=130,gw=m.width*size,gh=levels.length*size,overview=region?0:m.floors*15+55,w=Math.max(640,gw+100),h=gh+overview+(region?260:215);let svg=require('./tactical-art').base(w,h,(region?'区域地图':'建筑内部')+' · '+clip(m.name,28),region?'共同探索 · 道路 / 建筑 / 水域 · 蓝点队伍':'第 '+(chosen+1)+' 层 · 已探索区域共享 · 蓝点队伍 / ?迷雾');
 levels.forEach((y,row)=>{svg+=text(region?y+1:(y+1)+'F',30,top+row*size+size/2+5,13,'#97b7c6','text-anchor="middle"');for(let x=0;x<m.width;x++){const ref=x+','+y,c=m.cells[ref],seen=full||m.revealed[ref],px=left+x*size,py=top+row*size;if(!c){if(!row)svg+=text(x+1,px+size/2,top-14,12,'#9bb6c6','text-anchor="middle"');continue;}svg+=rect(px,py,size-2,size-2,seen&&c?colors[c.type]||colors.room:colors.fog,'#3a5361',region?3:1);if(!row)svg+=text(x+1,px+size/2,top-14,12,'#9bb6c6','text-anchor="middle"');
 if(!c)continue;
 const rpHidden=!full&&m.rpPendingId&&m.rps?.[m.rpPendingId]?.cell===ref&&require('./rp').waiting(m);if(!seen||rpHidden){svg+=text(rpHidden?'等待描述':'?',px+size/2,py+size/2+6,rpHidden?Math.min(15,size/5):20,'#4e6472','text-anchor="middle"');continue;}if(!c)continue;
 svg+=rect(px,py,size-2,size-2,'url(#floor)');
 if(!region){if(c.type==='room')svg+=`<path d="M${px+4} ${py+size-2}H${px+size*.4}M${px+size*.6} ${py+size-2}H${px+size-3}" stroke="#b8c9cd" stroke-width="4"/><path d="M${px+size*.4} ${py+size-3}v-${size*.2}" stroke="#e4c58b" stroke-width="2"/>`;if(c.type==='stairs')for(let i=0;i<5;i++)svg+=`<path d="M${px+10+i*3} ${py+13+i*7}h${size-26-i*2}" stroke="#c7bbde" stroke-width="2"/>`;if(c.type==='corridor')svg+=`<path d="M${px+5} ${py+size/2}H${px+size-7}" stroke="#7894a5" stroke-dasharray="4 4"/>`;}
 if(!region&&c.type==='room'){const name=(c.room?.snapshot?.obstacles||require('./encounter-layout').defaults(c.room?.snapshot||{id:c.room?.templateId})).names.split(/[、,，]/)[0];svg+=require('./tactical-art').obstacle(name,px+size*.08,py+size*.03,size*.68,'decor');}
 if(region){const mid=px+size/2,yy=py+size/2;if(c.type==='road')svg+=`<path d="M${px} ${yy}H${px+size}" stroke="#a3ac93" stroke-width="${size*.22}"/><path d="M${px} ${yy}H${px+size}" stroke="#ddd09b" stroke-dasharray="6 5"/>`;if(c.type==='water')for(let n=0;n<3;n++)svg+=`<path d="M${px+8} ${py+15+n*size*.15}q${size*.2} -6 ${size*.4} 0t${size*.4} 0" fill="none" stroke="#7cbbcb" opacity=".6"/>`;if(c.type==='forest')for(let n=0;n<3;n++)svg+=`<path d="M${px+size*(.18+n*.27)} ${py+size*.12}l-${size*.14} ${size*.38}h${size*.28}Z" fill="#659877" stroke="#abc29b"/>`;if(c.type==='building')svg+=rect(px+size*.2,py+size*.18,size*.6,size*.42,'#677b70','#b7be9e',3);}

 if(c.room?.merchant)svg+=rect(px+size*.13,py+size*.2,size*.55,size*.24,'#876239','#efce7b',3)+`<path d="M${px+size*.1} ${py+size*.2}l${size*.07} -${size*.1}h${size*.47}l${size*.07} ${size*.1}Z" fill="#ca9566"/>`+text('商',px+size*.4,py+size*.4,Math.max(10,size*.13),'#ffdf88','text-anchor="middle"');
 if(c.type==='wall'||c.passable===false)svg+=`<path d="M${px+6} ${py+6}L${px+size-8} ${py+size-8}M${px+size-8} ${py+6}L${px+6} ${py+size-8}" stroke="#df9e89" stroke-width="2" opacity=".65"/>`;
 const name=rpHidden?'等待描述':c.room?.merchant?.name||c.name||c.room?.snapshot.name||labels[c.type]||c.type;svg+=text(clip(name,Math.max(2,Math.floor(size/13))),px+size/2,py+size-9,region?11:13,'#d5e4e9','text-anchor="middle"');if(c.passable===false)svg+=text('×',px+size/2,py+size/2+5,18,'#e89790','text-anchor="middle"');
 if(!rpHidden&&c.room&&c.room.encounter!=='resolved')svg+=text('!',px+size-10,py+17,16,'#ff9a7a','text-anchor="middle"');if(c.type==='building'&&c.buildingMapId)svg+=text('门',px+11,py+17,15,'#abd8fa');const members=Object.values(m.participants).filter(p=>p.cell===ref);if(members.length)svg+=`<circle cx="${px+size/2}" cy="${py+size*.4}" r="${size*.19}" fill="#3aa5dd" stroke="#a6dfff" stroke-width="2"/>`+text(members.length,px+size/2,py+size*.4+5,14,'#ffffff','text-anchor="middle"');}});
 let yy=top+gh+27;if(!region){svg+=text('全楼层总览',left,yy,13,'#77c6d3');yy+=18;for(let y=m.floors-1;y>=0;y--){svg+=text((y+1)+'F',left,yy+10,10);for(let x=0;x<m.width;x++){const ref=x+','+y,c=m.cells[ref],seen=full||m.revealed[ref];if(!c)continue;svg+=rect(left+32+x*15,yy,13,11,seen?colors[c?.type]||'#12222d':colors.fog,y===chosen?'#e6cc83':'#354959');}yy+=15;}}
 svg+=text((m.rpEnabled?'RP开启 · ':'')+(require('./rp').waiting(m)?'等待GM环境描述 · ':'')+'图例：蓝点 队伍 · ? 迷雾 · ! 遭遇 · 商 行商 · × 禁行 · 门 建筑入口',left,yy+24,12,'#9fbfc9')+text('已探索 '+Object.keys(m.revealed).length+'格 · 队员 '+Object.keys(m.participants).length+' 人'+(m.excursion?' · 队伍在建筑内部':''),left,yy+49,13,'#b9d9df')+text(clip(m.lastEvent||'等待全队确认下一步移动',Math.floor((w-100)/13)),left,yy+73,12);return svg+'</svg>';}
const art=require('./tactical-art'),battleSVG=art.battleSVG,eventSVG=art.eventSVG;
function renderSVG(svg){return new(require('@resvg/resvg-js').Resvg)(svg,{font:{fontFiles:[FONT],loadSystemFonts:false,defaultFontFamily:'Noto Sans CJK SC'}}).render().asPng();}
function battle(state,b){return renderSVG(battleSVG(state,b));}function exploration(m,full=false,floor=null){return renderSVG(explorationSVG(m,full,floor));}
function attach(v,buffer,name){v.files=[...(v.files||[]),{attachment:buffer,name}];v.attachments=[];v.embeds[0].setImage('attachment://'+name);return v;}
function prepare(v,descriptor){v.rpgMap=descriptor;v.embeds[0].setImage('attachment://tactical-map.png');return v;}
function createRenderer({portraits,logFailure,metrics}){const cache=new Map(),jobs=[],avatarCache=new Map(),inflight=new Map(),avatarInflight=new Map(),workers=Array.from({length:2},()=>({worker:null,job:null}));let bytes=0,closed=false;
 async function avatarUncached(guild,ref){const key=guild+':'+ref.id;try{const input=await portraits.load(guild,ref),buffer=await require('sharp')(input,{limitInputPixels:20000000}).rotate().resize(96,96,{fit:'cover'}).png().toBuffer();const uri='data:image/png;base64,'+buffer.toString('base64');avatarCache.set(key,uri);while(avatarCache.size>40)avatarCache.delete(avatarCache.keys().next().value);return uri;}catch{return null;}}
 function avatar(guild,ref){if(!ref)return Promise.resolve(null);const key=guild+':'+ref.id;if(avatarCache.has(key))return Promise.resolve(avatarCache.get(key));if(avatarInflight.has(key))return avatarInflight.get(key);const job=avatarUncached(guild,ref);avatarInflight.set(key,job);job.finally(()=>avatarInflight.delete(key));return job;}
 function queue(svg,options={}){if(closed)return Promise.reject(Error('地图渲染已停止'));const key=createHash('sha256').update(JSON.stringify({svg,options})).digest('hex');if(cache.has(key)){const value=cache.get(key);cache.delete(key);cache.set(key,value);return Promise.resolve(value);}if(inflight.has(key))return inflight.get(key);const promise=new Promise((resolve,reject)=>{if(jobs.length>=16)return reject(Object.assign(Error('地图渲染队列已满'),{code:'RPG_RENDER_BUSY'}));jobs.push({svg,options,key,resolve,reject});drain();});inflight.set(key,promise);promise.finally(()=>inflight.delete(key)).catch(()=>{});return promise;}
 function done(slot,error,result){const job=slot.job;if(!job)return;clearTimeout(job.timer);slot.job=null;metrics?.observe('render.worker',performance.now()-job.started);slot.worker?.unref();if(error)job.reject(error);else{const value=Buffer.from(result);bytes-=cache.get(job.key)?.length||0;cache.set(job.key,value);bytes+=value.length;while(cache.size>16||bytes>24*1024*1024){const key=cache.keys().next().value;bytes-=cache.get(key).length;cache.delete(key);}job.resolve(value);}drain();}
 function spawn(slot){const worker=new Worker(path.join(__dirname,'map-worker.js'),{workerData:{font:FONT}});slot.worker=worker;worker.unref();worker.on('message',data=>{if(slot.worker===worker&&data.id===slot.job?.key)done(slot,data.error?Error(data.error):null,data.png);});const fail=()=>{if(slot.worker!==worker)return;slot.worker=null;done(slot,Error('地图渲染进程异常'));void worker.terminate();drain();};worker.on('error',fail);worker.on('exit',fail);}
 function drain(){if(closed)return;for(const slot of workers){if(slot.job||!jobs.length)continue;if(!slot.worker)spawn(slot);const job=jobs.shift();slot.job=job;job.started=performance.now();job.timer=setTimeout(()=>{const worker=slot.worker;slot.worker=null;void worker?.terminate();done(slot,Error('地图渲染超时'));},15000);slot.worker.ref();slot.worker.postMessage({id:job.key,svg:job.svg,options:job.options});}metrics?.gauge('render.queue',jobs.length);}
 async function decorate(guild,result){const v={...result},d=v.rpgMap;delete v.rpgMap;if(!d)return v;try{let svg,options={};if(d.kind==='battle'){const portraitsByActor={};const actors=d.b.actors;for(let n=0;n<actors.length;n+=4)await Promise.all(actors.slice(n,n+4).map(async a=>{const p=require('./combat').actorCharacter(d.state,a);portraitsByActor[a.id]=await avatar(guild,p.portraits?.avatar);}));svg=battleSVG(d.state,d.b,portraitsByActor,d.overlay,d.zoom,d);}else if(d.kind==='personal')svg=art.personalSVG(d.state,d.b,d.a,await avatar(guild,require('./combat').actorCharacter(d.state,d.a).portraits?.avatar));else if(d.kind==='items')svg=art.itemGridSVG(d.title,d.items);else if(d.kind==='event')return v;else svg=explorationSVG(d.m,d.full,d.floor,d.layout==='wide');const buffer=await queue(svg,options),gif=buffer.subarray(0,3).toString()==='GIF';return attach(v,buffer,gif?'combat-action.gif':'tactical-map.png');}catch(e){if(d.backgroundImage&&e.code==='RPG_RENDER_BUSY')throw e;logFailure('图片生成失败，文字和操作按钮仍可用。',e);v.embeds[0].setImage(null);v.files=v.files||[];return v;}}

 function close(){closed=true;for(const job of jobs.splice(0))job.reject(Error('地图渲染已停止'));for(const slot of workers){done(slot,Error('地图渲染已停止'));void slot.worker?.terminate();slot.worker=null;}}
 return {decorate,avatar,queue,cache,close,workers};}
module.exports={battle,exploration,attach,prepare,battleSVG,explorationSVG,eventSVG,renderSVG,createRenderer,esc};
