'use strict';
const path=require('node:path'),{Worker}=require('node:worker_threads'),{createHash}=require('node:crypto');
const FONT=path.join(__dirname,'../../assets/fonts/NotoSansCJKsc-Regular.otf');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const clip=(s,n=16)=>[...String(s||'')].slice(0,n).join('')+([...String(s||'')].length>n?'…':'');
const text=(s,x,y,size=16,color='#c8d9e5',extra='')=>`<text x="${x}" y="${y}" font-size="${size}" fill="${color}" ${extra}>${esc(s)}</text>`;
const rect=(x,y,w,h,fill,stroke='',r=0)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="${fill}" ${stroke?`stroke="${stroke}"`:''}/>`;
const colors={room:'#254650',corridor:'#243747',stairs:'#635282',entrance:'#20594e',wall:'#35434e',road:'#404852',wild:'#314b41',forest:'#254336',ruins:'#594a43',water:'#244e67',mountain:'#4b4b51',landmark:'#63593e',building:'#35516b',fog:'#15232d'};
const labels={room:'房间',corridor:'走廊',stairs:'楼梯',entrance:'入口',wall:'墙体',road:'道路',wild:'野地',forest:'森林',ruins:'废墟',water:'水域',mountain:'山地',landmark:'地标',building:'建筑'};
function base(w,h,title,sub){return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" font-family="Noto Sans CJK SC"><defs><pattern id="texture" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M0 10L10 0" stroke="#ffffff" stroke-opacity=".025"/></pattern><pattern id="trees" width="18" height="18" patternUnits="userSpaceOnUse"><path d="M9 3L15 13H3Z" fill="#82ad7e" opacity=".14"/></pattern></defs>${rect(0,0,w,h,'#0c1822')}${rect(18,18,w-36,h-36,'#12232f','#2a4455',16)}<path d="M32 74H${w-32}" stroke="#42bac8" stroke-width="2"/>${text(title,34,48,24,'#eef7f8')}${text(sub,34,67,12,'#88a7b7')}`;}
function bar(x,y,w,value,max){const ratio=Math.max(0,Math.min(1,value/Math.max(1,max)));return rect(x,y,w,5,'#293c48','',2)+rect(x,y,w*ratio,5,ratio>.5?'#58d0a0':ratio>.2?'#ecc171':'#ef7777','',2);}
function token(n,a,x,y,r,avatar,current){const color=a.team==='enemy'?'#f17a7e':'#53bcf5',cid='portrait'+n;return `<defs><clipPath id="${cid}"><circle cx="${x}" cy="${y}" r="${r-2}"/></clipPath></defs>`+(current?`<circle cx="${x}" cy="${y}" r="${r+5}" fill="none" stroke="#f7d781" stroke-width="2"/>`:'')+`<circle cx="${x}" cy="${y}" r="${r}" fill="#203747" stroke="${color}" stroke-width="2"/>`+(avatar?`<image x="${x-r+2}" y="${y-r+2}" width="${r*2-4}" height="${r*2-4}" xlink:href="${avatar}" clip-path="url(#${cid})"/>`+rect(x+r*.3,y+r*.25,r*.8,14,'#142735',color,4)+text(String(n).replace(/^side/,''),x+r*.7,y+r*.25+11,10,'#ffffff','text-anchor="middle"'):text(String(n).replace(/^side/,''),x,y+5,Math.max(12,r*.65),'#ffffff','text-anchor="middle"'));}
function battleSVG(state,b,avatars={},overlay=null,zoom=false){const B=require('./combat'),M=require('./model'),size=Math.max(34,Math.min(zoom?82:60,Math.floor((zoom?1500:960)/Math.max(b.width,b.height)))),left=50,top=112,gw=b.width*size,gh=b.height*size,side=300,w=Math.max(720,gw+left+side+42),h=Math.max(gh+190,190+Math.min(b.actors.length,zoom?20:10)*44);let svg=base(w,h,'战术战场 · '+clip(b.name,28),'每格 50米 · 世界坐标与棋子位置一致 · 蓝：友方 / 红：敌方 / 金：当前行动');
 for(let y=0;y<b.height;y++){svg+=text(y+1,33,top+y*size+size/2+5,12,'#89a7b8','text-anchor="middle"');for(let x=0;x<b.width;x++){const type=b.terrain[x+','+y]||'normal',px=left+x*size,py=top+y*size;svg+=rect(px,py,size,size,type==='blocked'?'#35414b':type==='difficult'?'#5a493b':'#192f3e','#355062');if(type==='blocked')svg+=`<path d="M${px+5} ${py+5}L${px+size-5} ${py+size-5}M${px+size-5} ${py+5}L${px+5} ${py+size-5}" stroke="#77808a" stroke-width="2"/>`;else svg+=rect(px,py,size,size,'url(#texture)');if(y===0)svg+=text(x+1,px+size/2,top-14,12,'#89a7b8','text-anchor="middle"');}}
 if(overlay){const x=left+overlay.center.x/50*size,y=top+overlay.center.y/50*size,r=overlay.radius/50*size;svg+=`<defs><clipPath id="field"><rect x="${left}" y="${top}" width="${gw}" height="${gh}"/></clipPath></defs><g clip-path="url(#field)"><circle cx="${x}" cy="${y}" r="${r}" fill="#ef8257" fill-opacity=".17" stroke="#ffb07d" stroke-dasharray="8 5"/><path d="M${x-9} ${y}H${x+9}M${x} ${y-9}V${y+9}" stroke="#ffd4a0"/></g>`;}
 const live=b.actors.filter(a=>!a.retreated&&!a.deathId),groups=new Map();for(const a of live){const ref=a.x.toFixed(2)+','+a.y.toFixed(2),list=groups.get(ref)||[];list.push(a);groups.set(ref,list);}
 for(const list of groups.values()){const a=list[0],p=B.actorCharacter(state,a),n=b.actors.indexOf(a)+1,x=left+a.x/50*size,y=top+a.y/50*size,current=list.some(a=>a.id===b.current?.actorId);svg+=token(n,a,x,y,Math.max(12,size*.27),list.length===1?avatars[a.id]:null,current)+(list.length>1?rect(x+8,y-22,34,20,'#ead38a','',6)+text('×'+list.length,x+25,y-8,12,'#142532','text-anchor="middle"'):'')+bar(x-size*.3,y+size*.34,size*.6,p.hp,M.stats(p).maxHP);if(overlay?.targets.some(id=>list.some(a=>a.id===id)))svg+=`<circle cx="${x}" cy="${y}" r="${size*.37}" fill="none" stroke="#ffac72" stroke-width="2"/>`;}
 const sx=left+gw+24,active=b.actors.find(a=>a.id===b.current?.actorId);svg+=text('当前行动',sx,107,14,'#6bc9d3')+text(clip(active?.name||'等待GM',18),sx,134,18,'#f6d486')+text(b.current?'快速 '+b.current.quick+' · 正式 '+b.current.formal+' · 移动 '+b.current.move+'m':'战斗 '+({recruiting:'招募中',active:'进行中',paused:'已暂停',ended:'已结束'}[b.status]),sx,157,12);
 b.actors.slice(0,zoom?20:10).forEach((a,n)=>{const p=B.actorCharacter(state,a),max=M.stats(p).maxHP,yy=188+n*44;svg+=token('side'+(n+1),a,sx+14,yy,13,avatars[a.id],a.id===b.current?.actorId)+text(clip(a.name,15),sx+36,yy-2,13,a.deathId?'#758796':'#d7e6ed')+text((a.deathId?'死亡':a.retreated?'离场':'HP '+p.hp+'/'+max)+' · '+(a.x||0)+','+(a.y||0)+'m',sx+36,yy+14,10,'#8baabb')+bar(sx+36,yy+20,185,p.hp,max);});
 const events=b.recent.slice(-2).map(e=>clip(e.message,Math.min(80,Math.floor(gw/13))));svg+=text('待防守 '+require('./aoe').hits(b).length+' 位 · 动作点推进 '+b.wave,left,top+gh+27,13,'#8dc4ce');events.forEach((e,n)=>svg+=text(e,left,top+gh+52+n*22,12));return svg+'</svg>';}
function explorationSVG(m,full=false,floor=null){const region=m.mapType==='region',current=Object.values(m.participants)[0]?.cell?.split(',').map(Number)||[0,0],chosen=floor===null?current[1]:Math.max(0,Math.min(Number(floor)||0,m.floors-1));const size=region?Math.max(34,Math.min(64,Math.floor(1000/m.width))):Math.max(60,Math.min(105,Math.floor(1160/m.width))),levels=region?Array.from({length:m.floors},(_,n)=>n):[chosen],left=50,top=112,gw=m.width*size,gh=levels.length*size,overview=region?0:m.floors*15+55,w=Math.max(560,gw+100),h=gh+overview+215;let svg=base(w,h,(region?'区域地图':'建筑内部')+' · '+clip(m.name,28),region?'上下左右相邻移动 · 全队共同确认 · 地形装饰不增加费用':'当前 '+(chosen+1)+' 层 · 房间 / 墙 / 门 / 走廊 / 楼梯 · 已探索区域共享');
 levels.forEach((y,row)=>{svg+=text(region?y+1:(y+1)+'F',30,top+row*size+size/2+5,13,'#97b7c6','text-anchor="middle"');for(let x=0;x<m.width;x++){const ref=x+','+y,c=m.cells[ref],seen=full||m.revealed[ref],px=left+x*size,py=top+row*size;if(!c){if(!row)svg+=text(x+1,px+size/2,top-14,12,'#9bb6c6','text-anchor="middle"');continue;}svg+=rect(px,py,size-2,size-2,seen&&c?colors[c.type]||colors.room:colors.fog,'#3a5361',region?3:1);if(!row)svg+=text(x+1,px+size/2,top-14,12,'#9bb6c6','text-anchor="middle"');
 if(!c)continue;
 if(!seen){svg+=text('?',px+size/2,py+size/2+6,20,'#4e6472','text-anchor="middle"');continue;}if(!c)continue;
 if(c.type==='forest')svg+=rect(px,py,size-2,size-2,'url(#trees)');else svg+=rect(px,py,size-2,size-2,'url(#texture)');
 if(!region){if(c.type==='room')svg+=`<path d="M${px+4} ${py+size-2}H${px+size*.4}M${px+size*.6} ${py+size-2}H${px+size-3}" stroke="#b8c9cd" stroke-width="4"/><path d="M${px+size*.4} ${py+size-3}v-${size*.2}" stroke="#e4c58b" stroke-width="2"/>`;if(c.type==='stairs')for(let i=0;i<5;i++)svg+=`<path d="M${px+10+i*3} ${py+13+i*7}h${size-26-i*2}" stroke="#c7bbde" stroke-width="2"/>`;if(c.type==='corridor')svg+=`<path d="M${px+5} ${py+size/2}H${px+size-7}" stroke="#7894a5" stroke-dasharray="4 4"/>`;}
 if(!region&&c.type==='room'){
 const tone='#94b9bc',fx=px+8,fy=py+9,unit=size*.18;
 svg+=`<path d="M${px+2} ${py+size-3}V${py+2}H${px+size-3}V${py+size-3}" fill="none" stroke="#8da9b1" stroke-width="3"/>`;
 const furniture=c.room?.templateId||c.templateId||ref,seed=[...furniture].reduce((n,ch)=>n+ch.charCodeAt(0),0)%4;
 if(seed===0)svg+=rect(fx,fy,unit*2.2,unit,tone,'#c1d4d6',2)+rect(fx+unit*2.6,fy,unit,unit*2.5,'#3c626c',tone,2);
 else if(seed===1){for(let n=0;n<3;n++)svg+=rect(fx+n*unit*1.4,fy,unit,unit*2.3,'#3c626c',tone,2);}
 else if(seed===2)svg+=rect(fx,fy,unit*3.5,unit*1.1,'#496674',tone,4)+`<circle cx="${fx+unit}" cy="${fy+unit*1.8}" r="${unit*.35}" fill="${tone}"/><circle cx="${fx+unit*2.6}" cy="${fy+unit*1.8}" r="${unit*.35}" fill="${tone}"/>`;
 else svg+=rect(fx,fy,unit*2.1,unit*1.8,'#435e6d',tone,2)+rect(fx+unit*2.7,fy,unit,unit,'#496674',tone,2);
 }
 if(c.type==='wall'||c.passable===false)svg+=`<path d="M${px+6} ${py+6}L${px+size-8} ${py+size-8}M${px+size-8} ${py+6}L${px+6} ${py+size-8}" stroke="#df9e89" stroke-width="2" opacity=".65"/>`;
 const rpHidden=!full&&m.rpPendingId&&m.rps?.[m.rpPendingId]?.cell===ref&&require('./rp').waiting(m);const name=rpHidden?'等待描述':c.name||c.room?.snapshot.name||labels[c.type]||c.type;svg+=text(clip(name,Math.max(2,Math.floor(size/13))),px+size/2,py+size-9,region?11:13,'#d5e4e9','text-anchor="middle"');if(c.passable===false)svg+=text('×',px+size/2,py+size/2+5,18,'#e89790','text-anchor="middle"');
 if(!rpHidden&&c.room&&c.room.encounter!=='resolved')svg+=text('!',px+size-10,py+17,16,'#ff9a7a','text-anchor="middle"');if(c.type==='building'&&c.buildingMapId)svg+=text('门',px+11,py+17,15,'#abd8fa');const members=Object.values(m.participants).filter(p=>p.cell===ref);if(members.length)svg+=`<circle cx="${px+size/2}" cy="${py+size*.4}" r="${size*.19}" fill="#3aa5dd" stroke="#a6dfff" stroke-width="2"/>`+text(members.length,px+size/2,py+size*.4+5,14,'#ffffff','text-anchor="middle"');}});
 let yy=top+gh+27;if(!region){svg+=text('全楼层总览',left,yy,13,'#77c6d3');yy+=18;for(let y=m.floors-1;y>=0;y--){svg+=text((y+1)+'F',left,yy+10,10);for(let x=0;x<m.width;x++){const ref=x+','+y,c=m.cells[ref],seen=full||m.revealed[ref];if(!c)continue;svg+=rect(left+32+x*15,yy,13,11,seen?colors[c?.type]||'#12222d':colors.fog,y===chosen?'#e6cc83':'#354959');}yy+=15;}}
 svg+=text((m.rpEnabled?'RP开启 · ':'')+(require('./rp').waiting(m)?'等待GM环境描述 · ':'')+'图例：蓝点 队伍 · ? 迷雾 · ! 遭遇 · × 禁行 · 门 建筑入口',left,yy+24,12,'#9fbfc9')+text('已探索 '+Object.keys(m.revealed).length+'格 · 队员 '+Object.keys(m.participants).length+' 人'+(m.excursion?' · 队伍在建筑内部':''),left,yy+49,13,'#b9d9df')+text(clip(m.lastEvent||'等待全队确认下一步移动',Math.floor((w-100)/13)),left,yy+73,12);return svg+'</svg>';}
function eventSVG(e,avatar){const w=850,h=260,d=e.details||{},color=e.type==='death'?'#e87682':e.type==='result'?'#e5ad70':'#59b7d3';let svg=base(w,h,({attack:'攻击 / 技能释放',result:'防守与伤害结算',death:'死亡',move:'战术移动',casting:'吟唱',reload:'弹药操作',switch:'武器切换',item:'道具使用'}[e.type])+' · '+clip(e.actorName||'战斗记录',20),'公开操作结果 · 骰点已经保存');svg+=`<path d="M710 85L735 124L800 99L774 151L817 188L753 185L731 224L706 186L657 206L678 160L645 121L697 129Z" fill="${color}" opacity=".14"/>`;
 if(avatar)svg+=token(1,{team:'ally'},76,144,30,avatar,false);else svg+=`<circle cx="76" cy="144" r="30" fill="#234152" stroke="${color}"/>`+text('★',76,153,26,color,'text-anchor="middle"');
 const words=[...e.message];for(let n=0;n<Math.min(3,Math.ceil(words.length/39));n++)svg+=text(words.slice(n*39,(n+1)*39).join(''),122,115+n*27,17,'#e2edf1');if(d.hp!=null)svg+=bar(122,215,460,d.hp,d.maxHP)+text('HP '+d.hp+' / '+d.maxHP,600,221,16,color);else svg+=text(e.id,122,228,12,'#7c9eaf');return svg+'</svg>';}
function renderSVG(svg){return new(require('@resvg/resvg-js').Resvg)(svg,{font:{fontFiles:[FONT],loadSystemFonts:false,defaultFontFamily:'Noto Sans CJK SC'}}).render().asPng();}
function battle(state,b){return renderSVG(battleSVG(state,b));}function exploration(m,full=false,floor=null){return renderSVG(explorationSVG(m,full,floor));}
function attach(v,buffer,name){v.files=[...(v.files||[]),{attachment:buffer,name}];v.attachments=[];v.embeds[0].setImage('attachment://'+name);return v;}
function prepare(v,descriptor){v.rpgMap=descriptor;v.embeds[0].setImage('attachment://tactical-map.png');return v;}
function createRenderer({portraits,logFailure}){const cache=new Map(),jobs=[],avatarCache=new Map(),inflight=new Map();let bytes=0,running=false;
 async function avatar(guild,ref){if(!ref)return null;const key=guild+':'+ref.id,old=avatarCache.get(key);if(old)return old;try{const input=await portraits.load(guild,ref),buffer=await require('sharp')(input,{limitInputPixels:20000000}).rotate().resize(96,96,{fit:'cover'}).png().toBuffer();const uri='data:image/png;base64,'+buffer.toString('base64');avatarCache.set(key,uri);while(avatarCache.size>40)avatarCache.delete(avatarCache.keys().next().value);return uri;}catch{return null;}}
 function queue(svg){const key=createHash('sha256').update(svg).digest('hex');if(cache.has(key)){const value=cache.get(key);cache.delete(key);cache.set(key,value);return Promise.resolve(value);}if(inflight.has(key))return inflight.get(key);const promise=new Promise((resolve,reject)=>{if(jobs.length>=16)return reject(Error('地图渲染队列已满'));jobs.push({svg,key,resolve,reject});drain();});inflight.set(key,promise);promise.finally(()=>inflight.delete(key)).catch(()=>{});return promise;}
 function drain(){if(running||!jobs.length)return;running=true;const job=jobs.shift(),worker=new Worker(path.join(__dirname,'map-worker.js'),{workerData:{svg:job.svg,font:FONT}});let finished=false;const timer=setTimeout(()=>{worker.terminate();done(Error('地图渲染超时'));},15000);
  const done=(error,result)=>{if(finished)return;finished=true;clearTimeout(timer);running=false;if(error)job.reject(error);else{const value=Buffer.from(result);bytes-=cache.get(job.key)?.length||0;cache.set(job.key,value);bytes+=value.length;while(cache.size>16||bytes>24*1024*1024){const key=cache.keys().next().value;bytes-=cache.get(key).length;cache.delete(key);}job.resolve(value);}drain();};worker.once('message',data=>done(null,data));worker.once('error',error=>done(error));worker.once('exit',code=>{if(code!==0)done(Error('地图渲染进程异常'));});}
 async function decorate(guild,result){const v={...result},d=v.rpgMap;delete v.rpgMap;if(!d)return v;try{let svg;if(d.kind==='battle'){const portraitsByActor={};const actors=d.b.actors;for(let n=0;n<actors.length;n+=4)await Promise.all(actors.slice(n,n+4).map(async a=>{const p=require('./combat').actorCharacter(d.state,a);portraitsByActor[a.id]=await avatar(guild,p.portraits?.avatar);}));svg=battleSVG(d.state,d.b,portraitsByActor,d.overlay,d.zoom);}else if(d.kind==='event')svg=eventSVG(d.event,await avatar(guild,d.event.portrait));else svg=explorationSVG(d.m,d.full,d.floor);const buffer=await queue(svg);return attach(v,buffer,'tactical-map.png');}catch(e){logFailure('地图图片生成失败，文字和操作按钮仍可用。',e);v.embeds[0].setImage(null);v.files=[];v.attachments=[];return v;}}
 return {decorate,avatar,queue,cache};}
module.exports={battle,exploration,attach,prepare,battleSVG,explorationSVG,eventSVG,renderSVG,createRenderer,esc};
