'use strict';
const C=require('./constants'),M=require('./model'),U=require('./ui'),V=require('./merchant'),Categories=require('./item-categories');
const ok=C.requireThat,PAGE=20;
function createMerchant({snapshot,tx,store,needGM}){
 const route=(a,...x)=>['merchant',a,...x].join(':');
 function own(s,id,uid,kind){const f=s.forms[id];ok(f&&f.owner===uid&&(!kind||f.kind===kind),'行商草稿不属于你。');return f;}
 function fresh(s,uid,kind,data){const f={id:C.id('f'),owner:uid,kind,version:0,status:'ready',expiresAt:C.confirmationDeadline(300000),...data};s.forms[f.id]=f;return f;}
 function home(s,page=0){const list=Object.values(s.merchantTemplates||{}),part=list.slice(page*PAGE,page*PAGE+PAGE);return U.payload('GM · 行商模板','节点货单仅生成一次，共享有限库存；出售100%，收购110%（小数向下取整）。\n'+part.map(t=>t.name+' · v'+t.version+(t.enabled?'':' · 停用')).join('\n'),[...(part.length?[U.row(U.select(route('edit'),'编辑行商模板',part.map(t=>({label:t.name,value:t.id}))))]:[]),U.row(U.button(route('new'),'新建行商模板',U.D.ButtonStyle.Primary),U.button(route('audit',0),'交易审计')),U.row(U.button(route('home',Math.max(0,page-1)),'上一页',undefined,!page),U.button(route('home',page+1),'下一页',undefined,(page+1)*PAGE>=list.length))]);}
 function editor(s,f,preview=false){const t=f.data,base=(a,...x)=>route(a,f.id,f.version,...x),body='**'+t.name+'**\n'+t.description+'\n出售：'+(t.sellMode==='random'?t.sellCount+'种随机货品，每种'+t.sellQuantity+'件':'固定货单')+'\n出售分类：'+t.sellCategories.map(x=>Categories.groups.find(g=>g[0]===x)?.[1]).join('、')+'\n收购：'+(t.buyMode==='random'?t.buyCount+'种随机指定物品':'分类内所有实物')+' · 总额度 '+t.buyQuota+'件\n收购分类：'+t.buyCategories.map(x=>Categories.groups.find(g=>g[0]===x)?.[1]).join('、')+'\n'+t.entries.map(e=>(s.catalog[e.ref]?.name||'失效')+' ×'+e.quantity).join('\n');
  if(preview)return U.payload('确认发布行商模板',body,[U.row(U.button(base('publish'),'确认发布',U.D.ButtonStyle.Success),U.button(base('back'),'返回修改'))]);
  const categories=(a,list)=>U.row(U.select(base(a),a==='sellcats'?'GM选择出售类型':'GM选择收购类型',Categories.groups.map(([value,label])=>({value,label,default:list.includes(value)})),1,11));
  return U.payload('GM行商草稿',body,[categories('sellcats',t.sellCategories),categories('buycats',t.buyCategories),U.row(U.select(base('sellmode'),'出售货单模式',[{value:'random',label:'按分类随机生成',default:t.sellMode==='random'},{value:'fixed',label:'GM指定固定货单',default:t.sellMode==='fixed'}])),U.row(U.select(base('buymode'),'收购需求模式',[{value:'random',label:'按分类随机指定品种',default:t.buyMode==='random'},{value:'category',label:'收购分类内全部实物',default:t.buyMode==='category'}])),U.row(U.button(base('settings'),'名称 / 数量 / 额度'),U.button(base('fixed',0),'编辑固定货单'),U.button(base('preview'),'预览发布',U.D.ButtonStyle.Success),U.button(base('toggle'),t.enabled?'停用模板':'启用模板'),U.button(route('home',0),'返回'))]);}
 function fixed(s,f,page=0){const list=Object.values(s.catalog).filter(t=>t.published&&V.matches(t,f.data.sellCategories)),part=list.slice(page*PAGE,page*PAGE+PAGE),base=(a,...x)=>route(a,f.id,f.version,...x);return U.payload('GM固定货单',f.data.entries.map(e=>(s.catalog[e.ref]?.name||'失效')+' ×'+e.quantity).join('\n')||'选择模板并填写库存，0移除。',[...(part.length?[U.row(U.select(base('stockpick'),'选择模板设置库存（0移除）',part.map(t=>({label:t.name,value:t.id}))))]:[]),U.row(U.button(base('fixed',Math.max(0,page-1)),'上一页',undefined,!page),U.button(base('fixed',page+1),'下一页',undefined,(page+1)*PAGE>=list.length),U.button(base('back'),'返回编辑'))]);}
 function node(s,uid,mapId,ref,page=0){const {p,n}=V.access(s,uid,mapId,ref),part=n.stock.filter(e=>e.remaining>0).slice(page*PAGE,page*PAGE+PAGE),sell=Object.values(p.inventory).filter(i=>{try{M.transferable(s,uid,i.id,1);return V.buyable(n,i)&&M.available(s,uid,i.id)>0;}catch{return false;}}),sp=sell.slice(page*PAGE,page*PAGE+PAGE);
  const v=U.payload('行商 · '+n.name,n.description+'\n余额 '+p.balance+' · 收购剩余额度 **'+n.buyRemaining+'件**\n售价100%，收购110%（小数向下取整）。每次交易最多100件。\n'+(n.buyMode==='random'?'指定收购：'+n.wanted.map(id=>n.wantedTemplates?.[id]?.name||s.catalog[id]?.name||id).join('、'):'收购类型：'+n.buyCategories.map(c=>Categories.groups.find(g=>g[0]===c)[1]).join('、'))+'\n\n'+part.map(e=>e.template.name+' · '+V.price(e.template.value)+'币 · 剩余'+e.remaining+'件').join('\n'),[
    ...(part.length?[U.row(U.select(route('purchase',mapId,ref),'选择行商出售货品',part.map(e=>({label:e.template.name+' · '+e.template.value+'币 ×'+e.remaining,value:e.id}))))]:[]),
    ...(sp.length&&n.buyRemaining?[U.row(U.select(route('sell',mapId,ref),'选择背包物品卖给行商',sp.map(i=>({label:i.snapshot.name+' · '+V.price(i.snapshot.value,true)+'币 ×'+M.available(s,uid,i.id),value:i.id}))))]:[]),
    U.row(U.button(route('node',mapId,ref,Math.max(0,page-1)),'上一页',undefined,!page),U.button(route('node',mapId,ref,page+1),'下一页',undefined,(page+1)*PAGE>=Math.max(n.stock.filter(e=>e.remaining).length,sell.length)),U.button(route('node',mapId,ref,page),'刷新货单'),U.button('map:personal:'+mapId,'返回探索'))]);v.rpgPanel={kind:'map',mapId};return v;}
 function quoteView(s,f){const n=s.explorations[f.mapId]?.cells[f.cell]?.room?.merchant,item=f.mode==='purchase'?n?.stock.find(e=>e.id===f.itemId)?.template:s.players[f.owner]?.inventory[f.itemId]?.snapshot;
  const v=U.payload('确认行商交易',(f.mode==='purchase'?'购买':'出售')+' **'+(item?.name||'物品失效')+' ×'+f.quantity+'**\n单价 '+f.unitPrice+'币 · 合计 **'+f.total+'币**\n截止 <t:'+Math.floor(f.expiresAt/1000)+':R>',[U.row(U.button(route('count',f.id,f.version),'修改件数'),U.button(route('commit',f.id,f.version),'确认交易',U.D.ButtonStyle.Success,f.status!=='ready'),U.button(route('node',f.mapId,f.cell,0),'返回货单'))]);v.rpgPanel={kind:'map',mapId:f.mapId};return v;}
 function maps(s,mapId,action,page=0,templateId){const m=s.explorations[mapId];ok(m,'地图已失效。');if(action==='assign'){const list=Object.values(s.merchantTemplates||{}).filter(t=>t.published&&t.enabled),part=list.slice(page*PAGE,page*PAGE+PAGE);return U.payload('分配行商节点',m.name+' · 模板改动不影响已生成节点。',[...(part.length?[U.row(U.select(route('cells',mapId),'选择行商模板',part.map(t=>({label:t.name,value:t.id}))))]:[]),U.row(U.button(route('assign',mapId,Math.max(0,page-1)),'上一页',undefined,!page),U.button(route('assign',mapId,page+1),'下一页',undefined,(page+1)*PAGE>=list.length),U.button(route('home',0),'模板管理'),U.button('map:manage:'+mapId,'返回地图'))]);}
  const cells=Object.entries(m.cells).filter(([ref,c])=>action==='restock'?c.room?.merchant:(c.type==='room'||c.hasContents)&&require('./exploration').passable(c)&&!c.room?.boss&&!require('./exploration').touched(m,ref)),part=cells.slice(page*PAGE,page*PAGE+PAGE);return U.payload(action==='restock'?'选择补货节点':'选择未进入的内容格',m.name,[...(part.length?[U.row(U.select(route(action==='restock'?'restockpick':'assignpick',mapId,templateId||'_'),'选择地图格子',part.map(([ref,c])=>({label:ref+' · '+(c.room?.snapshot.name||'房间'),value:ref}))))]:[]),U.row(U.button(route(action==='restock'?'restock':'cells',mapId,templateId||'_',Math.max(0,page-1)),'上一页',undefined,!page),U.button(route(action==='restock'?'restock':'cells',mapId,templateId||'_',page+1),'下一页',undefined,(page+1)*PAGE>=cells.length),U.button('map:manage:'+mapId,'返回地图'))]);}
 function confirmation(s,f){const text=f.kind==='merchantAssign'?'生成货单：\n'+f.node.stock.map(e=>e.template.name+' ×'+e.remaining).join('\n')+'\n收购额度 '+f.node.buyRemaining+'件':(s.catalog[f.templateId]?.name||'仅追加收购额度')+' · 补货 '+f.quantity+'件 · 追加收购额度 '+f.buyQuota+'件';return U.payload('GM确认行商变更',text+'\n截止 <t:'+Math.floor(f.expiresAt/1000)+':R>',[U.row(U.button(route('gmcommit',f.id),'确认保存',U.D.ButtonStyle.Success),U.button('map:manage:'+f.mapId,'返回地图'))]);}
 async function openModal(i,s){if(i.isModalSubmit?.()||!i.customId?.startsWith('rpg:merchant:'))return false;const [,,a,id,ver,ref]=i.customId.split(':');if(a==='new'){needGM(s,i.member);await i.showModal(U.modal(route('create'),'新建行商模板',[{key:'name',label:'行商名称'},{key:'description',label:'行商说明',long:true,required:false,max:1000}]));return true;}
  if(a==='settings'||a==='stockpick'){needGM(s,i.member);const f=own(s,id,i.user.id,'merchantEdit');ok(f.status==='ready'&&f.version===Number(ver)&&f.expiresAt>Date.now(),'模板步骤已失效。');await i.showModal(a==='settings'?U.modal(route('settingssubmit',id,ver),'行商设置',[{key:'name',label:'名称',value:f.data.name,max:80},{key:'description',label:'说明',value:f.data.description,long:true,required:false,max:1000},{key:'sell',label:'随机出售：种数,每种库存',value:f.data.sellCount+','+f.data.sellQuantity},{key:'buy',label:'随机收购种数,收购总件数额度',value:f.data.buyCount+','+f.data.buyQuota}]):U.modal(route('stocksubmit',id,ver,i.values[0]),'固定货单数量',[{key:'quantity',label:'库存1—100；0移除',value:f.data.entries.find(e=>e.ref===i.values[0])?.quantity||1}]));return true;}
  if(a==='count'){const f=own(s,id,i.user.id,'merchantTrade');ok(f.status==='ready'&&f.expiresAt>Date.now()&&f.version===Number(ver),'交易步骤已失效。');await i.showModal(U.modal(route('countsubmit',id,ver),'交易数量',[{key:'quantity',label:'数量1—100',value:f.quantity}]));return true;}
  if(a==='restockitem'||a==='restockquota'){needGM(s,i.member);const f=own(s,id,i.user.id,'merchantRestockSelect');ok(f.expiresAt>Date.now(),'补货选择已过期。');await i.showModal(U.modal(route('restocksubmit',id,a==='restockitem'?i.values[0]:'_'),'GM手动补货',[{key:'quantity',label:'补货件数0—100',value:a==='restockitem'?1:0},{key:'quota',label:'追加收购总额度0—10000',value:0}]));return true;}return false;}
 async function component(i,member){const [,,a,id,x,y]=i.customId.split(':'),uid=i.user.id,s=snapshot(i.guildId);
  if(a==='node')return node(s,uid,id,x,Number(y)||0);
  if(['purchase','sell'].includes(a)){const f=await tx(i,st=>V.quote(st,uid,id,x,a,i.values[0]),'准备行商交易');return quoteView(snapshot(i.guildId),f);}
  if(a==='countsubmit'){const f=await tx(i,st=>{const f=own(st,id,uid,'merchantTrade');ok(f.status==='ready'&&f.expiresAt>Date.now()&&f.version===Number(x),'交易确认已失效。');const q=V.quote(st,uid,f.mapId,f.cell,f.mode,f.itemId,C.number(i.fields.getTextInputValue('quantity'),'数量',1,100));delete st.forms[q.id];Object.assign(f,{quantity:q.quantity,unitPrice:q.unitPrice,total:q.total,nodeVersion:q.nodeVersion,itemFingerprint:q.itemFingerprint});f.version++;return f;},'修改行商交易数量');return quoteView(snapshot(i.guildId),f);}
  if(a==='commit'){i.rpgOperation='merchant:'+id;const r=await store.transact(i.guildId,i.rpgOperation,uid,st=>{const f=own(st,id,uid,'merchantTrade');ok(f.version===Number(x),'交易数量已变化，请重新确认。');return V.execute(st,uid,id);},'行商交易');const v=node(snapshot(i.guildId),uid,r.mapId,own(snapshot(i.guildId),id,uid).cell);v.content='✅ '+(r.mode==='purchase'?'购买':'出售')+r.name+' ×'+r.quantity+' · '+r.total+'币，已保存。';return v;}
  needGM(s,member);
  if(a==='home')return home(s,Number(id)||0);
  if(a==='audit'){const list=Object.values(s.merchantTrades||{}).reverse(),page=Number(id)||0;return U.payload('GM行商审计',list.slice(page*PAGE,page*PAGE+PAGE).map(r=>'<@'+r.owner+'> '+(r.mode==='purchase'?'购买':'出售')+r.name+' ×'+r.quantity+' ='+r.total).join('\n')||'暂无记录',[U.row(U.button(route('audit',Math.max(0,page-1)),'上一页',undefined,!page),U.button(route('audit',page+1),'下一页',undefined,(page+1)*PAGE>=list.length),U.button(route('home',0),'返回'))]);}
  if(a==='clear'){await tx(i,st=>{needGM(st,member);V.clear(st,st.explorations[id],x);},'移除未进入行商节点');return U.payload('行商节点已移除','原房间已恢复。',[U.row(U.button('map:manage:'+id,'返回地图'))]);}
  if(a==='assign')return maps(s,id,'assign',Number(x)||0);
  if(a==='cells')return maps(s,id,'cells',Number(y)||0,i.values?.[0]||x);
  if(a==='restock')return maps(s,id,'restock',Number(y)||0);
  if(a==='restockpick'||a==='restockpage'){const f=a==='restockpick'?await tx(i,st=>{const m=st.explorations[id],cell=i.values[0],n=m?.cells[cell]?.room?.merchant;ok(n&&m.status!=='ended','节点不存在。');return fresh(st,uid,'merchantRestockSelect',{mapId:id,cell,nodeId:n.id});},'准备GM补货'):own(s,id,uid,'merchantRestockSelect'),page=a==='restockpage'?Number(x)||0:0,list=Object.values(s.catalog).filter(t=>t.published&&t.kind!=='技能'),part=list.slice(page*PAGE,page*PAGE+PAGE);return U.payload('GM手动补货','选择实物；确认后入共享库存。不会自动刷新原随机货单。',[U.row(U.select(route('restockitem',f.id),'选择补货实物',part.map(t=>({label:t.name,value:t.id})))),U.row(U.button(route('restockpage',f.id,Math.max(0,page-1)),'上一页',undefined,!page),U.button(route('restockpage',f.id,page+1),'下一页',undefined,(page+1)*PAGE>=list.length),U.button(route('restockquota',f.id),'只追加收购额度'))]);}
  if(a==='assignpick'||a==='restocksubmit'){const f=await tx(i,st=>{needGM(st,member);if(a==='assignpick'){const m=st.explorations[id],t=st.merchantTemplates[x],ref=i.values[0];ok(m&&t?.published&&t.enabled&&['draft','paused'].includes(m.status)&&!require('./exploration').touched(m,ref),'地图或模板已经变化。');const test=C.clone(st);const n=V.assign(test,test.explorations[id],ref,x);return fresh(st,uid,'merchantAssign',{mapId:id,cell:ref,mapVersion:m.version,templateId:x,templateVersion:t.version,node:n});}const parent=own(st,id,uid,'merchantRestockSelect'),m=st.explorations[parent.mapId],n=m?.cells[parent.cell]?.room?.merchant;ok(parent.expiresAt>Date.now()&&n?.id===parent.nodeId,'补货选择已失效。');return fresh(st,uid,'merchantRestock',{mapId:m.id,cell:parent.cell,nodeId:n.id,nodeVersion:n.version,templateId:x==='_'?null:x,templateVersion:st.catalog[x]?.version,quantity:C.number(i.fields.getTextInputValue('quantity'),'补货数量',0,100),buyQuota:C.number(i.fields.getTextInputValue('quota'),'收购额度',0,10000),expiresAt:parent.expiresAt});},'预览行商变更');return confirmation(snapshot(i.guildId),f);}
  if(a==='gmcommit'){i.rpgOperation='merchant-gm:'+id;const mapId=await store.transact(i.guildId,i.rpgOperation,uid,st=>{needGM(st,member);const f=own(st,id,uid);if(f.done)return f.mapId;ok(f.expiresAt>Date.now(),'变更确认已过期。');const m=st.explorations[f.mapId];if(f.kind==='merchantAssign'){ok(m?.version===f.mapVersion&&st.merchantTemplates[f.templateId]?.version===f.templateVersion,'地图或模板已变化。');V.assign(st,m,f.cell,f.templateId,undefined,f.node);}else{ok(f.kind==='merchantRestock'&&m?.cells[f.cell]?.room?.merchant?.id===f.nodeId&&m.cells[f.cell].room.merchant.version===f.nodeVersion,'补货节点已变化。');ok(!f.quantity||st.catalog[f.templateId]?.version===f.templateVersion,'补货模板已变化，请重新确认。');V.restock(st,m.id,f.cell,f.templateId,f.quantity,f.buyQuota);}f.done=true;f.status='done';return f.mapId;},'GM行商节点与补货');return U.payload('行商变更已保存','共享库存及收购额度已保存。',[U.row(U.button('map:manage:'+mapId,'返回地图'))]);}
  if(['create','edit','sellcats','buycats','sellmode','buymode','settingssubmit','stocksubmit','toggle','publish'].includes(a)){const f=await tx(i,st=>{needGM(st,member);if(a==='create')return fresh(st,uid,'merchantEdit',{baseVersion:0,data:{name:C.text(i.fields.getTextInputValue('name'),'行商名称',80),description:C.text(i.fields.getTextInputValue('description'),'说明',1000,true),sellMode:'random',buyMode:'category',sellCategories:['all'],buyCategories:['all'],sellCount:6,sellQuantity:1,buyCount:6,buyQuota:10,entries:[],enabled:true}});if(a==='edit'){const t=st.merchantTemplates[i.values[0]];ok(t,'模板失效。');return fresh(st,uid,'merchantEdit',{templateId:t.id,baseVersion:t.version,data:C.clone(t)});}const f=own(st,id,uid,'merchantEdit');ok(f.status==='ready'&&f.expiresAt>Date.now()&&f.version===Number(x),'模板草稿已变化或过期。');const t=f.data;
    if(a==='sellcats'||a==='buycats'){ok(i.values.length&&i.values.every(c=>Categories.valid(c,true)),'分类无效。');t[a==='sellcats'?'sellCategories':'buyCategories']=i.values;}
    if(a==='sellmode'||a==='buymode')t[a==='sellmode'?'sellMode':'buyMode']=i.values[0];
    if(a==='settingssubmit'){t.name=C.text(i.fields.getTextInputValue('name'),'名称',80);t.description=C.text(i.fields.getTextInputValue('description'),'说明',1000,true);const sell=i.fields.getTextInputValue('sell').split(/[,，]/),buy=i.fields.getTextInputValue('buy').split(/[,，]/);t.sellCount=C.number(sell[0],'种数',1,20);t.sellQuantity=C.number(sell[1],'库存',1,100);t.buyCount=C.number(buy[0],'收购种数',1,20);t.buyQuota=C.number(buy[1],'收购额度',0,10000);}
    if(a==='stocksubmit'){ok(st.catalog[y]?.published&&st.catalog[y].kind!=='技能','货品失效。');const q=C.number(i.fields.getTextInputValue('quantity'),'库存',0,100);t.entries=t.entries.filter(e=>e.ref!==y);if(q)t.entries.push({ref:y,quantity:q});ok(t.entries.length<=20,'固定货单最多20种。');}
    if(a==='toggle')t.enabled=!t.enabled;
    if(a==='publish'){V.publish(st,t,f.templateId,f.baseVersion);f.done=true;f.status='done';}f.version++;return f;},'GM行商模板');return f.done?home(snapshot(i.guildId)):editor(snapshot(i.guildId),f);}
  const f=own(s,id,uid,'merchantEdit');ok(f.status==='ready'&&f.expiresAt>Date.now()&&f.version===Number(x),'编辑步骤已失效。');if(a==='fixed')return fixed(s,f,Number(y)||0);if(a==='preview'){V.validate(s,f.data);return editor(s,f,true);}if(a==='back')return editor(s,f);ok(false,'行商入口已失效。');
 }
 async function slash(i,member){const s=snapshot(i.guildId);if(i.commandName==='gm'){needGM(s,member);return home(s);}const m=Object.values(s.explorations).find(m=>m.status==='active'&&m.participants[i.user.id]);ok(m,'请先参加探索并进入行商节点。');return node(s,i.user.id,m.id,m.participants[i.user.id].cell);}
 return {home,node,editor,component,openModal,slash};
}
module.exports={createMerchant};
