'use strict';
const crypto=require('node:crypto'),C=require('./constants'),B=require('./combat'),M=require('./model'),U=require('./ui'),H=require('./health');
const directions=[[0,-1],[1,-1],[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1]];
const cellName=(x,y)=>String.fromCharCode(65+x)+(y+1),clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function fingerprint(s,b,a){const p=B.actorCharacter(s,a);return crypto.createHash('sha256').update(JSON.stringify([p.id,a.x,a.y,b.status,b.pending?.id,b.current?.id,b.current?.move,b.current?.moveSpent,M.stats(p).move,M.stats(p).overloaded,b.terrain])).digest('hex');}
function motion(s,b,a){const p=B.actorCharacter(s,a);return {p,overloaded:M.stats(p).overloaded};}
function legal(s,b,a,x,y,ctx=motion(s,b,a)){const p=ctx.p,turn=b.current;if(require('./conditions').reason(p,'move')||!H.canAct(p)||ctx.overloaded||b.status!=='active'||b.pending||turn?.actorId!==a.id)return null;x=C.round2(x);y=C.round2(y);if(x<0||y<0||x>=b.width*50||y>=b.height*50||b.terrain[Math.floor(x/50)+','+Math.floor(y/50)]==='blocked')return null;
 try{const cost=B.movementCost(b,a,{x,y});return cost>0&&cost<=turn.move+.000001?{x,y,cost,distance:C.round2(Math.hypot(x-a.x,y-a.y))}:null;}catch{return null;}}
function points(s,b,a,x,y,ctx=motion(s,b,a)){const list=[],names=['左上','上方','右上','左侧','正中','右侧','左下','下方','右下'];for(const [n,dy] of [10,25,40].entries())for(const [k,dx] of [10,25,40].entries())list.push({...legal(s,b,a,x*50+dx,y*50+dy,ctx),label:names[n*3+k]});
 const near=legal(s,b,a,clamp(a.x,x*50,x*50+49.99),clamp(a.y,y*50,y*50+49.99),ctx);if(near)list.push({...near,label:'最近可达点'});
 if(Math.floor(a.x/50)===x&&Math.floor(a.y/50)===y)for(const [n,[dx,dy]] of directions.entries()){const p=ray(s,b,a,dx,dy,Math.min(5,b.current?.move||0),ctx);if(p)list.push({...p,label:'短距 '+['上','右上','右','右下','下','左下','左','左上'][n]});}
 return list.map((p,n)=>({...p,key:n}));}
const cache=new Map();
async function reachable(s,b,a){const key=b.id+':'+fingerprint(s,b,a);if(cache.has(key)){const value=cache.get(key);cache.delete(key);cache.set(key,value);return value;}const cells=[],ctx=motion(s,b,a);for(let y=0;y<b.height;y++){for(let x=0;x<b.width;x++){const p=points(s,b,a,x,y,ctx).filter(p=>p.cost);if(p.length)cells.push({x,y,label:cellName(x,y),points:p});}if(y%4===3)await new Promise(resolve=>setImmediate(resolve));}cache.set(key,cells);while(cache.size>16)cache.delete(cache.keys().next().value);return cells;}
function ray(s,b,a,dx,dy,distance,ctx=motion(s,b,a)){const len=Math.hypot(dx,dy);if(!len)return null;dx/=len;dy/=len;let end=legal(s,b,a,a.x+dx*distance,a.y+dy*distance,ctx);if(end)return end;
 let lo=0,hi=distance,best=null;for(let n=0;n<36;n++){const mid=(lo+hi)/2,p=legal(s,b,a,a.x+dx*mid,a.y+dy*mid,ctx);if(p){lo=mid;best=p;}else hi=mid;}return best;}
function relative(s,b,a,target,choice,away=false){C.requireThat(['5','10','20','remaining'].includes(String(choice)),'距离无效。');C.requireThat(target&&target.id!==a.id&&target.team!==a.team&&!target.deathId&&!target.retreated&&H.alive(B.actorCharacter(s,target)),'敌人已失效，请重新选择。');const wanted=choice==='remaining'?b.current.move:C.number(choice,'移动距离',5,20),gap=Math.hypot(target.x-a.x,target.y-a.y),d=away?wanted:Math.min(wanted,gap);let p;
 if(!gap&&away){p=directions.map(([x,y],n)=>{const p=ray(s,b,a,x,y,d);return p&&{...p,n};}).filter(Boolean).sort((a,b)=>b.distance-a.distance||a.cost-b.cost||a.n-b.n)[0];}
 else p=ray(s,b,a,(target.x-a.x)*(away?-1:1),(target.y-a.y)*(away?-1:1),d);
 C.requireThat(p,'当前方向没有可用移动位置，请改用地图选点。');return {...p,note:(away?'远离':'靠近')+target.name+' · 实际 '+p.distance+'米'+(p.distance+.02<wanted?'（受预算、障碍、边界或目标距离限制）':''),targetId:target.id,targetCharacterId:B.actorCharacter(s,target).id,targetPosition:{x:target.x,y:target.y}};}
function createMovement({snapshot,tx,canActor,actionPanel}){
 const id=(action,...args)=>['movement',action,...args].join(':');
 function ctx(i,s,bid,aid,member){const b=s.battles[bid];C.requireThat(b,'战斗已不存在。');const a=canActor(s,b,aid,member,i.user.id);C.requireThat(B.current(s,b,b.current?.id).actor.id===a.id&&!b.pending,'行动机会已变化或正在等待防守。');C.requireThat(!M.stats(B.actorCharacter(s,a)).overloaded,'超重时不能移动。');return {b,a};}
 function decorate(v,s,b,a,cells,selected){v.rpgPanel={kind:'battle',battleId:b.id,actorId:a.id,tab:'move'};v.rpgMap={kind:'battle',state:s,b,page:0,movement:{actorId:a.id,cells:cells.map(c=>({x:c.x,y:c.y,points:c.points})),selected}};return v;}
 async function open(i,bid,aid,member,page=0){const s=snapshot(i.guildId),{b,a}=ctx(i,s,bid,aid,member),cells=await reachable(s,b,a),pages=b.width>5?Math.max(1,Math.ceil(cells.length/15)):Math.max(1,Math.ceil(b.height/3));page=clamp(Number(page)||0,0,pages-1);const rows=[];
  for(let y=page*3;y<Math.min(b.height,page*3+3);y++){const rowCells=Array.from({length:b.width},(_,x)=>({x,y}));
   if(b.width<=5)rows.push(U.row(...rowCells.map(c=>U.button(id('cell',bid,aid,c.x,c.y),cellName(c.x,c.y),U.D.ButtonStyle.Secondary,!cells.some(p=>p.x===c.x&&p.y===c.y)))));}
  if(b.width>5){const part=cells.slice(page*15,page*15+15);rows.length=0;for(let n=0;n<part.length;n+=5)rows.push(U.row(...part.slice(n,n+5).map(c=>U.button(id('cell',bid,aid,c.x,c.y),c.label))));}
  const total=b.width>5?Math.max(1,Math.ceil(cells.length/15)):pages;rows.push(U.row(U.button(id('open',bid,aid,Math.max(0,page-1)),'上一页',undefined,!page),U.button(id('open',bid,aid,page+1),'下一页',undefined,page>=total-1),U.button(id('shortcuts',bid,aid),'靠近 / 远离'),U.button('view:'+bid+':'+aid+':'+i.user.id+':'+b.current.id+':move','返回')));
  return decorate(U.payload('点选移动 · '+a.name,'剩余预算 '+b.current.move+'米 · 可点击格子含合法终点。绿色点仅表示可选位置，并非整格均可达。\n格子 '+(page+1)+'/'+total,rows),s,b,a,cells);}
 async function shortcuts(i,bid,aid,member,f){const s=snapshot(i.guildId),{b,a}=ctx(i,s,bid,aid,member);if(!f)f=await tx(i,st=>{const p=B.actorCharacter(st,st.battles[bid].actors.find(a=>a.id===aid)),f={id:C.id('f'),kind:'moveSelect',owner:i.user.id,battleId:bid,actorId:aid,characterId:p.id,turnId:b.current.id,distance:'5',expiresAt:C.confirmationDeadline(300000)};st.forms[f.id]=f;return f;},'选择快捷移动');const enemies=b.actors.filter(e=>e.team!==a.team&&!e.deathId&&!e.retreated&&H.alive(B.actorCharacter(s,e))),enemy=enemies.find(e=>e.id===f.enemy),base=(action)=>id(action,f.id);
  const v=U.payload('靠近 / 远离敌人','剩余预算 '+b.current.move+'米 · 先选择敌人与移动距离。',[...(enemies.length?[U.row(U.select(base('enemy'),'选择敌人',enemies.map(e=>({label:e.name,value:e.id,default:e.id===f.enemy}))))]:[]),U.row(U.select(base('distance'),'选择距离',[['5','5米'],['10','10米'],['20','20米'],['remaining','剩余预算']].map(([value,label])=>({value,label,default:value===f.distance})))),U.row(U.button(base('toward'),'靠近'+(enemy?.name||'敌人'),U.D.ButtonStyle.Primary,!enemy),U.button(base('away'),'远离'+(enemy?.name||'敌人'),undefined,!enemy),U.button(id('open',bid,aid,0),'点地图移动'))]);return decorate(v,s,b,a,await reachable(s,b,a));}
 async function component(i,member){const p=i.customId.split(':'),legacy=p[1]==='move',action=legacy?'open':p[2],args=legacy?p.slice(2):p.slice(3),s=snapshot(i.guildId);
  if(['open','shortcuts','cell','point','short'].includes(action)){const [bid,aid,x,y,key]=args,{b,a}=ctx(i,s,bid,aid,member);if(legacy)C.requireThat(args[2]===i.user.id&&args[3]===b.current.id,'移动面板已失效。');if(action==='open')return open(i,bid,aid,member,legacy?0:x);if(action==='shortcuts')return shortcuts(i,bid,aid,member);
   const all=await reachable(s,b,a),list=points(s,b,a,Number(x),Number(y));if(action==='cell'||action==='short'){const part=action==='short'?list.slice(10):list.slice(0,10),rows=[];for(let n=0;n<part.length;n+=3)rows.push(U.row(...part.slice(n,n+3).map(v=>U.button(id('point',bid,aid,x,y,v.key),v.label+(v.cost?' · '+v.cost+'米':''),undefined,!v.cost))));rows.push(U.row(U.button(id(action==='short'?'cell':'short',bid,aid,x,y),action==='short'?'九宫格':'短距离点'),U.button(id('open',bid,aid,0),'返回地图')));return decorate(U.payload('格内选点 · '+cellName(Number(x),Number(y)),'只启用合法终点；标注为地形计费消耗。',rows),s,b,a,all);}
   const point=list.find(v=>v.key===Number(key));C.requireThat(point?.cost,'位置已不可达，请重新选择。');return prepare(i,s,b,a,point);}
  const f=s.forms[args[0]];C.requireThat(f?.kind==='moveSelect'&&f.owner===i.user.id&&f.expiresAt>Date.now(),'移动选择已失效。');const {b,a}=ctx(i,s,f.battleId,f.actorId,member);C.requireThat(f.turnId===b.current.id&&f.characterId===B.actorCharacter(s,a).id,'行动机会或角色已变化。');if(['enemy','distance'].includes(action)){const updated=await tx(i,st=>{const live=st.forms[f.id];C.requireThat(live.owner===i.user.id&&live.expiresAt>Date.now(),'选择已失效。');if(action==='distance')C.requireThat(['5','10','20','remaining'].includes(i.values[0]),'距离无效。');live[action]=i.values[0];return live;},'调整移动选择');return shortcuts(i,b.id,a.id,member,updated);}
  C.requireThat(['toward','away'].includes(action),'移动入口已失效。');return prepare(i,s,b,a,relative(s,b,a,b.actors.find(e=>e.id===f.enemy),f.distance,action==='away'));
 }
 function prepare(i,s,b,a,p){return actionPanel.prepare(i,{battleId:b.id,actorId:a.id,turnId:b.current.id,action:'move',params:{...p,movementFingerprint:fingerprint(s,b,a)}});}
 return {component,open,shortcuts};
}
module.exports={createMovement,legal,points,reachable,relative,fingerprint,cellName,cache};
