'use strict';
const C=require('./constants'),U=require('./ui'),{requireThat:ok}=C;
function waiting(m){return !!m.rps?.[m.rpPendingId]&&!['released','skipped','cancelled'].includes(m.rps[m.rpPendingId].status);}
function check(m){ok(!waiting(m),'等待GM发布环境描述，暂不能移动、开战或领取物资。');}
function enter(state,m,cell){const room=m.cells[cell]?.room;if(!m.rpEnabled||!room||room.rpVisited)return null;ok(state.config.rpChannelId,'开启RP前请配置隐藏GM操作频道。');room.rpVisited=true;const r={id:C.id('p'),roomId:room.id,cell,description:room.snapshot.description,name:room.snapshot.name,status:'pending',version:1,createdAt:Date.now(),draft:{status:'pending'},publication:{status:'pending'}};m.rps||={};m.rps[r.id]=r;m.rpPendingId=r.id;return r;}
function release(m,r,status='released'){ok(waiting(m)&&m.rpPendingId===r.id,'该RP等待已经结束。');r.status=status;r.releasedAt=Date.now();if(status==='released')m.cells[r.cell].room.publicDescription=r.description;m.version++;m.lastEvent=status==='released'?'GM已发布房间环境':'GM已取消本次RP等待';}
async function verifyChannel(guild,channel,s){
 const P=U.D.PermissionFlagsBits;
 const check=(condition,message)=>{if(!condition)throw Object.assign(new Error(message),{code:'RPG_RP_CHANNEL',recoverable:true});};
 check(channel?.guildId===guild.id&&[U.D.ChannelType.GuildText,U.D.ChannelType.GuildAnnouncement].includes(channel.type),'请选择本服务器的GM文字频道。');
 const [me,roles]=await Promise.all([guild.members.fetchMe(),guild.roles.fetch()]);
 check(channel.permissionsFor(me)?.has([P.ViewChannel,P.SendMessages,P.EmbedLinks]),'Bot需要查看频道、发送消息及嵌入链接权限。');
 check(!channel.permissionsFor(roles.get(guild.id))?.has(P.ViewChannel),'RP操作频道不能向所有人开放。');
 for(const id of s.config.playerRoleIds){const role=roles.get(id);check(role&&!channel.permissionsFor(role)?.has(P.ViewChannel),'RP操作频道不能向玩家身份组开放。');}
 check(s.config.gmRoleIds.length,'请先配置GM身份组。');
 const missing=[];
 for(const id of s.config.gmRoleIds){const role=roles.get(id),perms=role&&channel.permissionsFor(role);
  if(!role){missing.push('<@&'+id+'>：身份组已不存在，请在跑团配置中移除或重选');continue;}
  const fields=[[P.ViewChannel,'查看频道'],[P.SendMessages,'发送消息']].filter(([bit])=>!perms?.has(bit)).map(([,name])=>name);
  if(fields.length)missing.push('<@&'+id+'>：缺少'+fields.join('、'));
 }
 check(!missing.length,'RP操作频道 <#'+channel.id+'> 权限未通过：\n'+missing.join('\n')+'\n请在该频道的权限中为上述GM身份组允许对应权限，再从此菜单重新选择频道。');
 for(const role of roles.values()){if(role.id===guild.id||s.config.gmRoleIds.includes(role.id)||role.managed||role.permissions?.has(P.Administrator))continue;check(!channel.permissionsFor(role)?.has(P.ViewChannel),'非GM身份组「'+role.name+'」可以查看操作频道，请先关闭。');}
 for(const overwrite of channel.permissionOverwrites?.cache.values()||[]){if(overwrite.type!==1||!overwrite.allow.has(P.ViewChannel))continue;const member=await guild.members.fetch(overwrite.id);check(member.user.bot||member.permissions.has(P.Administrator)||U.gm(s,member),'操作频道存在普通成员的个人查看授权，请先关闭。');}
 return channel;
}
function card(m,r,gm=true){return U.payload((gm?'GM环境草稿':'房间环境')+' · '+r.name,r.description+(gm?'\n\n状态：'+r.status+' · 发布到 <#'+m.channelId+'>':''),gm?[U.row(U.button('rp:edit:'+m.id+':'+r.id+':'+r.version,'编辑描述'),U.button('rp:preview:'+m.id+':'+r.id,'预览'),U.button('rp:publish:'+m.id+':'+r.id+':'+r.version,'直接发布',U.D.ButtonStyle.Success)),U.row(U.button('rp:review:'+m.id+':'+r.id,'发送不明确时核对'),U.button('rp:skippreview:'+m.id+':'+r.id,'取消本次等待',U.D.ButtonStyle.Danger))]:[]);}
function controller({snapshot,tx,store,client,textChannel,needGM,logFailure,publishMap}){const jobs=new Map(),publishing=new Set();
 async function draft(guild,mapId,force=false){const jobKey=guild+':'+mapId;if(jobs.has(jobKey))return jobs.get(jobKey);const job=(async()=>{let s=snapshot(guild),m=s.explorations[mapId],r=m?.rps?.[m.rpPendingId];if(!m||!r||!waiting(m))return;if(r.draft.status==='sent'&&!force)return;if(['sending','uncertain'].includes(r.draft.status)&&!force)return;const ch=await textChannel(guild,s.config.rpChannelId);await verifyChannel(await client.guilds.fetch(guild),ch,s);await store.transact(guild,'rp-draft-intent:'+C.id('t'),client.user.id,st=>{const r=st.explorations[mapId].rps[st.explorations[mapId].rpPendingId];r.draft.status='sending';},'RP草稿发送意图');try{const msg=await ch.send({...card(m,r),content:s.config.gmRoleIds.map(id=>'<@&'+id+'>').join(' '),allowedMentions:{parse:[],roles:s.config.gmRoleIds},nonce:'d'+r.id,enforceNonce:true});await store.transact(guild,'rp-draft-result:'+C.id('t'),client.user.id,st=>{const r=st.explorations[mapId].rps[m.rpPendingId];r.draft={status:'sent',messageId:msg.id,channelId:ch.id};},'RP草稿已发送');}catch(e){await store.transact(guild,'rp-draft-error:'+C.id('t'),client.user.id,st=>{st.explorations[mapId].rps[m.rpPendingId].draft.status='uncertain';},'RP草稿待核对').catch(()=>{});throw e;}})();jobs.set(jobKey,job);try{return await job;}finally{jobs.delete(jobKey);}}
 async function openModal(i,s){if(i.isModalSubmit?.()||!i.customId?.startsWith('rpg:rp:edit:'))return false;needGM(s,i.member);const [,,,mapId,rid,version]=i.customId.split(':'),r=s.explorations[mapId]?.rps?.[rid];ok(r?.version===Number(version)&&r.status==='pending','RP草稿已经变化或正在发送。');await i.showModal(U.modal('rp:submit:'+mapId+':'+rid+':'+version,'编辑环境描述',[{key:'description',label:'公开环境描述（最多2000字）',value:r.description,long:true}]));return true;}
 async function component(i,member){const [,,action,mapId,rid,version]=i.customId.split(':'),s=snapshot(i.guildId);needGM(s,member);
  if(action==='config')return U.payload('RP隐藏操作频道','选择玩家不可查看、GM和Bot可以查看的文字频道。各地图独立开启RP。',[U.row(new U.D.ChannelSelectMenuBuilder().setCustomId('rpg:rp:channel').setChannelTypes(U.D.ChannelType.GuildText,U.D.ChannelType.GuildAnnouncement).setMinValues(1).setMaxValues(1)),U.row(U.button('map:config','返回地图配置'))]);
  if(action==='channel'){const ch=await i.guild.channels.fetch(i.values[0]);await verifyChannel(i.guild,ch,s);await tx(i,st=>{needGM(st,member);st.config.rpChannelId=ch.id;},'配置RP隐藏频道');return U.payload('RP操作频道已保存','<#'+ch.id+'>',[U.row(U.button('map:config','返回地图配置'))]);}
  const m=s.explorations[mapId];ok(m,'地图已清理或不存在。');
  if(action==='toggle'){if(!m.rpEnabled){ok(s.config.rpChannelId,'请先配置RP隐藏频道。');await verifyChannel(i.guild,await i.guild.channels.fetch(s.config.rpChannelId),s);}await tx(i,st=>{needGM(st,member);st.explorations[mapId].rpEnabled=!st.explorations[mapId].rpEnabled;st.explorations[mapId].version++;},'切换地图RP');return U.payload('RP设置已保存','仅影响后续首次进入的房间，已有等待须单独发布或取消。',[U.row(U.button('map:manage:'+mapId,'返回地图管理'))]);}
  const r=m.rps?.[rid||m.rpPendingId];ok(r,'RP草稿不存在。');if(action==='home')return card(m,r);if(action==='preview')return card(m,r,false);
  if(action==='skippreview')return U.payload('确认取消RP等待','队伍将恢复探索，本次环境描述不公开发送。',[U.row(U.button('rp:skip:'+mapId+':'+r.id+':'+r.version,'确认取消等待',U.D.ButtonStyle.Danger),U.button('rp:home:'+mapId+':'+r.id,'返回'))]);
  if(action==='resolve')ok(!publishing.has(i.guildId+':'+mapId+':'+r.id),'环境正在发送，请等待结果后再核对。');if(action==='review')return U.payload('核对RP发送','请先查看地图频道是否已经发出环境描述。选择“已发出”只解除等待；“确认未发出”重新开放发布，不自动发送。',[U.row(U.button('rp:resolve:'+mapId+':'+r.id+':yes','已发出，解除等待'),U.button('rp:resolve:'+mapId+':'+r.id+':no','确认未发出，重新发布')),U.row(U.button('rp:draftretry:'+mapId+':'+r.id,'核对后补发隐藏草稿'))]);
  if(action==='draftretry'){await draft(i.guildId,mapId,true);return card(snapshot(i.guildId).explorations[mapId],snapshot(i.guildId).explorations[mapId].rps[r.id]);}
  if(action==='publish'){ok(r.status==='pending'&&r.version===Number(version),'草稿已修改或已经发送，请重新预览。');await tx(i,st=>{needGM(st,member);const m=st.explorations[mapId],r=m.rps[rid];ok(r.status==='pending'&&r.version===Number(version),'RP状态已变化。');r.status='publishing';r.publication.status=store.backgroundPublications?'pending':'sending';},'RP环境发布意图');if(store.backgroundPublications){const live=snapshot(i.guildId).explorations[mapId],out=card(live,live.rps[rid]);out.content='环境发布任务已保存，送达成功后自动解除等待。';return out;}try{const ch=await textChannel(i.guildId,m.channelId),msg=await ch.send({...card(m,r,false),nonce:'p'+r.id,enforceNonce:true,allowedMentions:{parse:[]}});await store.transact(i.guildId,'rp-result:'+r.id,client.user.id,st=>{const live=st.explorations[mapId],v=live.rps[rid];v.publication={status:'sent',messageId:msg.id,channelId:m.channelId};release(live,v);},'RP环境已公开');}catch(e){await store.transact(i.guildId,'rp-error:'+C.id('t'),client.user.id,st=>{const v=st.explorations[mapId].rps[rid];v.status='uncertain';v.publication.status='uncertain';},'RP环境发送待核对').catch(()=>{});throw Error('环境发送结果待核对，仍保持等待。GM请核对后补发。');}}
  else await tx(i,st=>{needGM(st,member);const live=st.explorations[mapId],v=live.rps[r.id];ok(waiting(live),'RP等待已结束。');if(action==='submit'){ok(v.status==='pending'&&v.version===Number(version),'RP草稿已变化。');v.description=C.text(i.fields.getTextInputValue('description'),'环境描述',2000);v.version++;}else if(action==='skip'){ok(v.version===Number(version),'RP草稿已变化。');release(live,v,'skipped');}else if(action==='resolve'){ok(['publishing','uncertain'].includes(v.status),'仅可核对发送不明确的公开描述。');if(version==='yes'){v.publication.status='confirmed';release(live,v);}else{v.status='pending';v.publication.status='pending';v.version++;}}else throw Error('RP操作已失效。');},'GM环境操作');
  await publishMap(i.guildId,mapId);return card(snapshot(i.guildId).explorations[mapId],snapshot(i.guildId).explorations[mapId].rps[r.id]);
 }
 async function tick(guild){for(const m of Object.values(snapshot(guild).explorations))if(m.status==='active'&&waiting(m)){const r=m.rps[m.rpPendingId];if(r.draft.status==='pending'){if(store.backgroundPublications)await store.enqueue(guild,'rpDraft',m.id,{priority:3});else await draft(guild,m.id).catch(e=>logFailure('RP隐藏草稿发送失败，GM可从地图管理核对补发。',e));}}}
 async function publishQueued(guild,mapId,rid){const key=guild+':'+mapId+':'+rid;if(publishing.has(key))return;const m=snapshot(guild).explorations[mapId],r=m?.rps?.[rid];if(!r||r.status!=='publishing'||r.publication.status!=='pending')return;publishing.add(key);
  try{await store.transact(guild,'rp-queued-intent:'+C.id('j'),client.user.id,st=>{const v=st.explorations[mapId].rps[rid];ok(v.status==='publishing'&&v.version===r.version&&v.publication.status==='pending','RP发布状态已变化。');v.publication.status='sending';},'RP后台发布意图',{delivery:false});
   const ch=await textChannel(guild,m.channelId),msg=await ch.send({...card(m,r,false),nonce:'p'+r.id,enforceNonce:true,allowedMentions:{parse:[]}});
   await store.transact(guild,'rp-result:'+r.id,client.user.id,st=>{const live=st.explorations[mapId],v=live.rps[rid];ok(v.status==='publishing'&&v.version===r.version,'RP状态已变化，须核对已发出的环境描述。');v.publication={status:'sent',messageId:msg.id,channelId:m.channelId};release(live,v);},'RP环境已公开');
  }catch(e){if(!store.frozen(guild))await store.transact(guild,'rp-queued-error:'+C.id('j'),client.user.id,st=>{const v=st.explorations[mapId]?.rps?.[rid];if(v?.status==='publishing'){v.status='uncertain';v.publication.status='uncertain';}},'RP环境发送待核对',{delivery:false}).catch(()=>{});throw e;}finally{publishing.delete(key);}
 }
 return {openModal,component,draft,tick,publishQueued};
}
module.exports={waiting,check,enter,release,verifyChannel,card,controller};
