'use strict';
const C=require('./constants'),M=require('./model'),B=require('./combat');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const clip=(s,n=18)=>[...String(s||'')].slice(0,n).join('')+([...String(s||'')].length>n?'…':'');
const text=(s,x,y,size=22,color='#eadfcb',extra='')=>`<text x="${x}" y="${y}" font-size="${size}" fill="${color}" ${extra}>${esc(s)}</text>`;
const rect=(x,y,w,h,fill,stroke='',r=8)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="${fill}" ${stroke?`stroke="${stroke}"`:''}/>`;
const line=(x,y,x2,y2,color='#59625d',extra='')=>`<path d="M${x} ${y}L${x2} ${y2}" fill="none" stroke="${color}" ${extra}/>`;
function base(w,h,title,subtitle){return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" font-family="Noto Sans CJK SC"><defs><linearGradient id="bg" x2="1" y2="1"><stop stop-color="#242b2a"/><stop offset="1" stop-color="#101b22"/></linearGradient><pattern id="floor" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M0 32H32V0" stroke="#e4d6ad" opacity=".05"/><path d="M5 8h3m12 14h2" stroke="#d7bf96" opacity=".08"/></pattern></defs>${rect(0,0,w,h,'url(#bg)','',0)}${rect(14,14,w-28,h-28,'none','#687163',14)}${rect(24,24,5,49,'#d8b46d','',2)}${text(clip(title,w===640?20:32),42,53,27,'#f3e6cc','font-weight="bold"')}${text(clip(subtitle,w===640?33:58),42,83,16,'#a6b3b0')}${line(30,100,w-30,100,'#6d755f')}`;}
function bar(x,y,w,n,max,tone='#7bd3a4',height=8){return rect(x,y,w,height,'#101e24','',3)+rect(x,y,w*Math.max(0,Math.min(1,n/Math.max(1,max))),height,tone,'',3);}
function portrait(id,n,a,x,y,r,avatar,current=false,pending=false){const color=a.team==='enemy'?'#ff747e':'#6dd8f6';return `<defs><clipPath id="p${id}"><circle cx="${x}" cy="${y}" r="${r-2}"/></clipPath></defs>`+(current?`<circle cx="${x}" cy="${y}" r="${r+5}" fill="none" stroke="#ffd678" stroke-width="3"/>`:'')+`<circle cx="${x+1}" cy="${y+3}" r="${r+1}" fill="#080e13" opacity=".8"/><circle cx="${x}" cy="${y}" r="${r}" fill="#24333b" stroke="${color}" stroke-width="2"/>`+(avatar?`<image href="${avatar}" x="${x-r}" y="${y-r}" width="${2*r}" height="${2*r}" clip-path="url(#p${id})"/>`:`<circle cx="${x}" cy="${y-r*.24}" r="${r*.27}" fill="${color}" opacity=".55"/><path d="M${x-r*.5} ${y+r*.42}Q${x-r*.42} ${y-r*.08} ${x} ${y-r*.03}Q${x+r*.42} ${y-r*.08} ${x+r*.5} ${y+r*.42}Z" fill="${color}" opacity=".42"/>`)+rect(x+r*.1,y+r*.25,r*1.1,18,'#17262d',color,4)+text(n,x+r*.65,y+r*.25+14,14,'#fff','text-anchor="middle" font-weight="bold"')+(pending?text('!',x-r,y-r,20,'#ffbd75','font-weight="bold"'):'');}
function obstacle(name,x,y,size,type='blocked'){const pad=size*.12,w=size-pad*2,h=size*.54,px=x+pad,py=y+pad;let s=rect(px+3,py+5,w,h,'#101716','',4),kind=/帐篷/.test(name)?'tent':/车/.test(name)?'car':/床/.test(name)?'bed':/路障/.test(name)?'barrier':/机柜|服务器/.test(name)?'rack':/货架|柜/.test(name)?'shelf':/灶|厨房/.test(name)?'stove':'desk';
 if(kind==='tent')s+=`<path d="M${px} ${py+h}L${px+w/2} ${py}L${px+w} ${py+h}Z" fill="#827754" stroke="#cbb777"/><path d="M${px+w*.4} ${py+h}L${px+w/2} ${py+h*.35}L${px+w*.62} ${py+h}Z" fill="#1c2c28"/>`;
 else if(kind==='car')s+=rect(px,py,w,h,'#73766b','#c1c0a4',8)+rect(px+w*.25,py+h*.15,w*.45,h*.7,'#2f4a50','#9ca9a0',5)+rect(px-3,py+5,5,h*.23,'#172121','',1)+rect(px+w-2,py+h*.65,5,h*.23,'#172121','',1);
 else if(kind==='barrier'){s+=rect(px,py+h*.3,w,h*.45,'#b5a16a','#ecd193',2);for(let n=0;n<5;n++)s+=line(px+n*w/5,py+h*.3,px+n*w/5+w*.1,py+h*.75,'#484c40','stroke-width="5"');}
 else {s+=rect(px,py,w,h,kind==='bed'?'#9dafa3':kind==='rack'?'#39454a':'#747663','#c3baa1',4);if(kind==='bed')s+=rect(px+4,py+4,w*.3,h-8,'#d6d3b8','',3);else if(kind==='desk')s+=rect(px+w*.55,py+5,w*.27,h*.48,'#2b5158','#99b0a5',2)+rect(px+6,py+8,w*.22,h*.45,'#b2a276','',2);else if(kind==='stove')for(let n=0;n<2;n++)s+=`<circle cx="${px+w*(.3+n*.4)}" cy="${py+h/2}" r="${h*.3}" fill="#252d2c" stroke="#c6ba90"/>`;else for(let n=1;n<4;n++)s+=line(px+4,py+h*n/4,px+w-4,py+h*n/4,kind==='rack'?'#89bec0':'#b5ae93','stroke-width="2"');}
 return s+text(clip(name,6),x+size/2,y+size-12,Math.min(17,size/6),'#eadcb6','text-anchor="middle"')+text(type==='decor'?'陈设':type==='difficult'?'困难':'阻挡',x+size-6,y+10,Math.min(10,size/8),'#e2c98d','text-anchor="end"');}
function battleSVG(state,b,avatars={},overlay=null,zoom=false,options={}){const wide=options.layout==='wide'||zoom,w=wide?960:640,size=Math.min(b.width<=3&&b.height<=4?150:72,Math.floor((wide?570:550)/Math.max(1,b.width)),Math.floor(600/Math.max(1,b.height))),gw=b.width*size,gh=b.height*size,left=wide?50:(w-gw)/2,top=170,page=Math.max(0,Number(options.page)||0),actors=b.actors.slice(page*10,page*10+10),listY=wide?164:top+gh+56,listX=wide?660:36,rows=wide?actors.length:Math.ceil(actors.length/2),h=Math.max(wide?600:500,wide?top+gh+100:listY+rows*102+110,wide?listY+rows*100+90:0),round=B.roundState(b);let s=base(w,h,'战术战场 · '+b.name,'第'+round.number+'轮 · 50米/格 · 蓝友 / 红敌 / 金当前');const active=b.actors.find(a=>a.id===b.current?.actorId);s+=text('当前 '+clip(active?.name||'等待行动',15),36,132,22,'#f3d18c');if(b.current)s+=text('快速 '+b.current.quick+'  正式 '+b.current.formal+'  移动 '+b.current.move+'m',wide?390:36,wide?132:155,wide?18:16,'#b4ceca');
 for(let y=0;y<b.height;y++)for(let x=0;x<b.width;x++){const px=left+x*size,py=top+y*size,type=b.terrain[x+','+y];s+=rect(px,py,size,size,type==='blocked'?'#41493e':type==='difficult'?'#675b3e':'#38433c','#6f7b69',0)+rect(px,py,size,size,'url(#floor)','',0);if(!y)s+=text(options.movement?String.fromCharCode(65+x):x+1,px+size/2,top-9,14,'#bdc9b4','text-anchor="middle"');if(!x)s+=text(y+1,left-14,py+size/2,14,'#bdc9b4','text-anchor="middle"');const o=b.roomObstacles?.find(o=>o.cell===x+','+y&&o.terrain===type);if(o)s+=obstacle(o.name,px,py,size,type);else if(type==='blocked')s+=obstacle('掩体',px,py,size);else if(type==='difficult')s+=text('困难',px+size/2,py+size-10,12,'#d8c38f','text-anchor="middle"');}
 if(options.movement){const move=options.movement,a=b.actors.find(a=>a.id===move.actorId);for(const c of move.cells||[])for(const p of c.points||[])s+=`<circle cx="${left+p.x/50*size}" cy="${top+p.y/50*size}" r="3" fill="#88e4b2" opacity=".7"/>`;}
 if(overlay){const cx=left+overlay.center.x/50*size,cy=top+overlay.center.y/50*size,r=overlay.radius/50*size;s+=`<defs><clipPath id="field"><rect x="${left}" y="${top}" width="${gw}" height="${gh}"/></clipPath></defs><g clip-path="url(#field)"><circle cx="${cx}" cy="${cy}" r="${r}" fill="#ff9850" fill-opacity=".22" stroke="#ffd08e" stroke-width="2" stroke-dasharray="7 4"/></g>`;}
 const hits=require('./aoe').hits(b),groups=new Map();for(const a of b.actors.filter(a=>!a.retreated&&!a.deathId)){const key=a.x+','+a.y;groups.set(key,[...(groups.get(key)||[]),a]);}for(const list of groups.values()){const a=list[0],p=B.actorCharacter(state,a),n=b.actors.indexOf(a)+1,x=left+a.x/50*size,y=top+a.y/50*size,r=Math.max(6,Math.min(17,size*.12));s+=portrait('map'+n,list.length>1?'×'+list.length:n,a,x,y,r,list.length===1?avatars[a.id]:null,list.some(a=>a.id===b.current?.actorId),hits.some(h=>list.some(a=>a.id===h.targetId)))+bar(x-r,y+r+7,2*r,p.hp,M.stats(p).maxHP,'#9cdb9a',3);if(p.userId)s+=bar(x-r,y+r+12,2*r,p.life?.reserveHP??M.stats(p).maxHP,M.stats(p).maxHP,'#eead6f',3);if(overlay?.targets.includes(a.id))s+=`<circle cx="${x}" cy="${y}" r="${r+8}" stroke="#ffb979" fill="none" stroke-width="2"/>`;}
 if(options.movement?.selected){const a=b.actors.find(a=>a.id===options.movement.actorId),p=options.movement.selected;if(a){const x=left+p.x/50*size,y=top+p.y/50*size;s+=line(left+a.x/50*size,top+a.y/50*size,x,y,'#ffd678','stroke-width="4" stroke-dasharray="6 4"')+`<circle cx="${x}" cy="${y}" r="7" fill="#ffd678" stroke="#fff"/>`+text('终点',Math.min(left+gw-35,x+12),Math.max(top+15,y-12),13,'#ffe59d');}}
 actors.forEach((a,n)=>{const p=B.actorCharacter(state,a),stats=M.stats(p),x=listX+(wide?0:n%2*286),y=listY+(wide?n:Math.floor(n/2))*(wide?100:102),cost=B.opportunityCost(b,a.id);s+=rect(x-8,y-20,wide?265:274,wide?94:96,'#233138',a.id===b.current?.actorId?'#e8c278':'#536159',7)+portrait('list'+n,b.actors.indexOf(a)+1,a,x+12,y+1,16,avatars[a.id],false,hits.some(h=>h.targetId===a.id))+text(clip(a.name,wide?11:10),x+40,y-1,17,a.deathId?'#85948d':'#f0e5cf')+text(a.deathId?'已死亡':a.retreated?'已离场':'HP '+p.hp+'/'+stats.maxHP+' · AP '+p.ap,x+40,y+20,13,'#b8c6bb')+bar(x+40,y+28,190,p.hp,stats.maxHP)+(p.userId?text('倒地 '+(p.life?.reserveHP??stats.maxHP)+'/'+stats.maxHP+(require('./health').downed(p)?' · 倒地中':' · 待用'),x+40,y+49,12,'#e7ac77')+bar(x+40,y+54,190,p.life?.reserveHP??stats.maxHP,stats.maxHP,'#e6a56f',4):'')+text('本轮'+(round.counts[a.id]||0)+'次 · 下次 '+(Number.isFinite(cost)?cost+'AP':'待重置'),x+40,y+73,12,'#d6c391');});
 s+=text('待防守 '+hits.length+' 位 · AP推进 '+b.wave+' · 名单 '+(page+1)+'/'+Math.max(1,Math.ceil(b.actors.length/10)),36,h-56,17,'#becdc0')+text('障碍以文字图例为准 · 大图与名单分页可查看全部角色',36,h-29,13,'#9caaa0');return s+'</svg>';}
function eventSVG(e,avatar,options={},progress=1){const wide=options.layout==='wide',w=wide?960:640,h=wide?500:620,feedback=require('./combat-presentation').feedback(e,options.section),d=e.details||{},r=feedback.result,tone=feedback.killed?'#ff668b':feedback.full?'#ffe071':feedback.damageTypes.includes('magical')?'#ad95ff':feedback.damageTypes.includes('mental')?'#ef82c9':'#81dacf',titles={attack:'攻击',result:'防守结算',move:'移动',death:'死亡结算',casting:'吟唱',reload:'弹药操作',switch:'武器切换',item:'道具',pass:'放弃行动',finish:'结束机会',flee:'撤退',rescue:'救援事件',condition:'异常结算',support:'援军加入'},headline=feedback.killed?'击杀敌人':feedback.full?'满伤害':feedback.kind==='skill'?'技能释放':titles[e.type]||'行动记录';let s=base(w,h,headline+' · '+(e.actorName||'战斗记录'),(d.ability||d.weapon||titles[e.type]||'操作')+' · 结果已经保存');
 const cx=wide?830:537,cy=178,pulse=Math.sin(progress*Math.PI);s+=`<circle cx="${cx}" cy="${cy}" r="${38+progress*45}" fill="none" stroke="${tone}" stroke-opacity="${.15+pulse*.45}" stroke-width="${3+pulse*6}"/>`;
 if(feedback.kind==='skill'){for(const [n,type] of feedback.damageTypes.entries()){const color={physical:'#ffd077',magical:'#ad95ff',mental:'#ef82c9'}[type]||tone;s+=`<g transform="rotate(${progress*100+n*60},${cx},${cy})"><path d="M${cx} ${cy-58}L${cx+50} ${cy+28}L${cx-50} ${cy+28}Z" fill="none" stroke="${color}" stroke-width="2" opacity=".65"/></g>`;}}
 else if(e.type==='move')s+=`<path d="M${cx-50} ${cy+20}L${cx-15+progress*30} ${cy-10}L${cx+35} ${cy+10}" stroke="${tone}" stroke-width="5" fill="none" stroke-dasharray="9 6"/>`;
 else {for(let n=0;n<8;n++){const angle=n*Math.PI/4,x=cx+Math.cos(angle)*28,y=cy+Math.sin(angle)*28;s+=line(x,y,cx+Math.cos(angle)*(45+pulse*20),cy+Math.sin(angle)*(45+pulse*20),tone,'stroke-width="3"');}}
 if(feedback.kind!=='skill')s+=require('./action-motion').motion(e.type,cx,cy,tone,progress);
 s+=portrait('event','', {team:e.type==='death'?'enemy':'ally'},76,156,34,avatar)+text(clip(options.section?.child?.name||e.targetNames?.join('、')||d.ability||'行动记录',wide?35:18),128,141,23,tone,'font-weight="bold"');
 const words=[...require('./combat-presentation').message(e,feedback)];for(let n=0;n<3;n++)s+=text(words.slice(n*(wide?47:25),(n+1)*(wide?47:25)).join(''),wide?40:36,215+n*28,19,'#e8dfca');
 if(feedback.killed&&feedback.full)s+=text('满伤害 · 伤害骰全满',36,wide?284:293,22,'#ffe071','font-weight="bold"');
 const dataY=wide?315:325,actual=r?.total??d.total;s+=rect(30,dataY-22,w-60,120,'#1b2c32','#62746b',10);
 if(actual!=null){s+=text('实际伤害',48,dataY+2,16,'#bdc6b5')+text(actual,48,dataY+43,36,tone,'font-weight="bold"')+text('HP '+(r?.hpBefore??d.hpBefore??'?')+' → '+(r?.hp??d.hp)+' / '+(r?.maxHP??d.maxHP??'?'),220,dataY+6,22,'#dce7d6')+bar(220,dataY+22,wide?450:320,r?.hp??d.hp,r?.maxHP??d.maxHP??1,'#87d5a1',10)+text(r?.dodge?.success?'闪避成功':!r?.perShot?'护甲减免未记录':'护甲减免 '+C.round2((r?.perShot||[]).reduce((n,s)=>n+Object.values(s.reduced||{}).reduce((a,b)=>a+b,0),0)),220,dataY+52,17,feedback.full?'#ffe071':'#b5c5b6');}
 else if((r?.healed??d.healed)!=null){const hp=r?.healthAfter||d.healthAfter;s+=text('正常HP恢复 '+(r?.healed??d.healed)+' · 倒地HP恢复 '+(r?.reserveHealed??d.reserveHealed??0),48,dataY+2,20,tone)+text('正常 HP '+hp.hp+'/'+hp.maxHP+(hp.downed?' · 等待救援':' · 可行动'),220,dataY+36,19,'#bce6c4')+bar(220,dataY+48,wide?450:320,hp.hp,hp.maxHP,'#87d5a1',8);}
 else s+=text(d.ammoRemaining!=null?'剩余载弹 '+d.ammoRemaining+' 发':d.remaining!=null?'剩余移动 '+d.remaining+' 米':e.type==='death'?'死亡记录已确认':d.opportunity?'行动机会 '+(d.opportunity.free?'免费':'已扣 '+(d.opportunity.apCost??100)+' AP'):'等待结算／已保存记录',48,dataY+20,24,tone)+text(clip(d.area?'AOE · '+e.targetNames?.length+' 名目标':d.magazine||d.ability||'',30),48,dataY+50,17);
 const health=r?.healthAfter||d.healthAfter;if(health?.reserveHP!=null)s+=text('倒地 HP '+health.reserveHP+'/'+health.maxHP+(health.downed?' · 倒地':' · 待用'),220,dataY+77,17,'#f2b474')+bar(220,dataY+87,wide?450:320,health.reserveHP,health.maxHP,'#edac6b',5);
 const shotPage=options.section?.shotPage||0;if(feedback.shots.length)s+=text('逐发页 '+(shotPage+1)+' · '+feedback.shots.slice(shotPage*4,shotPage*4+4).map((_,n)=>{const i=shotPage*4+n,v=r?.perShot?.[i];return '第'+(i+1)+'发 '+(v?v.total+(v.maxRoll?' MAX':''):'待结算');}).join(' / '),36,wide?438:447,16,'#d2c69e');
 if(!wide&&feedback.rp.length){s+=text('角色 RP',36,484,16,'#e0bc85');const rp=[...feedback.rp.map(r=>r.text).join(' / ')];for(let n=0;n<2;n++)s+=text(clip(rp.slice(n*27,(n+1)*27).join(''),27),36,512+n*25,18,'#c7d7cb');}
 if(feedback.killed)s+=text(r?.reward?'奖励已确认 · 实得经验 '+(r.reward.credited??r.reward.xp??0):'奖励待GM确认',36,wide?464:576,17,'#ffb58d');
 s+=text(clip(e.id,30)+' · 目标与逐发结果可翻页',36,h-(wide?18:27),13,'#99aba3');return s+'</svg>';}
function personalSVG(state,b,a,avatar){const p=B.actorCharacter(state,a),stats=M.stats(p),turn=b.current?.actorId===a.id?b.current:null,round=B.roundState(b),cost=B.opportunityCost(b,a.id);let s=base(640,580,'行动仪表 · '+a.name,'第'+round.number+'轮 · 本轮'+(round.counts[a.id]||0)+'次 · 下次 '+(Number.isFinite(cost)?cost+' AP':'等待重置'));
 s+=portrait('personal','',a,81,158,38,avatar,!!turn)+text('HP '+p.hp+' / '+stats.maxHP,147,146,28,'#a6e2b0','font-weight="bold"')+bar(147,166,425,p.hp,stats.maxHP,'#8ed19d',12)+(p.userId?text('倒地 HP '+(p.life?.reserveHP??stats.maxHP)+'/'+stats.maxHP+(require('./health').downed(p)?' · 等待救援':' · 待用'),147,193,16,'#eeb078')+bar(147,200,425,p.life?.reserveHP??stats.maxHP,stats.maxHP,'#eeb078',6):'')+text('AP '+p.ap,147,229,22,'#e9d095','font-weight="bold"');
 for(const [n,label,value] of [[0,'快速行动',turn?.quick??'—'],[1,'正式行动',turn?.formal??'—'],[2,'剩余移动',(turn?.move??'—')+'m']]){const x=36+n*191;s+=rect(x,237,177,94,'#24343a','#697668')+text(label,x+14,267,17,'#b9cbbd')+text(value,x+14,310,30,'#f0d092','font-weight="bold"');}
 s+=text(require('./health').downed(p)?'已倒地 · 等待同伴或GM救援':turn?'本行动机会'+(turn.free?'免费':'已扣 '+(turn.apCost??100)+' AP')+' · 同机会内不重复扣AP':'等待自己的行动机会',36,363,19,'#d4c7a9');let y=404;for(const ref of require('./weapons').equipped(p).slice(0,2)){const i=p.inventory[ref];s+=text(clip(i.snapshot.name,20)+(i.loaded?' · 载弹 '+i.loaded.current+'/'+i.loaded.capacity:' · 耐久 '+require('./durability').current(i)),36,y,20,'#deeadc');y+=32;}s+=text(clip('异常 '+(p.conditions.map(c=>c.template.name).join('、')||'无'),30),36,489,18,'#daa3a5')+text('操作前可选择 RP 并行动 · 文字结果先返回，地图后台刷新',36,548,15,'#aebfb4');return s+'</svg>';}
function itemGridSVG(title,items){const w=640,h=140+Math.ceil(items.length/3)*175;let s=base(w,h,title,'物品图鉴 · 按稀有度辨识');items.forEach((i,n)=>{const t=i.snapshot||i,x=28+n%3*196,y=116+Math.floor(n/3)*175,color=t.rarity==='red'?'#eb7d95':t.rarity==='gold'?'#eac780':'#9fbcac',uri=require('./loot-icons').uri(i);s+=rect(x,y,188,161,'#233238',color,9)+(uri?`<image href="${uri}" x="${x+42}" y="${y+6}" width="104" height="104"/>`:text('◇',x+94,y+72,45,color,'text-anchor="middle"'))+text(clip(t.name,10),x+94,y+133,16,'#e6e4ce','text-anchor="middle"')+text('×'+(i.quantity||1),x+94,y+153,13,color,'text-anchor="middle"');});return s+'</svg>';}
module.exports={battleSVG,eventSVG,personalSVG,itemGridSVG,obstacle,base,text,rect,line,bar,esc,clip};
