'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const{createLocal,dpapi}=require('../local/server.cjs');
test('local proxy rejects foreign Origin, CSRF, nonce replay and unsafe service URLs',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'gm-local-')),app=createLocal({directory,port:0,staticDir:path.join(__dirname,'../dist'),protect:async b=>b});const{url,origin}=await app.start();t.after(async()=>{await app.stop();fs.rmSync(directory,{recursive:true,force:true});});const r=await fetch(url,{redirect:'manual'}),cookie=r.headers.get('set-cookie').split(';')[0],headers={cookie};assert.equal((await fetch(url,{redirect:'manual'})).status,401);const local=(await(await fetch(origin+'/local/status',{headers})).json()).data;assert.ok(local.csrf);assert.equal((await fetch(origin+'/local/status',{headers:{...headers,origin:'https://evil.example'}})).status,403);assert.equal((await fetch(origin+'/local/drafts',{method:'POST',headers:{...headers,origin},body:'{}'})).status,422);const post={...headers,origin,'x-gm-csrf':local.csrf,'content-type':'application/json'};assert.equal((await fetch(origin+'/local/drafts',{method:'POST',headers:post,body:'{"mine":{"name":"草稿"}}'})).status,200);assert.equal((await(await fetch(origin+'/local/drafts',{headers})).json()).data.mine.name,'草稿');assert.equal((await fetch(origin+'/local/pair',{method:'POST',headers:post,body:'{"url":"http://evil.example","code":"bad"}'})).status,422);const credentialText=JSON.stringify(local);assert.ok(!credentialText.includes('secret'));});
test('Windows DPAPI protects credentials for current user and survives reopening', {skip:process.platform!=='win32'},async()=>{const clear=Buffer.from('{"test":"isolated fixture"}'),encrypted=await dpapi(clear);assert.ok(!encrypted.equals(clear));assert.deepEqual(await dpapi(encrypted,true),clear);});
test('table imports preserve snowflakes, nested effects, quoted multiline cells and template kind',async()=>{const{parseImport,exportCsv,set}=await import('../src/data.js');const rows=[{kind:'item',baseVersion:0,data:{kind:'药品',name:'药,"\n两行',weightKg:0,heal:'1d6',effects:[{target:'constitution',op:'add',value:1}]}},{kind:'trait',id:'t123',baseVersion:2,data:{name:'特质',effects:[]}}];const decoded=parseImport(exportCsv(rows),'item');assert.deepEqual(decoded,rows);const grants=parseImport('uid\ttype\tquantity\n123456789012345678\tpoints\t3','grant');assert.equal(grants[0].data.uid,'123456789012345678');assert.equal(grants[0].data.quantity,3);assert.throws(()=>set({},'__proto__.polluted',true),/无效/);assert.equal({}.polluted,undefined);assert.throws(()=>parseImport('name\n"未闭合','item'),/闭合/);assert.ok(exportCsv([{kind:'trait',data:{name:'=formula()'}}]).includes("'=formula()"));});

test('pairing retry after a lost response reuses the protected device secret, then restores login',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'gm-pair-')),sent=[];let fail=true;const fetcher=async(url,init)=>{sent.push(JSON.parse(init.body));if(fail){fail=false;throw Error('response lost');}return new Response(JSON.stringify({data:{guildId:'123456789012345678',userId:'123456789012345679'}}),{status:200,headers:{'content-type':'application/json'}});};let app=createLocal({directory,port:0,protect:async b=>b,fetcher});t.after(async()=>{await app.stop();fs.rmSync(directory,{recursive:true,force:true});});async function session(){const a=await app.start(),r=await fetch(a.url,{redirect:'manual'}),cookie=r.headers.get('set-cookie').split(';')[0],data=(await(await fetch(a.origin+'/local/status',{headers:{cookie}})).json()).data;return{origin:a.origin,headers:{cookie,origin:a.origin,'x-gm-csrf':data.csrf,'content-type':'application/json'},data};}let s=await session();const request=()=>fetch(s.origin+'/local/pair',{method:'POST',headers:s.headers,body:JSON.stringify({url:'https://bot.example',code:'GW-fixed'})});assert.equal((await request()).status,422);assert.equal((await request()).status,200);assert.deepEqual(sent[0],sent[1]);await app.stop();app=createLocal({directory,port:0,protect:async b=>b});s=await session();assert.equal(s.data.bound,true);assert.ok(!JSON.stringify(s.data).includes('secret'));});

test('Windows proxy parsing accepts current HTTP settings and rejects PAC or executable paths',()=>{const{proxySettings}=require('../local/server.cjs');assert.equal(proxySettings('127.0.0.1:7897').HTTPS_PROXY,'http://127.0.0.1:7897');assert.equal(proxySettings('http=127.0.0.1:80;https=127.0.0.1:81').HTTPS_PROXY,'http://127.0.0.1:81');assert.deepEqual(proxySettings('https://proxy.example/pac'),{});assert.deepEqual(proxySettings('socks=127.0.0.1:90'),{});});
