import React,{useEffect,useState} from 'react';
import {api} from './api';
const types={physical:'物理',magical:'魔法',mental:'精神'};
export function SkillBook({game,groupId,userId,prepare,artStyle='tactical'}){
 const [q,Q]=useState(''),[type,Type]=useState(''),[action,Action]=useState(''),[key,Key]=useState(''),[bid,Bid]=useState(''),[target,Target]=useState(''),[center,Center]=useState(null),[targets,Targets]=useState([]),[rp,RP]=useState(''),[check,Check]=useState(null);
 const skills=game.skills||[],skill=skills.find(a=>a.key===key)?.attack,b=game.battles.find(b=>b.id===bid)||game.battles.find(b=>b.actors.some(a=>a.userId===userId)),actor=b?.actors.find(a=>a.userId===userId),area=skill?.aoe?.mode&&skill.aoe.mode!=='single';
 const params=()=>({battleId:b?.id,turnId:b?.current?.id,action:'attack',params:{abilityKey:key,targetId:target,action:skill?.action||'formal',center,targets,firing:{mode:'semi',count:1}},rp});
 useEffect(()=>{Check(null);if(!skill||!b||!actor)return;let alive=true;const t=setTimeout(()=>api('/groups/'+groupId+'/game/skill-check',params()).then(r=>{if(alive)Check(r);}).catch(e=>{if(alive)Check({available:false,reason:e.message});}),150);return()=>{alive=false;clearTimeout(t);};},[groupId,key,b?.id,b?.current?.id,game.versions?.['players:'+userId],game.versions?.['battles:'+b?.id],target,JSON.stringify(center),targets.join(',')]);
 const select=key=>{Key(key);Target('');Center(null);Targets([]);Check(null);};
 return <div className={'skill-book art-'+artStyle}>
  <section className="panel skill-header"><span className="eyebrow">ARSENAL · ARCANA · PSYCHE</span><h2 className="art-title">技能卡册</h2><p>每张卡沿用你的实际技能快照；施放前显示资源与限制。</p><div className="toolbar"><input aria-label="搜索技能" placeholder="搜索技能名称" value={q} onChange={e=>Q(e.target.value)}/><select aria-label="伤害类型" value={type} onChange={e=>Type(e.target.value)}><option value="">全部伤害类型</option>{Object.entries(types).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="行动类型" value={action} onChange={e=>Action(e.target.value)}><option value="">全部行动类型</option><option value="quick">快速行动</option><option value="formal">正式行动</option></select></div></section>
  <div className="skill-gallery">{skills.filter(({attack:t})=>t.name.includes(q)&&(!type||t.primary===type||t.damage?.[type]&&t.damage[type]!=='0')&&(!action||(t.action||'formal')===action)).map(({key:k,attack:t})=><button key={k} className={'skill-card '+(k===key?'selected':'')} onClick={()=>select(k)}><span className="skill-sigil" aria-hidden="true">{t.primary==='magical'?'✧':t.primary==='mental'?'◈':'⌖'}</span><h3 className="art-title">{t.name}</h3><p>{t.description}</p><div className="skill-numbers">{Object.entries(types).filter(([k])=>t.damage?.[k]&&t.damage[k]!=='0').map(([k,v])=><span key={k}>{v}<b>{t.damage[k]}</b></span>)}<span>命中<b>{t.hit}</b></span><span>射程<b>{t.rangeMeters??(t.range||0)*50} m</b></span></div><div className="skill-tags"><span>{t.action==='quick'?'快速':'正式'}行动 ×1</span><span>{t.casting?'吟唱 '+t.casting+' 次':'瞬发'}</span><span>{t.aoe?.mode==='single'||!t.aoe?'单体':'范围 '+t.aoe.radius+'m'}</span>{t.requiresWeapon&&<span>需武器</span>}</div>{t.conditions?.length>0&&<p>附带异常：{t.conditions.map(c=>(c.template?.name||'异常')+'·'+c.severity).join('、')}</p>}</button>)}</div>
  {!skills.length&&<section className="panel">尚未学习战斗技能，GM 发放后会出现在这里。</section>}
  {skill&&<section className="panel skill-cast"><span className="eyebrow">CASTING CONSOLE</span><h2 className="art-title">释放 · {skill.name}</h2><label className="field"><span>所在战斗</span><select value={b?.id||''} onChange={e=>Bid(e.target.value)}><option value="">选择战斗</option>{game.battles.filter(b=>b.actors.some(a=>a.userId===userId)).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><p>消耗：{skill.action==='quick'?'快速':'正式'}行动一次。{b&&actor&&b.current?.actorId===actor.id?'本机会已扣 '+(b.current.apCost||0)+' AP；施放不重复扣AP。':'等待你的行动机会。'}</p>
   <label className="field"><span>{area?'范围中心目标':'施放目标'}</span><select value={target} onChange={e=>{Target(e.target.value);const a=b?.actors.find(a=>a.id===e.target.value);Center(a?{x:a.x,y:a.y}:null);}}><option value="">请选择目标</option>{b?.actors.filter(a=>!a.deathId&&!a.retreated&&a.id!==actor?.id).map(a=><option key={a.id} value={a.id}>{a.name} · HP {a.health.hp}/{a.health.maxHP}{a.health.downed?' · 倒地':''}</option>)}</select></label>
   {area&&b&&<><p>点击战场格子选择范围中心（半径 {skill.aoe.radius} 米）。</p><div className="skill-area-grid" style={{gridTemplateColumns:'repeat('+b.width+',minmax(38px,1fr))'}}>{Array.from({length:b.height*b.width},(_,n)=>{const x=n%b.width,y=Math.floor(n/b.width);return <button key={n} className={center?.x===x*50+25&&center?.y===y*50+25?'selected':''} onClick={()=>Center({x:x*50+25,y:y*50+25})}>{String.fromCharCode(65+x)}{y+1}</button>;})}</div>{skill.aoe.mode==='selective'&&<div className="toolbar">{b.actors.filter(a=>!a.deathId&&!a.retreated).map(a=><label key={a.id}><input type="checkbox" checked={targets.includes(a.id)} onChange={e=>Targets(e.target.checked?[...targets,a.id]:targets.filter(id=>id!==a.id))}/>{a.name}</label>)}</div>}</>}
   <label className="field"><span className="art-title">行动 RP（选填）</span><textarea maxLength={1000} value={rp} onChange={e=>RP(e.target.value)} placeholder="描述这次技能施放，将随真实操作一起保存。"/></label>
   {check?.reason&&<p className="error" role="status">{check.reason}</p>}<button className="primary cast-button" disabled={!check?.available} onClick={()=>prepare('battle.action',params())}>{skill.casting?'吟唱／释放技能':'释放技能'}</button>
  </section>}
 </div>;
}
